-- Enriquecimiento de landings desde fichas técnicas oficiales del fabricante (konfort-plus-caminadores).
-- Contenido redactado solo con datos presentes en la ficha; ver informe docs/informe-fichas-fabricantes-2026-10-02.md.
-- Se aplica con el workflow manual "Deploy Supabase Migrations". Idempotente (UPDATE por slug).

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp1-8120l-ft.pdf',
  descripcion_larga_es = $d$El caminador Doble Función KP1-8120L en aluminio anodizado color bronce está diseñado para ofrecer una solución versátil y elegante a aquellos que requieren asistencia en la movilidad. Su diseño permite utilizarlo como un caminador paso a paso para mayor estabilidad o como un caminador estándar de un solo botón para una movilidad más rápida. Fabricado en aluminio anodizado, este caminador destaca por su acabado en color bronce, que combina estilo y durabilidad.

El caminador de doble función Konfort Plus en aluminio anodizado con manilares de PVC gris puede usarse paso a paso o como caminador estándar de un solo botón. Es plegable, graduable en altura con pines (77 a 96,5 cm), tiene tapones antideslizantes para mayor tracción, soporta 113 kg y ofrece 2 años de garantía.$d$,
  descripcion_larga_en = $d$The KP1-8120L Dual Function Walker in anodized aluminum bronze color is designed to offer a versatile and elegant solution for those who require mobility assistance. Its design allows use as a step-by-step walker for greater stability or as a standard single-button walker for faster mobility. Made of anodized aluminum, this walker stands out for its bronze finish, which combines style and durability.

The Konfort Plus dual-function walker in anodised aluminium with grey PVC handles can be used step-by-step or as a standard one-button walker. It is foldable, height-adjustable with pins (77 to 96.5 cm), has anti-slip tips for greater traction, supports 113 kg and offers a 2-year warranty.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP1-8120L"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"113 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"77 - 96,5 cm"},{"clave":"Estructura / empuñadura","grupo":"Material","valor":"Aluminio anodizado / PVC gris"},{"clave":"Garantía","grupo":"Garantía","valor":"2 años"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Doble función: paso a paso o estándar de un solo botón.","Plegable y graduable de 77 a 96,5 cm con pines.","Soporta 113 kg y tiene 2 años de garantía."],"beneficios_en":["Dual function: step-by-step or standard one-button.","Foldable and adjustable from 77 to 96.5 cm with pins.","Supports 113 kg and has a 2-year warranty."],"valor_es":"Un caminador plegable de aluminio con doble función, según la ficha oficial de Konfort Plus.","valor_en":"A foldable aluminium walker with dual function, per the official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué peso soporta?","a":"113 kg."},{"q":"¿Qué altura alcanza?","a":"De 77 a 96,5 cm."},{"q":"¿Se pliega?","a":"Sí, tiene mecanismo de plegado accionado con la mano."},{"q":"¿Dónde descargo la ficha técnica de Caminador Doble Función En Bronce Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What weight does it support?","a":"113 kg."},{"q":"What height does it reach?","a":"From 77 to 96.5 cm."},{"q":"Does it fold?","a":"Yes, with a hand-operated folding mechanism."},{"q":"Where can I download the Konfort Plus Dual Function Walker in Bronze KP1-8120L datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["caminador doble función de aluminio","caminador plegable","caminador paso a paso","caminador Konfort Plus","caminador ortopédico Colombia","ficha técnica KP1-8120L"],"seo_keywords_en":["dual-function aluminium walker","folding walker","step-by-step walker","Konfort Plus walker","orthopaedic walker Colombia","KP1-8120L datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MC7NSY2QXYDRCF7CZRJRTHXIXQUY?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'caminador-doble-funcion-en-bronce-ref-kp1-8120l-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kp1-8130g-5-ft.pdf',
  descripcion_larga_es = $d$El Caminador Doble Función con Ruedas KP1-8130G-5 ofrece versatilidad para usuarios que requieren apoyo tanto en desplazamiento como en bipedestación. Fabricado en acero resistente, combina la funcionalidad de un caminador fijo y un rollator, facilitando la rehabilitación y la movilidad diaria. Su diseño robusto incluye ruedas guía que permiten un desplazamiento seguro en diferentes superficies.

El caminador doble función con ruedas Konfort Plus es de acero gris con dos ruedas, estructura plegable de un botón, graduable en 8 puntos de altura (76 a 94 cm) y empuñadura de PVC de larga duración. Está pensado para uso en interiores por personas que necesitan asistencia y estabilidad para la marcha.$d$,
  descripcion_larga_en = $d$The Dual-Function Wheeled Walker KP1-8130G-5 offers versatility for users requiring support in both ambulation and standing. Made of resistant steel, it combines the functionality of a fixed walker and a rollator, facilitating rehabilitation and daily mobility. Its robust design includes guide wheels that allow safe movement on different surfaces.

The Konfort Plus dual-function walker with wheels is grey steel with two wheels, a one-button folding structure, adjustable at 8 height points (76 to 94 cm) and a long-lasting PVC handle. It is designed for indoor use by people who need assistance and stability when walking.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP1-8130G-5"},{"clave":"Altura","grupo":"Dimensiones","valor":"76 - 94 cm (8 puntos)"},{"clave":"Estructura / empuñadura","grupo":"Material","valor":"Acero gris / PVC"},{"clave":"Ruedas","grupo":"Ruedas","valor":"2 delanteras"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Dos ruedas delanteras y doble función (fijo y paso a paso).","Graduable en 8 puntos de altura, de 76 a 94 cm.","Estructura de acero plegable con un botón y empuñadura de PVC."],"beneficios_en":["Two front wheels and dual function (fixed and step-by-step).","Adjustable at 8 height points, from 76 to 94 cm.","One-button folding steel structure and PVC handle."],"valor_es":"Un caminador de acero con ruedas y doble función para interiores.","valor_en":"A steel walker with wheels and dual function for indoor use.","preguntas_frecuentes_es":[{"q":"¿Cuántas alturas tiene?","a":"8 puntos de regulación, de 76 a 94 cm."},{"q":"¿Cuántas ruedas tiene?","a":"Dos ruedas."},{"q":"¿Para qué uso es?","a":"Ideal para interiores, según el fabricante."},{"q":"¿Dónde descargo la ficha técnica de Caminador Doble Función con Ruedas?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"How many heights does it have?","a":"8 adjustment points, from 76 to 94 cm."},{"q":"How many wheels does it have?","a":"Two wheels."},{"q":"What use is it for?","a":"Ideal for indoors, per the manufacturer."},{"q":"Where can I download the Dual-Function Wheeled Walker datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["caminador con ruedas de acero","caminador doble función con ruedas","caminador plegable gris","caminador Konfort Plus","caminador Colombia","ficha técnica KP1-8130G-5"],"seo_keywords_en":["steel walker with wheels","dual-function walker with wheels","grey folding walker","Konfort Plus walker","walker Colombia","KP1-8130G-5 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCR2GZQO7PN5F7TOCTSLOW4EHAG4?version=2.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'caminador-doble-funcion-con-ruedas-ref-kp1-8130g-5';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kp1-8150l3-ft.pdf',
  descripcion_larga_es = $d$El caminador Doble Función KP1-8150L3 en aluminio anodizado color gris está diseñado para ofrecer una solución versátil, elegante y cómoda a usuarios que requieren asistencia en la movilidad. Con su doble función, este caminador se adapta fácilmente a las necesidades del usuario, permitiendo un uso estable en modo paso a paso o más ágil en modo estándar. Fabricado en aluminio anodizado, destaca por su acabado moderno y su resistencia a la corrosión, asegurando durabilidad y un aspecto atractivo.

El caminador doble función Konfort Plus KP1-8150L3 es de aluminio anodizado gris con manilares y tapones de TPR. Puede usarse como caminador paso a paso o estándar de un solo botón, cuenta con mecanismo de plegado, altura de 75 a 85 cm y capacidad de 115 kg (clase I, riesgo bajo).$d$,
  descripcion_larga_en = $d$The KP1-8150L3 Dual Function Walker in anodized aluminum gray color is designed to offer a versatile, elegant and comfortable solution for users who require mobility assistance. With its dual function, this walker easily adapts to the user's needs, allowing stable use in step-by-step mode or more agile use in standard mode. Made of anodized aluminum, it stands out for its modern finish and corrosion resistance, ensuring durability and an attractive appearance.

The Konfort Plus KP1-8150L3 dual-function walker is grey anodised aluminium with TPR handles and tips. It can be used as a step-by-step or standard one-button walker, has a folding mechanism, a height of 75 to 85 cm and a capacity of 115 kg (class I, low risk).$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP1-8150L3"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"115 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"75 - 85 cm"},{"clave":"Estructura / manilares","grupo":"Material","valor":"Aluminio anodizado / TPR"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Manilares y tapones de TPR para mejor agarre.","Doble función y mecanismo de plegado.","Capacidad de 115 kg y altura de 75 a 85 cm."],"beneficios_en":["TPR handles and tips for better grip.","Dual function and folding mechanism.","115 kg capacity and 75 to 85 cm height."],"valor_es":"Un caminador de aluminio con manilares de TPR y doble función.","valor_en":"An aluminium walker with TPR handles and dual function.","preguntas_frecuentes_es":[{"q":"¿Qué capacidad tiene?","a":"115 kg."},{"q":"¿De qué material son los manilares?","a":"De TPR."},{"q":"¿Qué altura tiene?","a":"De 75 a 85 cm."},{"q":"¿Dónde descargo la ficha técnica de Caminador Doble Función KP1-8150L3?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What capacity does it have?","a":"115 kg."},{"q":"What are the handles made of?","a":"TPR."},{"q":"What height does it have?","a":"From 75 to 85 cm."},{"q":"Where can I download the Konfort Plus Dual Function Walker KP1-8150L3 datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["caminador de aluminio KP1-8150L3","caminador doble función TPR","caminador plegable","caminador Konfort Plus","caminador Colombia","ficha técnica KP1-8150L3"],"seo_keywords_en":["KP1-8150L3 aluminium walker","TPR dual-function walker","folding walker","Konfort Plus walker","walker Colombia","KP1-8150L3 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCLJ6WF4TAIJG7TOTOQLTRMGH67E?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'caminador-doble-funcion-ref-kp1-8150l3';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp1-8160l-ft.pdf',
  descripcion_larga_es = $d$El caminador en aluminio desarmable está diseñado para brindar apoyo, estabilidad y seguridad a personas con movilidad reducida o en procesos de rehabilitación. Su estructura en aluminio combina ligereza y resistencia, facilitando el uso diario sin generar sobreesfuerzo durante el desplazamiento. Su diseño desarmable permite desmontarlo de manera sencilla, facilitando el transporte y el almacenamiento cuando no está en uso. Esta característica lo convierte en una ayuda práctica tanto para el hogar como para traslados, terapias o acompañamientos fuera de casa.

El caminador desarmable Konfort Plus en aleación de aluminio tiene patas removibles y doble función (fija y paso a paso). Pesa 2,4 kg, se gradúa en 8 niveles (74,5 a 92,5 cm), soporta 110 kg, tiene vida útil de 5 años y es clase I. Es liviano, fácil de almacenar y apto para uso domiciliario o institucional.$d$,
  descripcion_larga_en = $d$Lightweight, foldable aluminum structure that eases transport and storage without compromising walking stability. Ideal for long rehabilitation processes and users who require portable mobility assistance at home or health centers.

The Konfort Plus take-apart walker in aluminium alloy has removable legs and dual function (fixed and step-by-step). It weighs 2.4 kg, adjusts in 8 levels (74.5 to 92.5 cm), supports 110 kg, has a 5-year service life and is class I. It is lightweight, easy to store and suitable for home or institutional use.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP1-8160L"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"110 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"74,5 - 92,5 cm (8 niveles)"},{"clave":"Peso neto","grupo":"Peso","valor":"2,4 kg"},{"clave":"Vida útil","grupo":"Vida útil","valor":"5 años"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Solo 2,4 kg y patas removibles para guardarlo y transportarlo.","8 niveles de altura de 74,5 a 92,5 cm.","Capacidad de 110 kg y vida útil de 5 años."],"beneficios_en":["Only 2.4 kg with removable legs to store and carry.","8 height levels from 74.5 to 92.5 cm.","110 kg capacity and 5-year service life."],"valor_es":"Un caminador de aluminio desarmable y liviano con doble función.","valor_en":"A lightweight take-apart aluminium walker with dual function.","preguntas_frecuentes_es":[{"q":"¿Cuánto pesa?","a":"2,4 kg."},{"q":"¿Cuántos niveles de altura tiene?","a":"8 niveles, de 74,5 a 92,5 cm."},{"q":"¿Qué capacidad tiene?","a":"110 kg."},{"q":"¿Dónde descargo la ficha técnica de Caminador Desarmable En Aluminio Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"How much does it weigh?","a":"2.4 kg."},{"q":"How many height levels does it have?","a":"8 levels, from 74.5 to 92.5 cm."},{"q":"What capacity does it have?","a":"110 kg."},{"q":"Where can I download the Disassemblable Aluminum Walker Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["caminador desarmable de aluminio","caminador liviano 2,4 kg","caminador doble función","caminador Konfort Plus","caminador Colombia","ficha técnica KP1-8160L"],"seo_keywords_en":["take-apart aluminium walker","lightweight 2.4 kg walker","dual-function walker","Konfort Plus walker","walker Colombia","KP1-8160L datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCRWPOKIG26VG3PHA5JVSYG5IXUY?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'caminador-desarmable-en-aluminio-ref-kp1-8160l-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp1-816l-19-ft.pdf',
  descripcion_larga_es = $d$El caminador Stand Up Doble Función KP1-816L está diseñado para ofrecer una solución versátil y cómoda a usuarios que requieren asistencia en la movilidad. Con su doble función, este caminador se adapta fácilmente a las necesidades del usuario, permitiendo un uso estable en modo paso a paso o más ágil en modo estándar. Fabricado en aluminio con alma de hierro, combina ligereza y durabilidad, asegurando un manejo fácil y un soporte confiable.

El caminador stand up doble función Konfort Plus es de aluminio con alma de hierro, plegable, con empuñaduras de PVC (gris y negro), altura de 70 a 88 cm y capacidad de 113 kg. Pesa 11 kg en caja y es clase I (riesgo bajo).$d$,
  descripcion_larga_en = $d$The Stand Up Dual Function Walker KP1-816L is designed to offer a versatile and comfortable solution for users who require mobility assistance. With its dual function, this walker easily adapts to the user's needs, allowing stable use in step-by-step mode or more agile use in standard mode. Made of aluminum with an iron core, it combines lightness and durability, ensuring easy handling and reliable support.

The Konfort Plus dual-function stand-up walker is aluminium with an iron core, foldable, with PVC handles (grey and black), a height of 70 to 88 cm and a capacity of 113 kg. It weighs 11 kg boxed and is class I (low risk).$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP1-816L-19"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"113 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"70 - 88 cm"},{"clave":"Estructura","grupo":"Material","valor":"Aluminio con alma de hierro"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Diseño stand up con doble función.","Altura de 70 a 88 cm y capacidad de 113 kg.","Aluminio con alma de hierro, plegable."],"beneficios_en":["Stand-up design with dual function.","Height from 70 to 88 cm and 113 kg capacity.","Aluminium with iron core, foldable."],"valor_es":"Un caminador stand up plegable de aluminio.","valor_en":"A foldable aluminium stand-up walker.","preguntas_frecuentes_es":[{"q":"¿Qué capacidad tiene?","a":"113 kg."},{"q":"¿En qué colores viene la empuñadura?","a":"PVC en gris y negro."},{"q":"¿Se pliega?","a":"Sí, es plegable."},{"q":"¿Dónde descargo la ficha técnica de Caminador Stand Up Doble Función Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What capacity does it have?","a":"113 kg."},{"q":"Which colours is the handle available in?","a":"PVC in grey and black."},{"q":"Does it fold?","a":"Yes, it is foldable."},{"q":"Where can I download the Konfort Plus Stand Up Dual Function Walker KP1-816L datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["caminador stand up","caminador doble función aluminio","caminador plegable","caminador Konfort Plus","caminador Colombia","ficha técnica KP1-816L-19"],"seo_keywords_en":["stand-up walker","dual-function aluminium walker","folding walker","Konfort Plus walker","walker Colombia","KP1-816L-19 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCWNXVUGY2NZFVHP7PBJ6B7E44LI?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'caminador-stand-up-doble-funcion-ref-kp1-816l-19-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kp1342al-19-ft.pdf',
  descripcion_larga_es = $d$El caminador doble función Konfort Plus está diseñado para ofrecer una solución versátil y confiable a aquellos que requieren asistencia en la movilidad. Fabricado en aluminio con alma de hierro, este caminador combina ligereza con durabilidad, proporcionando un soporte seguro y fácil de manejar. Su diseño permite utilizarlo como un caminador paso a paso para mayor estabilidad o como un caminador estándar de un solo botón para una movilidad más rápida.

El caminador doble función Konfort Plus KP1342AL-19 (sin ruedas) puede usarse paso a paso o como caminador estándar de un solo botón. Es de aluminio con alma de hierro, plegable, con altura de 75 a 92,5 cm, manilares de PVC gris y capacidad de 113 kg.$d$,
  descripcion_larga_en = $d$The Konfort Plus dual-function walker is designed to offer a versatile and reliable solution for those who require mobility assistance. Made of aluminum with an iron core, this walker combines lightness with durability, providing safe and easy-to-handle support. Its design allows use as a step-by-step walker for greater stability or as a standard single-button walker for faster mobility.

The Konfort Plus KP1342AL-19 dual-function walker (without wheels) can be used step-by-step or as a standard one-button walker. It is aluminium with an iron core, foldable, with a height of 75 to 92.5 cm, grey PVC handles and a capacity of 113 kg.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP1342AL-19"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"113 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"75 - 92,5 cm"},{"clave":"Estructura / manilares","grupo":"Material","valor":"Aluminio con alma de hierro / PVC gris"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Doble función: paso a paso o estándar.","Altura de 75 a 92,5 cm, plegable.","Capacidad de 113 kg con manilares de PVC."],"beneficios_en":["Dual function: step-by-step or standard.","Height from 75 to 92.5 cm, foldable.","113 kg capacity with PVC handles."],"valor_es":"Un caminador doble función de aluminio, sin ruedas.","valor_en":"A dual-function aluminium walker without wheels.","preguntas_frecuentes_es":[{"q":"¿Tiene ruedas?","a":"No, es la versión sin ruedas."},{"q":"¿Qué capacidad tiene?","a":"113 kg."},{"q":"¿Qué altura tiene?","a":"De 75 a 92,5 cm."},{"q":"¿Dónde descargo la ficha técnica de Caminador Doble Función KP1342AL-19?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Does it have wheels?","a":"No, it is the wheel-less version."},{"q":"What capacity does it have?","a":"113 kg."},{"q":"What height does it have?","a":"From 75 to 92.5 cm."},{"q":"Where can I download the Konfort Plus Dual Function Walker KP1342AL-19 datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["caminador doble función sin ruedas","caminador KP1342AL","caminador plegable de aluminio","caminador Konfort Plus","caminador Colombia","ficha técnica KP1342AL-19"],"seo_keywords_en":["dual-function walker without wheels","KP1342AL walker","folding aluminium walker","Konfort Plus walker","walker Colombia","KP1342AL-19 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCV5YQVB3TGJGR3DDZYTVHFMTMIQ?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'caminador-doble-funcion-ref-kp1342al-19';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp153-al-12-ft.pdf',
  descripcion_larga_es = $d$El caminador con ruedas de 5” en aluminio anodizado KP es la elección perfecta para quienes buscan un dispositivo de movilidad que combine ligereza, durabilidad y funcionalidad. El material de su estructura garantiza una larga vida útil, mientras que las ruedas macizas de 5” con rin estrella aseguran un desplazamiento suave en cualquier superficie. Ajustable en altura, este caminador se adapta a las necesidades de cada usuario, proporcionando un soporte cómodo y personalizado.

El caminador con ruedas de 5" en aluminio anodizado Konfort Plus (azul) es una ayuda de movilidad estable y cómoda para personas con movilidad reducida. Su estructura de aluminio con barras laterales reforzadas ofrece dos funciones (fijo y paso a paso), es plegable con un solo botón, graduable en altura (78 a 96 cm), con ruedas macizas de rin estrella y empuñaduras ergonómicas; soporta 113 kg y tiene 2 años de garantía.$d$,
  descripcion_larga_en = $d$The KP 5" wheel walker in anodized aluminum is the perfect choice for those seeking a mobility device that combines lightness, durability and functionality. The material of its structure guarantees a long service life, while the 5" solid wheels with star rim ensure smooth movement on any surface. Adjustable in height, this walker adapts to each user's needs, providing comfortable and personalized support.

The Konfort Plus 5" wheeled walker in anodised aluminium (blue) is a stable, comfortable mobility aid for people with reduced mobility. Its aluminium structure with reinforced side bars offers two functions (fixed and step-by-step), folds with a single button, is height-adjustable (78 to 96 cm), with solid star-rim wheels and ergonomic handles; it supports 113 kg and has a 2-year warranty.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP153-AL-12"},{"clave":"Color","grupo":"Variante","valor":"Azul"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"113 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"78 - 96 cm"},{"clave":"Ruedas","grupo":"Ruedas","valor":"Macizas 5\" rin estrella"},{"clave":"Garantía","grupo":"Garantía","valor":"2 años"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Dos funciones (fijo y paso a paso) y plegado con un solo botón.","Ruedas macizas de 5\" con rin estrella y altura de 78 a 96 cm.","Capacidad de 113 kg y 2 años de garantía."],"beneficios_en":["Two functions (fixed and step-by-step) and one-button folding.","Solid 5\" star-rim wheels and 78 to 96 cm height.","113 kg capacity and 2-year warranty."],"valor_es":"Un caminador de aluminio con ruedas de 5\" y plegado de un botón, con ficha oficial de Konfort Plus.","valor_en":"An aluminium walker with 5\" wheels and one-button folding, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué tamaño tienen las ruedas?","a":"5 pulgadas, macizas con rin estrella."},{"q":"¿Qué capacidad tiene?","a":"113 kg."},{"q":"¿Qué colores hay?","a":"Disponible en azul y gris, entre otros."},{"q":"¿Dónde descargo la ficha técnica de Caminador Con Ruedas de 5\" En Aluminio Color Azul Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What size are the wheels?","a":"5 inches, solid with star rim."},{"q":"What capacity does it have?","a":"113 kg."},{"q":"Which colours are there?","a":"Available in blue and grey, among others."},{"q":"Where can I download the Konfort Plus Aluminum 5\" Wheel Walker Blue Color datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["caminador con ruedas azul","caminador de aluminio con ruedas de 5\"","caminador doble función con ruedas","caminador Konfort Plus","caminador Colombia","ficha técnica KP153-AL-12"],"seo_keywords_en":["wheeled walker blue","aluminium walker with 5\" wheels","dual-function wheeled walker","Konfort Plus walker","walker Colombia","KP153-AL-12 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCN33BUCBZTRES3GZKGDHUJT4NUE?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'caminador-con-ruedas-de-5-en-aluminio-color-azul-ref-kp153-al-12-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp153-al-19-ft.pdf',
  descripcion_larga_es = $d$El caminador con ruedas de 5” en aluminio anodizado KP es la elección perfecta para quienes buscan un dispositivo de movilidad que combine ligereza, durabilidad y funcionalidad. El material de su estructura garantiza una larga vida útil, mientras que las ruedas macizas de 5” con rin estrella aseguran un desplazamiento suave en cualquier superficie. Ajustable en altura, este caminador se adapta a las necesidades de cada usuario, proporcionando un soporte cómodo y personalizado.

El caminador con ruedas de 5" en aluminio anodizado Konfort Plus (gris) es una ayuda de movilidad estable y cómoda para personas con movilidad reducida. Su estructura de aluminio con barras laterales reforzadas ofrece dos funciones (fijo y paso a paso), es plegable con un solo botón, graduable en altura (78 a 96 cm), con ruedas macizas de rin estrella y empuñaduras ergonómicas; soporta 113 kg y tiene 2 años de garantía.$d$,
  descripcion_larga_en = $d$The KP 5" wheel walker in anodized aluminum is the perfect choice for those seeking a mobility device that combines lightness, durability and functionality. The material of its structure guarantees a long service life, while the 5" solid wheels with star rim ensure smooth movement on any surface. Adjustable in height, this walker adapts to each user's needs, providing comfortable and personalized support.

The Konfort Plus 5" wheeled walker in anodised aluminium (grey) is a stable, comfortable mobility aid for people with reduced mobility. Its aluminium structure with reinforced side bars offers two functions (fixed and step-by-step), folds with a single button, is height-adjustable (78 to 96 cm), with solid star-rim wheels and ergonomic handles; it supports 113 kg and has a 2-year warranty.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP153-AL-19"},{"clave":"Color","grupo":"Variante","valor":"Gris"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"113 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"78 - 96 cm"},{"clave":"Ruedas","grupo":"Ruedas","valor":"Macizas 5\" rin estrella"},{"clave":"Garantía","grupo":"Garantía","valor":"2 años"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Dos funciones (fijo y paso a paso) y plegado con un solo botón.","Ruedas macizas de 5\" con rin estrella y altura de 78 a 96 cm.","Capacidad de 113 kg y 2 años de garantía."],"beneficios_en":["Two functions (fixed and step-by-step) and one-button folding.","Solid 5\" star-rim wheels and 78 to 96 cm height.","113 kg capacity and 2-year warranty."],"valor_es":"Un caminador de aluminio con ruedas de 5\" y plegado de un botón, con ficha oficial de Konfort Plus.","valor_en":"An aluminium walker with 5\" wheels and one-button folding, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué tamaño tienen las ruedas?","a":"5 pulgadas, macizas con rin estrella."},{"q":"¿Qué capacidad tiene?","a":"113 kg."},{"q":"¿Qué colores hay?","a":"Disponible en azul y gris, entre otros."},{"q":"¿Dónde descargo la ficha técnica de Caminador Con Ruedas de 5\" En Aluminio Color Gris Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What size are the wheels?","a":"5 inches, solid with star rim."},{"q":"What capacity does it have?","a":"113 kg."},{"q":"Which colours are there?","a":"Available in blue and grey, among others."},{"q":"Where can I download the Konfort Plus Aluminum 5\" Wheel Walker Gray Color datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["caminador con ruedas gris","caminador de aluminio con ruedas de 5\"","caminador doble función con ruedas","caminador Konfort Plus","caminador Colombia","ficha técnica KP153-AL-19"],"seo_keywords_en":["wheeled walker grey","aluminium walker with 5\" wheels","dual-function wheeled walker","Konfort Plus walker","walker Colombia","KP153-AL-19 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCEKDFQOSNCRFMPJBMX5ECSDMLAU?version=2.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'caminador-con-ruedas-de-5-en-aluminio-color-gris-ref-kp153-al-19-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kp1-8437-ft.pdf',
  descripcion_larga_es = $d$El caminador con ruedas KP1-8437 está diseñado para brindar un apoyo seguro y confiable a los usuarios que requieren asistencia en la movilidad en una variedad de entornos, tanto en interiores como exteriores. Fabricado en acero resistente, este rollator combina durabilidad con comodidad, gracias a su asiento más amplio de 35 cm con respaldo tipo barra y su bolsa de almacenamiento bajo el asiento.

El rollator en acero Konfort Plus (gris) es un caminador con cuatro ruedas y asiento que cuenta con bolsa bajo el asiento, altura graduable de las empuñaduras, espaldar tipo barra y freno de doble función accionado desde las empuñaduras. Es ideal para apoyar la movilidad de usuarios que requieren asistencia en la marcha, especialmente en interiores, con capacidad de 100 kg.$d$,
  descripcion_larga_en = $d$The wheeled walker KP1-8437 is designed to provide safe and reliable support to users requiring mobility assistance in a variety of environments, both indoors and outdoors. Made of resistant steel, this rollator combines durability with comfort, thanks to its wider 35 cm seat with bar-style backrest and its storage bag under the seat.

The Konfort Plus steel rollator (grey) is a four-wheeled walker with a seat, featuring an under-seat bag, adjustable handle height, bar-type backrest and dual-function brake operated from the handles. It is ideal to support mobility of users who need walking assistance, especially indoors, with a capacity of 100 kg.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP1-8437"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"100 kg"},{"clave":"Estructura","grupo":"Material","valor":"Acero; tubo de 25 mm x 1,2 mm"},{"clave":"Ruedas","grupo":"Ruedas","valor":"4, de PU con rin estrella (7 3/4\")"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Cuatro ruedas con asiento, bolsa bajo el asiento y espaldar tipo barra.","Frenos de doble función accionados desde las empuñaduras.","Altura de las empuñaduras graduable; ideal para interiores."],"beneficios_en":["Four wheels with seat, under-seat bag and bar-type backrest.","Dual-function brakes operated from the handles.","Adjustable handle height; ideal for indoors."],"valor_es":"Un rollator de acero con asiento, bolsa y frenos de doble función.","valor_en":"A steel rollator with seat, bag and dual-function brakes.","preguntas_frecuentes_es":[{"q":"¿Qué capacidad tiene?","a":"100 kg."},{"q":"¿Tiene asiento?","a":"Sí, con bolsa bajo el asiento y espaldar tipo barra."},{"q":"¿Cómo frena?","a":"Con freno de doble función accionado desde las empuñaduras."},{"q":"¿Dónde descargo la ficha técnica de Rollator En Acero KP1-8437?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What capacity does it have?","a":"100 kg."},{"q":"Does it have a seat?","a":"Yes, with an under-seat bag and bar-type backrest."},{"q":"How does it brake?","a":"With a dual-function brake operated from the handles."},{"q":"Where can I download the Steel Rollator KP1-8437 datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["rollator de acero gris","caminador con asiento y ruedas","rollator plegable","rollator Konfort Plus","rollator Colombia","ficha técnica KP1-8437"],"seo_keywords_en":["steel rollator grey","walker with seat and wheels","folding rollator","Konfort Plus rollator","rollator Colombia","KP1-8437 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MC4D2ZPVW6DNAH5EXPREABHJ4YIU?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'rollator-en-acero-ref-kp1-8437';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kp1-8437-1-ft.pdf',
  descripcion_larga_es = $d$El caminador con ruedas KP1-8437 está diseñado para brindar un apoyo seguro y confiable a los usuarios que requieren asistencia en la movilidad, tanto en interiores como exteriores. Fabricado en acero resistente, este rollator combina durabilidad con comodidad, gracias a su asiento con respaldo tipo barra y su bolsa de almacenamiento bajo el asiento.

El rollator en acero Konfort Plus (azul) es un caminador con cuatro ruedas y asiento que cuenta con bolsa bajo el asiento, altura graduable de las empuñaduras, espaldar tipo barra y freno de doble función accionado desde las empuñaduras. Es ideal para apoyar la movilidad de usuarios que requieren asistencia en la marcha, especialmente en interiores, con capacidad de 100 kg.$d$,
  descripcion_larga_en = $d$The wheeled walker KP1-8437 is designed to provide safe and reliable support to users requiring mobility assistance, both indoors and outdoors. Made of resistant steel, this rollator combines durability with comfort, thanks to its seat with bar-style backrest and its storage bag under the seat.

The Konfort Plus steel rollator (blue) is a four-wheeled walker with a seat, featuring an under-seat bag, adjustable handle height, bar-type backrest and dual-function brake operated from the handles. It is ideal to support mobility of users who need walking assistance, especially indoors, with a capacity of 100 kg.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP1-8437-1"},{"clave":"Color","grupo":"Variante","valor":"Azul"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"100 kg"},{"clave":"Estructura","grupo":"Material","valor":"Acero; tubo de 25 mm x 1,2 mm"},{"clave":"Ruedas","grupo":"Ruedas","valor":"4, de PU con rin estrella (7 3/4\")"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Cuatro ruedas con asiento, bolsa bajo el asiento y espaldar tipo barra.","Frenos de doble función accionados desde las empuñaduras.","Altura de las empuñaduras graduable; ideal para interiores."],"beneficios_en":["Four wheels with seat, under-seat bag and bar-type backrest.","Dual-function brakes operated from the handles.","Adjustable handle height; ideal for indoors."],"valor_es":"Un rollator de acero con asiento, bolsa y frenos de doble función.","valor_en":"A steel rollator with seat, bag and dual-function brakes.","preguntas_frecuentes_es":[{"q":"¿Qué capacidad tiene?","a":"100 kg."},{"q":"¿Tiene asiento?","a":"Sí, con bolsa bajo el asiento y espaldar tipo barra."},{"q":"¿Cómo frena?","a":"Con freno de doble función accionado desde las empuñaduras."},{"q":"¿Dónde descargo la ficha técnica de Rollator En Acero KP1-8437-1?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What capacity does it have?","a":"100 kg."},{"q":"Does it have a seat?","a":"Yes, with an under-seat bag and bar-type backrest."},{"q":"How does it brake?","a":"With a dual-function brake operated from the handles."},{"q":"Where can I download the Steel Rollator KP1-8437-1 datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["rollator de acero azul","caminador con asiento y ruedas","rollator plegable","rollator Konfort Plus","rollator Colombia","ficha técnica KP1-8437-1"],"seo_keywords_en":["steel rollator blue","walker with seat and wheels","folding rollator","Konfort Plus rollator","rollator Colombia","KP1-8437-1 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCODBQW3P6GRDADFEI7W3P7QDU5Q?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'rollator-en-acero-ref-kp1-8437-1';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kp1-8440-ft.pdf',
  descripcion_larga_es = $d$El caminador con ruedas KP1-8440 está diseñado para brindar un apoyo seguro y confiable a los usuarios que requieren asistencia en la movilidad. Fabricado en acero resistente, este rollator combina durabilidad con comodidad, gracias a su asiento con respaldo tipo barra, reposapiés integrados que permiten colocar los pies de manera segura mientras el usuario es llevado por un cuidador de manera transitoria, y una bolsa de almacenamiento bajo el asiento.

El rollator en acero Konfort Plus KP1-8440 (gris con reposapiés) tiene cuatro ruedas de PU con rin estrella, asiento de PVC acolchado, 5 puntos de graduación de altura de la empuñadura y capacidad de 100 kg. Está diseñado para apoyar la marcha con descanso incorporado.$d$,
  descripcion_larga_en = $d$The wheeled walker KP1-8440 is designed to provide safe and reliable support to users requiring mobility assistance. Made of resistant steel, this rollator combines durability with comfort, thanks to its seat with bar-style backrest, integrated footrests that allow secure foot placement while the user is carried by a caregiver, and a storage bag under the seat.

The Konfort Plus KP1-8440 steel rollator (grey with footrests) has four star-rim PU wheels, a padded PVC seat, 5 handle height adjustment points and a 100 kg capacity. It is designed to support walking with built-in rest.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP1-8440"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"100 kg"},{"clave":"Asiento","grupo":"Material","valor":"PVC acolchado"},{"clave":"Altura de empuñadura","grupo":"Ajustes","valor":"5 puntos"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Asiento de PVC acolchado para descansar durante el recorrido.","5 puntos de graduación de altura de la empuñadura.","Capacidad de 100 kg sobre estructura de acero."],"beneficios_en":["Padded PVC seat to rest during the walk.","5 handle height adjustment points.","100 kg capacity on a steel frame."],"valor_es":"Un rollator de acero con asiento acolchado y 5 alturas.","valor_en":"A steel rollator with padded seat and 5 heights.","preguntas_frecuentes_es":[{"q":"¿Cuántas alturas permite?","a":"5 puntos de graduación en la empuñadura."},{"q":"¿Qué capacidad tiene?","a":"100 kg."},{"q":"¿De qué es el asiento?","a":"De PVC acolchado."},{"q":"¿Dónde descargo la ficha técnica de Rollator En Acero Con Reposapiés KP1-8440?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"How many heights does it allow?","a":"5 adjustment points on the handle."},{"q":"What capacity does it have?","a":"100 kg."},{"q":"What is the seat made of?","a":"Padded PVC."},{"q":"Where can I download the Steel Rollator with Footrest KP1-8440 datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["rollator KP1-8440","rollator de acero con asiento","caminador con ruedas y asiento acolchado","rollator Konfort Plus","rollator Colombia","ficha técnica KP1-8440"],"seo_keywords_en":["KP1-8440 rollator","steel rollator with seat","walker with wheels and padded seat","Konfort Plus rollator","rollator Colombia","KP1-8440 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCV4F7DCHAKNEKHP77OKCDEJQRO4?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'rollator-en-acero-con-reposapies-ref-kp1-8440';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kp1-8440-i-ft.pdf',
  descripcion_larga_es = $d$El caminador con ruedas  KP1-8440-I está diseñado para brindar un apoyo robusto y confiable a los usuarios que requieren asistencia en la movilidad, especialmente en exteriores. Fabricado en acero resistente, este rollator combina durabilidad con comodidad gracias a su asiento con respaldo tipo barra y su canasta de almacenamiento bajo el asiento.

El rollator en acero Konfort Plus KP1-8440 (gris) tiene cuatro ruedas de PU con rin estrella, asiento de PVC acolchado, 5 puntos de graduación de altura de la empuñadura y capacidad de 100 kg. Está diseñado para apoyar la marcha con descanso incorporado.$d$,
  descripcion_larga_en = $d$The wheeled walker KP1-8440-I is designed to provide robust and reliable support to users requiring mobility assistance, especially outdoors. Made of resistant steel, this rollator combines durability with comfort thanks to its seat with bar-style backrest and its storage basket under the seat.

The Konfort Plus KP1-8440 steel rollator (grey) has four star-rim PU wheels, a padded PVC seat, 5 handle height adjustment points and a 100 kg capacity. It is designed to support walking with built-in rest.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP1-8440-I"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"100 kg"},{"clave":"Asiento","grupo":"Material","valor":"PVC acolchado"},{"clave":"Altura de empuñadura","grupo":"Ajustes","valor":"5 puntos"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Asiento de PVC acolchado para descansar durante el recorrido.","5 puntos de graduación de altura de la empuñadura.","Capacidad de 100 kg sobre estructura de acero."],"beneficios_en":["Padded PVC seat to rest during the walk.","5 handle height adjustment points.","100 kg capacity on a steel frame."],"valor_es":"Un rollator de acero con asiento acolchado y 5 alturas.","valor_en":"A steel rollator with padded seat and 5 heights.","preguntas_frecuentes_es":[{"q":"¿Cuántas alturas permite?","a":"5 puntos de graduación en la empuñadura."},{"q":"¿Qué capacidad tiene?","a":"100 kg."},{"q":"¿De qué es el asiento?","a":"De PVC acolchado."},{"q":"¿Dónde descargo la ficha técnica de Rollator En Acero KP1-8440-I?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"How many heights does it allow?","a":"5 adjustment points on the handle."},{"q":"What capacity does it have?","a":"100 kg."},{"q":"What is the seat made of?","a":"Padded PVC."},{"q":"Where can I download the Steel Rollator KP1-8440-I datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["rollator KP1-8440","rollator de acero con asiento","caminador con ruedas y asiento acolchado","rollator Konfort Plus","rollator Colombia","ficha técnica KP1-8440-I"],"seo_keywords_en":["KP1-8440 rollator","steel rollator with seat","walker with wheels and padded seat","Konfort Plus rollator","rollator Colombia","KP1-8440-I datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MC3I55FFL2XNDFPJ4DYCL2TJSWSU?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'rollator-en-acero-ref-kp1-8440-i';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp271-al-2-ft.pdf',
  descripcion_larga_es = $d$El caminador con ruedas y asiento ajustable Konfort Plus está diseñado para brindar un apoyo seguro y cómodo a usuarios que requieren asistencia al caminar o que padecen problemas de equilibrio. Su estructura ligera de aluminio con alma de hierro asegura durabilidad, mientras que las ruedas macizas de 6” ofrecen un desplazamiento suave y seguro en diversas superficies.

El rollator en aluminio Konfort Plus es un caminador plegable ligero (7,42 kg) de cuatro ruedas con asiento acolchado, respaldo y frenos manuales. Incorpora empuñaduras ergonómicas de altura ajustable en 5 niveles y bolsa portaobjetos, soporta 135 kg y está pensado para usuarios con movilidad reducida que necesitan estabilidad y descanso al desplazarse.$d$,
  descripcion_larga_en = $d$The Konfort Plus walker with wheels and adjustable seat is designed to provide safe and comfortable support to users who require walking assistance or suffer from balance problems. Its lightweight aluminum structure with iron core ensures durability, while the 6" solid wheels offer smooth and safe movement on various surfaces.

The Konfort Plus aluminium rollator is a light (7.42 kg) foldable four-wheeled walker with a padded seat, backrest and manual brakes. It has ergonomic handles adjustable in 5 levels and a storage bag, supports 135 kg and is designed for users with reduced mobility who need stability and rest when moving.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP271-AL-2"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"135 kg"},{"clave":"Peso neto","grupo":"Peso","valor":"7,42 kg"},{"clave":"Ancho total / altura","grupo":"Dimensiones","valor":"60 cm / 79 - 91 cm"},{"clave":"Estructura","grupo":"Material","valor":"Aluminio"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Aluminio ligero de 7,42 kg, plegable.","Asiento acolchado, respaldo, frenos manuales y bolsa portaobjetos.","Capacidad de 135 kg y empuñaduras con 5 niveles de altura."],"beneficios_en":["Light 7.42 kg aluminium, foldable.","Padded seat, backrest, manual brakes and storage bag.","135 kg capacity and handles with 5 height levels."],"valor_es":"Un rollator de aluminio ligero con capacidad de 135 kg.","valor_en":"A light aluminium rollator with 135 kg capacity.","preguntas_frecuentes_es":[{"q":"¿Cuánto pesa?","a":"7,42 kg."},{"q":"¿Qué capacidad tiene?","a":"135 kg."},{"q":"¿Cuántos niveles de altura tienen las asas?","a":"5 niveles."},{"q":"¿Dónde descargo la ficha técnica de Rollator En Aluminio Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"How much does it weigh?","a":"7.42 kg."},{"q":"What capacity does it have?","a":"135 kg."},{"q":"How many height levels do the handles have?","a":"5 levels."},{"q":"Where can I download the Konfort Plus Aluminum Rollator datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["rollator de aluminio","rollator plegable con asiento","caminador con ruedas y frenos","rollator Konfort Plus","rollator Colombia","ficha técnica KP271-AL-2"],"seo_keywords_en":["aluminium rollator","folding rollator with seat","walker with wheels and brakes","Konfort Plus rollator","rollator Colombia","KP271-AL-2 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCMG2NRCBZGNBLRBZJ4MFT7YWNPE?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'rollator-en-aluminio-ref-kp271-al-2-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/hy5-ft.pdf',
  descripcion_larga_es = $d$El caminador HY5 es una solución versátil y robusta diseñada para personas que requieren asistencia en su movilidad y actividades diarias. Equipado con múltiples funciones, este dispositivo no solo facilita el caminar, sino que también puede usarse como una silla de ruedas temporal, brindando un apoyo integral a los usuarios. Su diseño ergonómico y capacidad de peso de hasta 120 kg aseguran comodidad y soporte durante el uso prolongado.

El HY5 de Konfort Plus es un caminador con cinco funciones en un solo producto: rollator, silla para ducha, eleva sanitario / barra de seguridad, cómodo sanitario y silla de transporte. Ayuda a las personas con limitaciones de movilidad a permanecer independientes y seguras en casa. Es de aluminio, pesa 7,5 kg, soporta 120 kg y mide 109 cm de alto, 59 cm de ancho y 63 cm de largo.$d$,
  descripcion_larga_en = $d$The HY5 walker is a versatile and robust solution designed for people who require assistance in their mobility and daily activities. Equipped with multiple functions, this device not only facilitates walking, but can also be used as a temporary wheelchair, providing comprehensive support to users. Its ergonomic design and weight capacity of up to 120 kg ensure comfort and support during prolonged use.

The Konfort Plus HY5 is a five-function walker in a single product: rollator, shower chair, toilet riser / safety bar, commode and transport chair. It helps people with mobility limitations stay independent and safe at home. It is aluminium, weighs 7.5 kg, supports 120 kg and measures 109 cm high, 59 cm wide and 63 cm long.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"HY5"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"120 kg"},{"clave":"Peso neto","grupo":"Peso","valor":"7,5 kg"},{"clave":"Alto / ancho / largo","grupo":"Dimensiones","valor":"109 / 59 / 63 cm"},{"clave":"Estructura","grupo":"Material","valor":"Aluminio"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Cinco funciones en uno: rollator, silla de ducha, eleva sanitario/barra, cómodo y silla de transporte.","Aluminio de 7,5 kg con capacidad de 120 kg.","Pensado para mantener la independencia y la seguridad en casa."],"beneficios_en":["Five functions in one: rollator, shower chair, toilet riser/bar, commode and transport chair.","7.5 kg aluminium with 120 kg capacity.","Designed to keep independence and safety at home."],"valor_es":"Un caminador de cinco funciones para independencia en casa.","valor_en":"A five-function walker for independence at home.","preguntas_frecuentes_es":[{"q":"¿Qué funciones tiene?","a":"Rollator, silla para ducha, eleva sanitario / barra de seguridad, cómodo sanitario y silla de transporte."},{"q":"¿Qué capacidad tiene?","a":"120 kg."},{"q":"¿Cuánto pesa?","a":"7,5 kg."},{"q":"¿Dónde descargo la ficha técnica de Caminador 5 Funciones HY5?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which functions does it have?","a":"Rollator, shower chair, toilet riser / safety bar, commode and transport chair."},{"q":"What capacity does it have?","a":"120 kg."},{"q":"How much does it weigh?","a":"7.5 kg."},{"q":"Where can I download the HY5 5-Function Walker datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["caminador 5 funciones HY5","caminador todo en uno","rollator silla de ducha y cómodo","ayuda técnica multifunción","ayudas técnicas Colombia","ficha técnica HY5"],"seo_keywords_en":["5-function walker HY5","all-in-one walker","rollator shower chair and commode","multifunction mobility aid","mobility aids Colombia","HY5 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCWPLNXB6URZBWNKKZC6NDLQ3U7U?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'caminador-5-funciones-ref-hy5';
