-- First landing batch: content based on manufacturer product documentation.
-- Sources are retained in atributos.fuentes_auditoria for editorial traceability.
-- No prices, commercial logic, or schema are changed.

UPDATE public.productos
SET
  nombre_es = 'Adaptador de cable calefactor 900MR805 Fisher & Paykel',
  nombre_en = 'Fisher & Paykel 900MR805 Heater-Wire Adapter',
  descripcion_corta_es = 'Adaptador de cable calefactor para circuitos respiratorios RT de doble calefacción Fisher & Paykel.',
  descripcion_corta_en = 'Heater-wire adapter for Fisher & Paykel RT-series dual-heated breathing circuits.',
  descripcion_larga_es = 'El 900MR805 es un adaptador de cable calefactor Fisher & Paykel para circuitos respiratorios RT de doble calefacción. Es un accesorio de una unidad destinado a la configuración compatible del circuito; la compatibilidad final del circuito, humidificador y configuración clínica debe confirmarse con la documentación vigente del fabricante y en la cotización.',
  descripcion_larga_en = 'The 900MR805 is a Fisher & Paykel heater-wire adapter for RT-series dual-heated breathing circuits. It is a one-unit accessory for the compatible circuit configuration; final circuit, humidifier and clinical-setup compatibility must be confirmed against current manufacturer documentation and in the quotation.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"900MR805"},{"clave":"Tipo","grupo":"Configuración","valor":"Adaptador de cable calefactor"},{"clave":"Compatibilidad descrita","grupo":"Configuración","valor":"Circuitos respiratorios Fisher & Paykel serie RT de doble calefacción"},{"clave":"Contenido","grupo":"Presentación","valor":"1 unidad"}]'::jsonb,
  aplicaciones_es = ARRAY['Configuración de circuitos respiratorios RT de doble calefacción Fisher & Paykel'],
  aplicaciones_en = ARRAY['Configuration of Fisher & Paykel RT-series dual-heated breathing circuits'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"Fisher & Paykel","fabricante":"Fisher & Paykel","ref_proveedor":"900MR805","valor_es":"Adaptador de cable calefactor para completar una configuración compatible de circuito RT de doble calefacción.","valor_en":"Heater-wire adapter for a compatible RT-series dual-heated circuit configuration.","beneficios_es":["Identifica un accesorio específico para circuitos RT de doble calefacción.","La presentación de una unidad permite solicitar la referencia exacta dentro de la configuración del circuito."],"beneficios_en":["Identifies a specific accessory for RT-series dual-heated circuits.","The one-unit presentation supports ordering the exact reference within the circuit configuration."],"preguntas_frecuentes_es":[{"q":"¿Para qué circuito se describe el 900MR805?","a":"La documentación de Fisher & Paykel lo identifica como adaptador de cable calefactor para circuitos respiratorios RT de doble calefacción."},{"q":"¿Cuántas unidades contiene?","a":"La referencia se presenta como 1 unidad."},{"q":"¿Se debe confirmar compatibilidad?","a":"Sí. La compatibilidad con circuito, humidificador y configuración clínica se confirma con documentación vigente del fabricante y en la cotización."}],"preguntas_frecuentes_en":[{"q":"Which circuit is the 900MR805 described for?","a":"Fisher & Paykel documentation identifies it as a heater-wire adapter for RT-series dual-heated breathing circuits."},{"q":"How many units are included?","a":"This reference is supplied as one unit."},{"q":"Should compatibility be confirmed?","a":"Yes. Compatibility with the circuit, humidifier and clinical setup must be confirmed against current manufacturer documentation and in the quotation."}],"seo_keywords_es":["adaptador cable calefactor 900MR805","circuito RT doble calefacción Fisher Paykel","accesorio humidificación respiratoria Colombia"],"seo_keywords_en":["900MR805 heater-wire adapter","Fisher Paykel RT dual heated circuit","respiratory humidification accessory Colombia"],"fuentes_auditoria":["https://www.fphcare.com/us/products/devices-and-humidifiers/850-system/infant/circuits-and-accessories/"]}'::jsonb
WHERE slug = 'cable-calefactor-para-circuito-de-doble-hilo-caliente-ref-900mr805-fisher-paykel';

UPDATE public.productos
SET
  nombre_es = 'Interfaz para traqueostomía Optiflow+ OPT970 Fisher & Paykel',
  nombre_en = 'Fisher & Paykel Optiflow+ Tracheostomy Interface OPT970',
  descripcion_corta_es = 'Interfaz de traqueostomía Optiflow+ para terapia de alto flujo humidificado.',
  descripcion_corta_en = 'Optiflow+ tracheostomy interface for humidified high-flow therapy.',
  descripcion_larga_es = 'La OPT970 es una interfaz de traqueostomía Optiflow+ Fisher & Paykel para terapia de alto flujo humidificado. Se conecta al circuito AirSpiral e incorpora tecnología Evaqua, diseñada para reducir la condensación, además de un protector de secreciones rediseñado. La presentación indicada es de 20 unidades. La selección de interfaz y compatibilidad con la configuración de terapia deben validarse con la documentación vigente del fabricante y el protocolo institucional.',
  descripcion_larga_en = 'The OPT970 is a Fisher & Paykel Optiflow+ tracheostomy interface for humidified high-flow therapy. It connects to the AirSpiral circuit and includes Evaqua technology, designed to reduce condensation, plus a redesigned sputum guard. The stated pack contains 20 units. Interface selection and compatibility with the therapy configuration must be validated against current manufacturer documentation and the institution''s protocol.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"OPT970"},{"clave":"Tipo","grupo":"Interfaz","valor":"Interfaz de traqueostomía Optiflow+ para terapia de alto flujo humidificado"},{"clave":"Conexión","grupo":"Configuración","valor":"Circuito AirSpiral"},{"clave":"Tecnología","grupo":"Manejo de condensación","valor":"Evaqua, diseñada para reducir la condensación"},{"clave":"Protección","grupo":"Diseño","valor":"Protector de secreciones rediseñado"},{"clave":"Presentación","grupo":"Empaque","valor":"20 unidades"}]'::jsonb,
  aplicaciones_es = ARRAY['Terapia de alto flujo humidificado mediante interfaz de traqueostomía'],
  aplicaciones_en = ARRAY['Humidified high-flow therapy through a tracheostomy interface'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"Fisher & Paykel","fabricante":"Fisher & Paykel","ref_proveedor":"OPT970","valor_es":"Interfaz Optiflow+ de traqueostomía para conectar terapia de alto flujo humidificado al circuito AirSpiral.","valor_en":"Optiflow+ tracheostomy interface that connects humidified high-flow therapy to the AirSpiral circuit.","beneficios_es":["La conexión al circuito AirSpiral define la configuración de uso descrita por el fabricante.","La tecnología Evaqua está diseñada para reducir la condensación.","El protector de secreciones rediseñado es una característica de esta interfaz."],"beneficios_en":["Connection to the AirSpiral circuit defines the manufacturer-described use configuration.","Evaqua technology is designed to reduce condensation.","The redesigned sputum guard is a feature of this interface."],"preguntas_frecuentes_es":[{"q":"¿Qué es la OPT970?","a":"Es una interfaz de traqueostomía Optiflow+ Fisher & Paykel para terapia de alto flujo humidificado."},{"q":"¿Con qué circuito se conecta?","a":"La página del fabricante indica conexión con el circuito AirSpiral."},{"q":"¿Cuál es su presentación?","a":"La referencia OPT970 se indica en empaque de 20 unidades."}],"preguntas_frecuentes_en":[{"q":"What is the OPT970?","a":"It is a Fisher & Paykel Optiflow+ tracheostomy interface for humidified high-flow therapy."},{"q":"Which circuit does it connect to?","a":"The manufacturer page states connection to the AirSpiral circuit."},{"q":"What is its pack size?","a":"The OPT970 reference is stated as a 20-unit pack."}],"seo_keywords_es":["interfaz traqueostomía OPT970","Optiflow Plus traqueostomía","terapia alto flujo humidificado Colombia"],"seo_keywords_en":["OPT970 tracheostomy interface","Optiflow Plus tracheostomy","humidified high-flow therapy Colombia"],"fuentes_auditoria":["https://www.fphcare.com/us/hospital/adult-respiratory/optiflow/optiflow-tracheostomy-interface/"]}'::jsonb
WHERE slug = 'canula-para-traqueostomia-adulto-ref-opt970-fisher-paykel';

UPDATE public.productos
SET
  nombre_es = 'Cámara de humidificación de llenado automático MR290 Fisher & Paykel',
  nombre_en = 'Fisher & Paykel MR290 Auto-Fill Humidifier Chamber',
  descripcion_corta_es = 'Cámara de humidificación de llenado automático MR290, apta para pacientes y humidificadores MR Fisher & Paykel.',
  descripcion_corta_en = 'MR290 auto-fill humidifier chamber, suitable for all patients and Fisher & Paykel MR humidifiers.',
  descripcion_larga_es = 'La MR290 es una cámara de humidificación Fisher & Paykel de llenado automático, descrita como apta para todos los pacientes y para humidificadores MR Fisher & Paykel. Incorpora llenado automático, doble flotador contra sobrellenado y volumen compresible consistente. La familia incluye presentaciones MR290V de 40 por caja, MR290VX de 10 por caja y MR290HFV para ventilación de alta frecuencia de 40 por caja. La referencia y configuración compatibles deben confirmarse en la cotización.',
  descripcion_larga_en = 'The MR290 is a Fisher & Paykel auto-fill humidifier chamber described as suitable for all patients and Fisher & Paykel MR humidifiers. It includes automatic refill, dual-float anti-overfill protection and consistent compressible volume. The family includes MR290V in boxes of 40, MR290VX in boxes of 10 and MR290HFV for high-frequency ventilation in boxes of 40. The compatible reference and configuration must be confirmed in the quotation.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"MR290"},{"clave":"Tipo","grupo":"Humidificación","valor":"Cámara de humidificación de llenado automático"},{"clave":"Compatibilidad descrita","grupo":"Configuración","valor":"Todos los pacientes y humidificadores MR Fisher & Paykel"},{"clave":"Control de llenado","grupo":"Seguridad funcional","valor":"Llenado automático y doble flotador contra sobrellenado"},{"clave":"Volumen","grupo":"Diseño","valor":"Volumen compresible consistente"},{"clave":"Presentaciones relacionadas","grupo":"Empaque","valor":"MR290V: 40/caja; MR290VX: 10/caja; MR290HFV para ventilación de alta frecuencia: 40/caja"}]'::jsonb,
  aplicaciones_es = ARRAY['Humidificación de gases con humidificadores MR Fisher & Paykel', 'Configuraciones de ventilación de alta frecuencia con referencia MR290HFV cuando corresponda'],
  aplicaciones_en = ARRAY['Gas humidification with Fisher & Paykel MR humidifiers', 'High-frequency ventilation configurations with MR290HFV where applicable'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"Fisher & Paykel","fabricante":"Fisher & Paykel","ref_proveedor":"MR290","valor_es":"Cámara de llenado automático para humidificadores MR Fisher & Paykel, con doble flotador contra sobrellenado.","valor_en":"Auto-fill chamber for Fisher & Paykel MR humidifiers with dual-float anti-overfill protection.","beneficios_es":["El llenado automático y el doble flotador están diseñados para manejar el nivel de agua de la cámara.","El volumen compresible consistente es una característica publicada para la cámara.","Las presentaciones MR290V, MR290VX y MR290HFV permiten seleccionar la referencia según la configuración requerida."],"beneficios_en":["Automatic refill and the dual float are designed to manage the chamber water level.","Consistent compressible volume is a published chamber characteristic.","MR290V, MR290VX and MR290HFV packs allow reference selection for the required configuration."],"preguntas_frecuentes_es":[{"q":"¿Con qué humidificadores se describe compatible la MR290?","a":"Fisher & Paykel la describe como apta para humidificadores MR Fisher & Paykel."},{"q":"¿Qué sistema de llenado tiene?","a":"La cámara tiene llenado automático y doble flotador contra sobrellenado."},{"q":"¿Qué variantes de empaque se publican?","a":"MR290V: 40 por caja; MR290VX: 10 por caja; y MR290HFV para ventilación de alta frecuencia: 40 por caja."}],"preguntas_frecuentes_en":[{"q":"Which humidifiers is the MR290 described as compatible with?","a":"Fisher & Paykel describes it as suitable for Fisher & Paykel MR humidifiers."},{"q":"Which filling system does it have?","a":"The chamber has automatic refill and dual-float anti-overfill protection."},{"q":"Which pack variants are published?","a":"MR290V: 40 per box; MR290VX: 10 per box; and MR290HFV for high-frequency ventilation: 40 per box."}],"seo_keywords_es":["cámara humidificadora MR290","cascada llenado automático Fisher Paykel","cámara humidificador MR Colombia"],"seo_keywords_en":["MR290 humidifier chamber","Fisher Paykel auto-fill chamber","MR humidifier chamber Colombia"],"fuentes_auditoria":["https://www.fphcare.com/en-ca/products/mr290-auto-chamber/?cf=0"]}'::jsonb
WHERE slug = 'cascada-desechable-para-humidificador-ref-mr290-fisher-paykel';

UPDATE public.productos
SET
  nombre_es = 'Mamógrafo digital DM156 Series Angell Technology',
  nombre_en = 'Angell Technology DM156 Series Digital Mammography System',
  descripcion_corta_es = 'Sistema de mamografía digital Angell DM156 con detector plano a-Si/CsI e integración DICOM 3.0/PACS.',
  descripcion_corta_en = 'Angell DM156 digital mammography system with a-Si/CsI flat-panel detector and DICOM 3.0/PACS integration.',
  descripcion_larga_es = 'El DM156 Series de Angell Technology es un sistema de mamografía digital. La documentación técnica consultada describe detector plano a-Si/CsI, generador de alta frecuencia de 5 kW, tubo de molibdeno con focos focales de 0,1 y 0,3 mm, y estación DXRay para gestión de paciente, adquisición y procesamiento. Incluye compresión manual de 0 a 196 N con liberación automática; placas de 240 × 310 mm y 100 × 100 mm, con placa de 200 × 280 mm opcional. El brazo C tiene recorrido de -135° a 180°, SID de 650 mm y FID de 1420 a 2020 mm. La documentación también especifica DICOM 3.0 y PACS. Configuración, software, placas y conectividad final se confirman en la cotización.',
  descripcion_larga_en = 'The Angell Technology DM156 Series is a digital mammography system. The reviewed technical documentation describes an a-Si/CsI flat-panel detector, a 5 kW high-frequency generator, a molybdenum tube with 0.1 and 0.3 mm focal spots, and the DXRay workstation for patient management, acquisition and processing. It includes manual compression from 0 to 196 N with automatic release; 240 × 310 mm and 100 × 100 mm plates, with a 200 × 280 mm plate available as an option. The C-arm travels from -135° to 180°, with a 650 mm SID and 1420 to 2020 mm FID. Documentation also specifies DICOM 3.0 and PACS. Final configuration, software, plates and connectivity are confirmed in the quotation.',
  especificaciones = '[{"clave":"Detector","grupo":"Tecnología de imagen","valor":"Panel plano a-Si/CsI"},{"clave":"Generador","grupo":"Generación de rayos X","valor":"Alta frecuencia, 5 kW; 20–40 kV; 10–200 mA; 10–500 mAs; 220 V, 50/60 Hz"},{"clave":"Tubo y focos","grupo":"Generación de rayos X","valor":"Tubo de molibdeno; focos focales de 0,1 mm y 0,3 mm"},{"clave":"Compresión","grupo":"Posicionamiento","valor":"Manual 0–196 N con liberación automática"},{"clave":"Placas de compresión","grupo":"Posicionamiento","valor":"240 × 310 mm y 100 × 100 mm; 200 × 280 mm opcional"},{"clave":"Brazo C","grupo":"Geometría","valor":"Recorrido de -135° a 180°"},{"clave":"Distancias","grupo":"Geometría","valor":"SID 650 mm; FID 1420–2020 mm"},{"clave":"Estación de trabajo","grupo":"Software e integración","valor":"DXRay para paciente, adquisición y procesamiento; DICOM 3.0 y PACS"}]'::jsonb,
  aplicaciones_es = ARRAY['Mamografía digital en servicios de radiología'],
  aplicaciones_en = ARRAY['Digital mammography in radiology services'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"Angell Technology","fabricante":"Angell Technology","modelo":"DM156 Series","valor_es":"Mamografía digital con detector plano a-Si/CsI, geometría de brazo C e integración DICOM 3.0/PACS.","valor_en":"Digital mammography with an a-Si/CsI flat-panel detector, C-arm geometry and DICOM 3.0/PACS integration.","beneficios_es":["La estación DXRay reúne gestión de paciente, adquisición y procesamiento.","DICOM 3.0 y PACS permiten planear la integración con el flujo de imagen institucional.","Las placas de compresión y la opción de placa adicional permiten configurar el sistema según la necesidad de la institución."],"beneficios_en":["The DXRay workstation brings together patient management, acquisition and processing.","DICOM 3.0 and PACS support planning integration with the institution''s imaging workflow.","Compression plates and the additional optional plate allow configuration for the institution''s needs."],"preguntas_frecuentes_es":[{"q":"¿Qué detector usa el DM156?","a":"La documentación técnica consultada especifica un detector plano a-Si/CsI."},{"q":"¿Qué integración de imagen se indica?","a":"La estación DXRay se describe con DICOM 3.0 y PACS."},{"q":"¿Qué placas de compresión se indican?","a":"Se especifican placas de 240 × 310 mm y 100 × 100 mm; la de 200 × 280 mm es opcional."},{"q":"¿La configuración final está incluida?","a":"La configuración final de software, placas y conectividad se confirma en la cotización."}],"preguntas_frecuentes_en":[{"q":"Which detector does the DM156 use?","a":"The reviewed technical documentation specifies an a-Si/CsI flat-panel detector."},{"q":"Which imaging integration is indicated?","a":"The DXRay workstation is described with DICOM 3.0 and PACS."},{"q":"Which compression plates are specified?","a":"240 × 310 mm and 100 × 100 mm plates are specified; the 200 × 280 mm plate is optional."},{"q":"Is the final configuration included?","a":"The final software, plate and connectivity configuration is confirmed in the quotation."}],"seo_keywords_es":["mamógrafo digital DM156","mamografía digital Angell","sistema mamografía DICOM PACS Colombia"],"seo_keywords_en":["DM156 digital mammography","Angell digital mammography","DICOM PACS mammography system Colombia"],"fuentes_auditoria":["https://qx-files.yaozh.com/qxexport/gd/%E7%B2%A4%E9%A3%9F%E8%8D%AF%E7%9B%91%E6%A2%B0%E5%87%BA20230608%E5%8F%B7.pdf","https://www.scribd.com/document/723773094/DM156-MAMMOGRAPHY-SERIES-SPECS","https://www.scribd.com/document/835081652/DM156-USER-MANUAL"]}'::jsonb
WHERE slug = 'mamografo-digital-dm156-series-angell-technology';
