-- Correos transaccionales por estado. Cada estado tiene un objetivo y CTA;
-- las variables se resuelven en notificar-cliente.

WITH plantillas(clave, descripcion, asunto, html) AS (
  VALUES
    ('pedido_estado_pendiente_es', 'Pedido creado, pago pendiente (ES)',
     'Completa el pago de tu pedido {{referencia}}',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p><strong>Pedido:</strong> {{referencia}}</p><p><strong>Total:</strong> {{total}} {{moneda}}</p><ul>{{items_html}}</ul>{{action_html}}<p>Equipo I-ME</p>'),
    ('pedido_estado_pendiente_en', 'Order created, payment pending (EN)',
     'Complete payment for order {{referencia}}',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p><strong>Order:</strong> {{referencia}}</p><p><strong>Total:</strong> {{total}} {{moneda}}</p><ul>{{items_html}}</ul>{{action_html}}<p>I-ME Team</p>'),
    ('pedido_estado_pendiente_validacion_es', 'Comprobante en validacion (ES)',
     'Estamos validando tu comprobante — {{referencia}}',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p><strong>Pedido:</strong> {{referencia}}</p><p><strong>Total:</strong> {{total}} {{moneda}}</p>{{action_html}}<p>Te avisaremos cuando finalice la revision.</p><p>Equipo I-ME</p>'),
    ('pedido_estado_pendiente_validacion_en', 'Receipt under review (EN)',
     'We are reviewing your receipt — {{referencia}}',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p><strong>Order:</strong> {{referencia}}</p><p><strong>Total:</strong> {{total}} {{moneda}}</p>{{action_html}}<p>We will notify you when the review is complete.</p><p>I-ME Team</p>'),
    ('pedido_estado_pagado_es', 'Pago confirmado (ES)',
     'Pago confirmado — pedido {{referencia}}',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p><strong>Pedido:</strong> {{referencia}}</p><p><strong>Total confirmado:</strong> {{total}} {{moneda}}</p><ul>{{items_html}}</ul>{{action_html}}<p>Equipo I-ME</p>'),
    ('pedido_estado_pagado_en', 'Payment confirmed (EN)',
     'Payment confirmed — order {{referencia}}',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p><strong>Order:</strong> {{referencia}}</p><p><strong>Confirmed total:</strong> {{total}} {{moneda}}</p><ul>{{items_html}}</ul>{{action_html}}<p>I-ME Team</p>'),
    ('pedido_estado_procesando_es', 'Pedido en preparacion (ES)',
     'Estamos preparando tu pedido {{referencia}}',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p>Te enviaremos la guia cuando sea despachado.</p>{{action_html}}<p>Equipo I-ME</p>'),
    ('pedido_estado_procesando_en', 'Order in preparation (EN)',
     'We are preparing order {{referencia}}',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p>We will send tracking details after dispatch.</p>{{action_html}}<p>I-ME Team</p>'),
    ('pedido_estado_preparando_es', 'Proveedor preparando pedido (ES)',
     'Tu pedido {{referencia}} esta en preparacion',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p>Te enviaremos la guia cuando sea despachado.</p>{{action_html}}<p>Equipo I-ME</p>'),
    ('pedido_estado_preparando_en', 'Supplier preparing order (EN)',
     'Order {{referencia}} is being prepared',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p>We will send tracking details after dispatch.</p>{{action_html}}<p>I-ME Team</p>'),
    ('pedido_estado_enviado_es', 'Pedido despachado con tracking (ES)',
     'Tu pedido {{referencia}} fue enviado',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p>{{tracking_html}}{{action_html}}<p>Equipo I-ME</p>'),
    ('pedido_estado_enviado_en', 'Order shipped with tracking (EN)',
     'Order {{referencia}} has shipped',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p>{{tracking_html}}{{action_html}}<p>I-ME Team</p>'),
    ('pedido_estado_entregado_es', 'Pedido entregado (ES)',
     'Pedido {{referencia}} entregado',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p>Si existe alguna novedad, responde a este correo.</p>{{action_html}}<p>Equipo I-ME</p>'),
    ('pedido_estado_entregado_en', 'Order delivered (EN)',
     'Order {{referencia}} delivered',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p>Reply to this email if there is any issue.</p>{{action_html}}<p>I-ME Team</p>'),
    ('pedido_estado_retrasado_es', 'Alerta de retraso (ES)',
     'Actualizacion importante sobre tu pedido {{referencia}}',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p>Te contactaremos con una nueva fecha estimada.</p>{{action_html}}<p>Equipo I-ME</p>'),
    ('pedido_estado_retrasado_en', 'Delay alert (EN)',
     'Important update about order {{referencia}}',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p>We will contact you with a revised estimate.</p>{{action_html}}<p>I-ME Team</p>'),
    ('pedido_estado_rechazado_es', 'Pedido rechazado (ES)',
     'No pudimos continuar con tu pedido {{referencia}}',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p>{{action_html}}<p>Equipo I-ME</p>'),
    ('pedido_estado_rechazado_en', 'Order rejected (EN)',
     'We could not continue with order {{referencia}}',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p>{{action_html}}<p>I-ME Team</p>'),
    ('pedido_estado_expirado_es', 'Pedido expirado (ES)',
     'El pedido {{referencia}} expiro',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p>{{action_html}}<p>Equipo I-ME</p>'),
    ('pedido_estado_expirado_en', 'Order expired (EN)',
     'Order {{referencia}} expired',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p>{{action_html}}<p>I-ME Team</p>'),
    ('pedido_estado_cancelado_es', 'Pedido cancelado (ES)',
     'Pedido {{referencia}} cancelado',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p>{{action_html}}<p>Equipo I-ME</p>'),
    ('pedido_estado_cancelado_en', 'Order cancelled (EN)',
     'Order {{referencia}} cancelled',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p>{{action_html}}<p>I-ME Team</p>'),
    ('pedido_estado_reembolsado_es', 'Reembolso procesado (ES)',
     'Reembolso procesado — pedido {{referencia}}',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p><strong>Importe:</strong> {{total}} {{moneda}}</p>{{action_html}}<p>Equipo I-ME</p>'),
    ('pedido_estado_reembolsado_en', 'Refund processed (EN)',
     'Refund processed — order {{referencia}}',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p><p><strong>Amount:</strong> {{total}} {{moneda}}</p>{{action_html}}<p>I-ME Team</p>'),
    ('pedido_estado_error_verificacion_es', 'Error verificando pago (ES)',
     'Necesitamos que revises el pago — {{referencia}}',
     '<h2>Hola {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p>{{action_html}}<p>También puedes responder a este correo para recibir ayuda.</p><p>Equipo I-ME</p>'),
    ('pedido_estado_error_verificacion_en', 'Payment verification error (EN)',
     'Please review payment for order {{referencia}}',
     '<h2>Hello {{cliente_nombre}}</h2><p>{{mensaje_estado}}</p>{{action_html}}<p>You can also reply to this email for help.</p><p>I-ME Team</p>')
)
INSERT INTO email_templates (clave, descripcion, asunto, html)
SELECT clave, descripcion, asunto, html FROM plantillas
ON CONFLICT (clave) DO UPDATE
SET descripcion = EXCLUDED.descripcion,
    asunto = EXCLUDED.asunto,
    html = EXCLUDED.html;
