-- Bioquímica semiautomática: landings enriquecidas desde CAT/new/1.
-- Fuentes: Rayto RT-1904C inserto; BIOBASE Claire&Silver brochure; BIOBASE Silver Plus features; SUNNYMED SY-B010 ficha comercial.
-- Specs/beneficios trazables a PDF. Cero testimonios inventados. Precio null (cotización).


INSERT INTO public.productos (
  id, slug, familia_id, tipo_id,
  nombre_es, nombre_en,
  descripcion_corta_es, descripcion_corta_en,
  descripcion_larga_es, descripcion_larga_en,
  imagen_principal, galeria, ficha_pdf,
  especificaciones, aplicaciones_es, aplicaciones_en,
  tipo_comercial, fulfillment_mode, precio, moneda, stock,
  disponible, destacado, nuevo, activo, orden, atributos
) VALUES (
  '74f21d04-d798-4fce-91e9-c40312f8b6f0'::uuid,
  'analizador-bioquimico-semiautomatico-rayto-rt-1904c',
  '4d9a59cd-2c1e-4755-9584-28d6e9024d3c'::uuid,
  NULL,
  'Analizador bioquímico semiautomático Rayto RT-1904C',
  'Rayto RT-1904C Semi-Automatic Biochemistry Analyzer',
  'Analizador bioquímico semiautomático Rayto RT-1904C con pantalla LCD 7", 160 protocolos, celda de flujo y modos cinético, fijo y punto final',
  'Rayto RT-1904C semi-automatic biochemistry analyzer with 7" LCD, 160 protocols, flow cell and kinetic, fixed-time and endpoint modes',
  'El Rayto RT-1904C es un analizador bioquímico semiautomático orientado a laboratorios clínicos que necesitan química clínica con operación sencilla sobre Windows, mouse y pantalla LCD a color de 7". Según el inserto del fabricante, trabaja con sistema de reactivo abierto (celda de flujo o cubeta a solicitud; el sistema puede cerrarse), modos cinético, fijo y punto final bicromático, con o sin blanco de reactivo o muestra, y calibración lineal y no lineal. Monitorea la curva de reacción en tiempo real, almacena hasta 160 protocolos y un mínimo de 500 resultados, incorpora control de calidad Westgard / Levey-Jennings (2 controles por prueba), auto encendido, auto-zero y autodiagnóstico, y facilita el mantenimiento de lámpara y tubuladuras sin depender de ingeniero para cambios básicos. Rango fotométrico −0,500 a 3,000 Abs; longitudes de onda 340, 405, 500, 546, 578, 620 y 670 nm más filtro opcional; celda de flujo de 25 µL; volumen de aspiración 100–3000 µL; control de temperatura 25/30/37 °C ±0,1 °C. Dimensiones publicadas 460 × 330 × 140 mm; peso neto 8 kg. La configuración final, reactivos, instalación y soporte se confirman en cotización.',
  'The Rayto RT-1904C is a semi-automatic biochemistry analyzer for clinical labs that need chemistry assays with simple Windows operation, mouse and a 7" color LCD. Per the manufacturer insert, it supports an open reagent system (flow cell or on-demand cuvette; the system can be closed), kinetic, fixed-time and bichromatic endpoint modes with or without reagent/sample blank, plus linear and non-linear calibration. It monitors the reaction curve in real time, stores up to 160 protocols and at least 500 results, includes Westgard / Levey-Jennings QC (2 controls per test), auto power-on, auto-zero and self-diagnosis, and simplifies lamp and tubing maintenance for routine changes. Photometric range −0.500 to 3.000 Abs; wavelengths 340, 405, 500, 546, 578, 620 and 670 nm plus optional filter; 25 µL flow cell; aspiration volume 100–3000 µL; temperature control 25/30/37 °C ±0.1 °C. Published size 460 × 330 × 140 mm; net weight 8 kg. Final configuration, reagents, installation and support are confirmed in the quotation.',
  '/assets/productos/bioquimica/rayto-rt-1904c/producto.jpg',
  ARRAY['/assets/productos/bioquimica/rayto-rt-1904c/producto.jpg', '/assets/productos/bioquimica/rayto-rt-1904c/hero-brochure.jpg', '/assets/productos/bioquimica/rayto-rt-1904c/ui-0.jpeg', '/assets/productos/bioquimica/rayto-rt-1904c/ui-2.jpeg'],
  '/assets/productos/bioquimica/rayto-rt-1904c/ficha-tecnica.pdf',
  '[{"clave": "Rango fotométrico","grupo": "Óptica","valor": "−0,500 a 3,000 Abs"},{"clave": "Resolución","grupo": "Óptica","valor": "0,001 Abs (muestra); 0,001 Abs (calculado)"},{"clave": "Fuente de luz","grupo": "Óptica","valor": "Lámpara halógena 6 V / 10 W"},{"clave": "Longitudes de onda","grupo": "Óptica","valor": "340, 405, 500, 546, 578, 620, 670 nm + filtro opcional; precisión ±1 nm; ancho de banda 8 nm"},{"clave": "Celda de flujo","grupo": "Muestreo","valor": "25 µL, metal y cuarzo; cubeta opcional 12,5 × 12,5 mm"},{"clave": "Volumen de aspiración","grupo": "Muestreo","valor": "100–3000 µL (bomba peristáltica); contaminación cruzada <0,1 %"},{"clave": "Métodos","grupo": "Análisis","valor": "Cinético, fijo, punto final bicromático; calibración lineal y no lineal"},{"clave": "Memoria","grupo": "Datos","valor": "Hasta 160 protocolos; mínimo 500 resultados"},{"clave": "Control de calidad","grupo": "Datos","valor": "Reglas Westgard; gráficos Levey-Jennings; 2 controles por prueba"},{"clave": "Temperatura","grupo": "Instalación","valor": "25 °C, 30 °C, 37 °C ±0,1 °C"},{"clave": "Pantalla e interfaz","grupo": "Interfaz","valor": "LCD 7\" color; RS-232; PSTN opcional; mouse/teclado externos opcionales; impresora interna o externa"},{"clave": "Dimensiones y peso","grupo": "Instalación","valor": "460 × 330 × 140 mm; peso neto 8 kg"},{"clave": "Alimentación","grupo": "Instalación","valor": "AC 110/220 V ±10 %, 50/60 Hz"}]'::jsonb,
  ARRAY['Química clínica semiautomática en laboratorio hospitalario o IPS', 'Protocolos programables de enzimas y sustratos con curva de reacción en tiempo real', 'Laboratorios que requieren QC Westgard/Levey-Jennings y reporte de paciente'],
  ARRAY['Semi-automatic clinical chemistry in hospital or outpatient labs', 'Programmable enzyme and substrate protocols with real-time reaction curves', 'Labs needing Westgard/Levey-Jennings QC and patient reporting'],
  'equipo',
  'cotizacion',
  NULL,
  'COP',
  0,
  TRUE, FALSE, TRUE, TRUE,
  468,
  '{"marca": "Rayto","fabricante": "Rayto Life and Analytical Sciences Co.,Ltd.","distribuidor": "I-ME","ref_proveedor": "RT-1904C","fuente_ficha": "175040003.DOC_INSERTO_SAP.175138.pdf (inserto Rayto RT-1904C)","nota_precio": "Sin precio público; fulfillment cotización. No publicar costos de suministro.","beneficios_es": ["Opera con interfaz Windows, mouse y LCD a color de 7\", lo que reduce la curva de aprendizaje frente a equipos solo por menús numéricos.","Cubre modos cinético, fijo y punto final bicromático con monitoreo de curva en tiempo real para reforzar la fiabilidad del resultado.","Guarda hasta 160 protocolos y al menos 500 resultados, con QC Westgard / Levey-Jennings (2 controles por prueba).","Celda de flujo de 25 µL y aspiración 100–3000 µL con contaminación cruzada <0,1 %, útil para paneles de bajo volumen.","Mantenimiento cotidiano de lámpara y tubuladuras sin depender de ingeniero para cambios básicos, según el inserto Rayto."],"beneficios_en": ["Runs with Windows UI, mouse and a 7\" color LCD, lowering the learning curve versus numeric-menu-only analyzers.","Covers kinetic, fixed-time and bichromatic endpoint modes with real-time curve monitoring to support result reliability.","Stores up to 160 protocols and at least 500 results, with Westgard / Levey-Jennings QC (2 controls per test).","25 µL flow cell and 100–3000 µL aspiration with <0.1 % carryover for lower-volume panels.","Routine lamp and tubing maintenance without calling an engineer for basic changes, per the Rayto insert."],"valor_es": "Bioquímica semiautomática compacta (460×330×140 mm, 8 kg) con 160 protocolos, QC documental y curva en tiempo real para laboratorios que cotizan equipo Rayto sin ampliar la bancada.","valor_en": "Compact semi-automatic chemistry (460×330×140 mm, 8 kg) with 160 protocols, documented QC and real-time curves for labs quoting Rayto without expanding the bench.","preguntas_frecuentes_es": [{"q": "¿Qué longitudes de onda trae el RT-1904C?","a": "El inserto Rayto lista 340, 405, 500, 546, 578, 620 y 670 nm, más un filtro opcional; precisión ±1 nm y ancho de banda 8 nm."},{"q": "¿Usa celda de flujo o cubeta?","a": "Soporta celda de flujo de 25 µL (metal y cuarzo) y modo de cubeta opcional 12,5×12,5 mm; el sistema de reactivo puede abrirse o cerrarse según configuración."},{"q": "¿Qué control de calidad incluye?","a": "Reglas Westgard y gráficos Levey-Jennings con 2 controles por prueba, según la ficha del fabricante."},{"q": "¿El PDF fija la configuración contractual?","a": "No necesariamente. Es inserto genérico Rayto (RT-1904C); reactivos, idiomas, instalación y accesorios se validan en la cotización I-ME."},{"q": "¿Se publica precio de lista en la web?","a": "No. El equipo se ofrece en modo cotización; el precio institucional se confirma al comprador."}],"preguntas_frecuentes_en": [{"q": "Which wavelengths does the RT-1904C include?","a": "The Rayto insert lists 340, 405, 500, 546, 578, 620 and 670 nm plus an optional filter; ±1 nm accuracy and 8 nm bandwidth."},{"q": "Flow cell or cuvette?","a": "It supports a 25 µL metal/quartz flow cell and an optional 12.5×12.5 mm cuvette mode; the reagent system can be open or closed depending on configuration."},{"q": "What QC is included?","a": "Westgard rules and Levey-Jennings charts with 2 controls per test, per the manufacturer sheet."},{"q": "Is the PDF contractual?","a": "Not necessarily. It is a generic Rayto insert (RT-1904C); reagents, languages, installation and accessories are validated in the I-ME quotation."},{"q": "Is a list price published online?","a": "No. The analyzer is offered in quotation mode; institutional pricing is confirmed to the buyer."}],"seo_keywords_es": ["analizador bioquímico Rayto RT-1904C","química clínica semiautomática Colombia","analizador bioquímica celda de flujo","Rayto RT-1904C cotización","laboratorio bioquímico semiautomático"],"seo_keywords_en": ["Rayto RT-1904C biochemistry analyzer","semi-automatic clinical chemistry Colombia","flow cell chemistry analyzer","Rayto RT-1904C quote","semi-auto biochemistry analyzer lab"],"imagen_principal": "/assets/productos/bioquimica/rayto-rt-1904c/producto.jpg","galeria": ["/assets/productos/bioquimica/rayto-rt-1904c/producto.jpg","/assets/productos/bioquimica/rayto-rt-1904c/hero-brochure.jpg","/assets/productos/bioquimica/rayto-rt-1904c/ui-0.jpeg","/assets/productos/bioquimica/rayto-rt-1904c/ui-2.jpeg"]}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  nombre_es = EXCLUDED.nombre_es,
  nombre_en = EXCLUDED.nombre_en,
  descripcion_corta_es = EXCLUDED.descripcion_corta_es,
  descripcion_corta_en = EXCLUDED.descripcion_corta_en,
  descripcion_larga_es = EXCLUDED.descripcion_larga_es,
  descripcion_larga_en = EXCLUDED.descripcion_larga_en,
  imagen_principal = EXCLUDED.imagen_principal,
  galeria = EXCLUDED.galeria,
  ficha_pdf = EXCLUDED.ficha_pdf,
  especificaciones = EXCLUDED.especificaciones,
  aplicaciones_es = EXCLUDED.aplicaciones_es,
  aplicaciones_en = EXCLUDED.aplicaciones_en,
  fulfillment_mode = EXCLUDED.fulfillment_mode,
  nuevo = EXCLUDED.nuevo,
  activo = EXCLUDED.activo,
  orden = EXCLUDED.orden,
  atributos = COALESCE(public.productos.atributos, '{}'::jsonb) || EXCLUDED.atributos;


INSERT INTO public.productos (
  id, slug, familia_id, tipo_id,
  nombre_es, nombre_en,
  descripcion_corta_es, descripcion_corta_en,
  descripcion_larga_es, descripcion_larga_en,
  imagen_principal, galeria, ficha_pdf,
  especificaciones, aplicaciones_es, aplicaciones_en,
  tipo_comercial, fulfillment_mode, precio, moneda, stock,
  disponible, destacado, nuevo, activo, orden, atributos
) VALUES (
  '08b935d0-17e9-4589-b665-af56b3665cc8'::uuid,
  'analizador-bioquimico-semiautomatico-biobase-claire',
  '4d9a59cd-2c1e-4755-9584-28d6e9024d3c'::uuid,
  NULL,
  'Analizador bioquímico semiautomático BIOBASE-Claire',
  'BIOBASE-Claire Semi-auto Chemistry Analyzer',
  'Analizador bioquímico semiautomático BIOBASE-Claire: pantalla táctil 7", 144 ítems, 5.600 resultados, celda de flujo y 7 longitudes de onda',
  'BIOBASE-Claire semi-auto chemistry analyzer: 7" touchscreen, 144 items, 5,600 results, flow-through cuvette and 7 wavelengths',
  'El BIOBASE-Claire es un analizador de química clínica semiautomático de bancada documentado en la ficha conjunta BIOBASE Claire & Silver. Incorpora pantalla táctil LCD de 7,0" con interfaz gráfica, memoria para 144 ítems de prueba y 5.600 resultados, impresora térmica integrada con marcado de resultados anormales, y celda de flujo de lectura directa. Métodos: punto final, tiempo fijo (dos puntos) y dinámico (cinético). Longitudes de onda 340/405/450/510/546/578/630 nm con 2 posiciones abiertas para filtros adicionales y precisión ±2 nm. Idiomas: inglés, francés y español (otros bajo personalización). Interfaces RS-232 y USB; consumo 100 VA; alimentación AC 110/220 V ±10 %, 50/60 Hz; tamaño externo 400 × 410 × 190 mm; peso neto 8 kg / bruto 11 kg. Tipos de muestra indicados en ficha: suero, plasma, orina y líquido cefalorraquídeo. Configuración, reactivos, instalación y soporte se confirman en cotización.',
  'BIOBASE-Claire is a bench-top semi-automatic clinical chemistry analyzer documented in the joint BIOBASE Claire & Silver datasheet. It includes a 7.0" LCD touchscreen with graphical UI, memory for 144 test items and 5,600 results, a built-in thermal printer with abnormal-result flags, and a direct-reading flow-through cuvette. Methods: endpoint, fixed-time (two-point) and dynamic (rate). Wavelengths 340/405/450/510/546/578/630 nm with 2 open filter positions and ±2 nm accuracy. Languages: English, French and Spanish (others customizable). RS-232 and USB; consumption 100 VA; AC 110/220 V ±10 %, 50/60 Hz; external size 400 × 410 × 190 mm; net weight 8 kg / gross 11 kg. Sample types listed: serum, plasma, urine and cerebrospinal fluid. Configuration, reagents, installation and support are confirmed in the quotation.',
  '/assets/productos/bioquimica/biobase-claire/producto.jpg',
  ARRAY['/assets/productos/bioquimica/biobase-claire/producto.jpg', '/assets/productos/bioquimica/biobase-claire/hero-brochure.jpg'],
  '/assets/productos/bioquimica/biobase-claire/ficha-tecnica.pdf',
  '[{"clave": "Modelo","grupo": "Identificación","valor": "BIOBASE-Claire"},{"clave": "Tipos de muestra","grupo": "Muestreo","valor": "Suero, plasma, orina y líquido cefalorraquídeo (según ficha)"},{"clave": "Métodos","grupo": "Análisis","valor": "Punto final, tiempo fijo (dos puntos), dinámico (cinético)"},{"clave": "Cubeta","grupo": "Muestreo","valor": "Celda de flujo de lectura directa"},{"clave": "Longitudes de onda","grupo": "Óptica","valor": "340/405/450/510/546/578/630 nm + 2 posiciones abiertas; precisión ±2 nm"},{"clave": "Pantalla","grupo": "Interfaz","valor": "LCD táctil 7,0\""},{"clave": "Idiomas","grupo": "Interfaz","valor": "Inglés, francés, español; otros personalizables"},{"clave": "Impresora","grupo": "Interfaz","valor": "Térmica integrada; marca resultados anormales"},{"clave": "Memoria","grupo": "Datos","valor": "144 ítems de prueba; 5.600 resultados"},{"clave": "Interfaces","grupo": "Conectividad","valor": "RS-232, USB"},{"clave": "Consumo y alimentación","grupo": "Instalación","valor": "100 VA; AC 110/220 V ±10 %, 50/60 Hz"},{"clave": "Dimensiones y peso","grupo": "Instalación","valor": "400 × 410 × 190 mm; neto 8 kg; embalaje 520 × 490 × 330 mm; bruto 11 kg"}]'::jsonb,
  ARRAY['Química clínica semiautomática en laboratorios de volumen bajo-medio', 'Ensayos de suero, plasma, orina o LCR con celda de flujo', 'Flujos que necesitan impresora térmica y pantalla táctil 7" en bancada compacta'],
  ARRAY['Semi-automatic clinical chemistry in low-to-mid volume laboratories', 'Serum, plasma, urine or CSF assays via flow-through cuvette', 'Workflows needing a thermal printer and 7" touchscreen on a compact bench'],
  'equipo',
  'cotizacion',
  NULL,
  'COP',
  0,
  TRUE, FALSE, TRUE, TRUE,
  469,
  '{"marca": "BIOBASE","fabricante": "BIOBASE","distribuidor": "I-ME","ref_proveedor": "BIOBASE-Claire","fuente_ficha": "19-20 Semi-auto Chemistry Analyzer BIOBASE-Claire&BIOBASE-Silver(4).pdf","nota_precio": "Sin precio público; fulfillment cotización.","beneficios_es": ["Pantalla táctil de 7,0\" con interfaz gráfica facilita la operación diaria frente a menús solo por teclado.","Almacena 144 ítems y 5.600 resultados para laboratorios que rotan paneles sin depender de PC externo.","Impresora térmica integrada marca resultados anormales para revisión inmediata en mesa.","Siete longitudes de onda fijas más 2 filtros abiertos (±2 nm) cubren el espectro habitual de química clínica.","Huella 400×410×190 mm y 8 kg netos: cabe en bancadas pequeñas sin sacrificar USB/RS-232."],"beneficios_en": ["7.0\" touchscreen with graphical UI eases daily operation versus keyboard-only menus.","Stores 144 items and 5,600 results for labs that rotate panels without an external PC.","Built-in thermal printer flags abnormal results for immediate bench review.","Seven fixed wavelengths plus 2 open filters (±2 nm) cover common clinical chemistry spectra.","400×410×190 mm footprint and 8 kg net weight fit small benches while keeping USB/RS-232."],"valor_es": "Entrada BIOBASE a química semiautomática: 7\" táctil, 144 ítems y celda de flujo en 8 kg para laboratorios que cotizan Claire antes de subir a Silver.","valor_en": "BIOBASE entry to semi-auto chemistry: 7\" touch, 144 items and flow cell in 8 kg for labs quoting Claire before stepping up to Silver.","preguntas_frecuentes_es": [{"q": "¿Cuántos ítems y resultados guarda Claire?","a": "La ficha BIOBASE indica 144 ítems de prueba y 5.600 resultados."},{"q": "¿Qué métodos analíticos soporta?","a": "Punto final, tiempo fijo (dos puntos) y dinámico (método de tasa/cinético)."},{"q": "¿En qué se diferencia de BIOBASE-Silver?","a": "Según la misma ficha: Claire lista 144 ítems / 5.600 resultados y 100 VA; Silver lista 300 ítems / 20.000 resultados, 20 posiciones de incubación, 150 VA y 9 kg netos."},{"q": "¿La ficha es exclusiva de Claire?","a": "No. El PDF fuente es la hoja conjunta “Semi-auto Chemistry Analyzer BIOBASE-Claire & BIOBASE-Silver”; cada landing usa solo los parámetros de su columna."},{"q": "¿Hay precio publicado?","a": "No. Se cotiza; el precio institucional se confirma al comprador."}],"preguntas_frecuentes_en": [{"q": "How many items and results does Claire store?","a": "The BIOBASE sheet lists 144 test items and 5,600 results."},{"q": "Which analytical methods are supported?","a": "Endpoint, fixed-time (two-point) and dynamic (rate) methods."},{"q": "How does it differ from BIOBASE-Silver?","a": "Per the same sheet: Claire lists 144 items / 5,600 results and 100 VA; Silver lists 300 items / 20,000 results, 20 incubating positions, 150 VA and 9 kg net."},{"q": "Is the datasheet Claire-only?","a": "No. The source PDF is the joint “BIOBASE-Claire & BIOBASE-Silver” page; each landing uses only its column parameters."},{"q": "Is a price published?","a": "No. It is quoted; institutional pricing is confirmed to the buyer."}],"seo_keywords_es": ["BIOBASE-Claire analizador bioquímico","química clínica semiautomática BIOBASE","analizador bioquímica pantalla táctil 7","BIOBASE Claire cotización Colombia","celda de flujo laboratorio"],"seo_keywords_en": ["BIOBASE-Claire chemistry analyzer","BIOBASE semi-auto clinical chemistry","7 inch touchscreen biochemistry analyzer","BIOBASE Claire quote Colombia","flow-through cuvette analyzer"],"imagen_principal": "/assets/productos/bioquimica/biobase-claire/producto.jpg","galeria": ["/assets/productos/bioquimica/biobase-claire/producto.jpg","/assets/productos/bioquimica/biobase-claire/hero-brochure.jpg"]}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  nombre_es = EXCLUDED.nombre_es,
  nombre_en = EXCLUDED.nombre_en,
  descripcion_corta_es = EXCLUDED.descripcion_corta_es,
  descripcion_corta_en = EXCLUDED.descripcion_corta_en,
  descripcion_larga_es = EXCLUDED.descripcion_larga_es,
  descripcion_larga_en = EXCLUDED.descripcion_larga_en,
  imagen_principal = EXCLUDED.imagen_principal,
  galeria = EXCLUDED.galeria,
  ficha_pdf = EXCLUDED.ficha_pdf,
  especificaciones = EXCLUDED.especificaciones,
  aplicaciones_es = EXCLUDED.aplicaciones_es,
  aplicaciones_en = EXCLUDED.aplicaciones_en,
  fulfillment_mode = EXCLUDED.fulfillment_mode,
  nuevo = EXCLUDED.nuevo,
  activo = EXCLUDED.activo,
  orden = EXCLUDED.orden,
  atributos = COALESCE(public.productos.atributos, '{}'::jsonb) || EXCLUDED.atributos;


INSERT INTO public.productos (
  id, slug, familia_id, tipo_id,
  nombre_es, nombre_en,
  descripcion_corta_es, descripcion_corta_en,
  descripcion_larga_es, descripcion_larga_en,
  imagen_principal, galeria, ficha_pdf,
  especificaciones, aplicaciones_es, aplicaciones_en,
  tipo_comercial, fulfillment_mode, precio, moneda, stock,
  disponible, destacado, nuevo, activo, orden, atributos
) VALUES (
  '18f5314a-b532-4b03-a847-b229bc94a779'::uuid,
  'analizador-bioquimico-semiautomatico-biobase-silver',
  '4d9a59cd-2c1e-4755-9584-28d6e9024d3c'::uuid,
  NULL,
  'Analizador bioquímico semiautomático BIOBASE-Silver',
  'BIOBASE-Silver Semi-auto Chemistry Analyzer',
  'Analizador bioquímico semiautomático BIOBASE-Silver: 300 ítems, 20.000 resultados, 20 posiciones de incubación y pantalla táctil 7"',
  'BIOBASE-Silver semi-auto chemistry analyzer: 300 items, 20,000 results, 20 incubating positions and 7" touchscreen',
  'El BIOBASE-Silver es la variante de mayor capacidad de la ficha conjunta Claire & Silver. Según parámetros del fabricante: pantalla táctil LCD 7,0", memoria para 300 ítems y 20.000 resultados, impresora térmica con flag de anormales, 20 posiciones de incubación y control de temperatura ambiente / 25 / 30 / 37 °C. Métodos punto final, tiempo fijo y dinámico; celda de flujo de lectura directa; longitudes de onda 340/405/450/510/546/578/630 nm + 2 filtros abiertos (±2 nm). Idiomas EN/FR/ES; RS-232 y USB; consumo 150 VA; AC 110/220 V ±10 %, 50/60 Hz; tamaño 400 × 410 × 190 mm; peso neto 9 kg / bruto 12 kg. Tipos de muestra: suero, plasma, orina y LCR. Configuración final en cotización.',
  'BIOBASE-Silver is the higher-capacity variant on the joint Claire & Silver datasheet. Manufacturer parameters: 7.0" LCD touchscreen, memory for 300 items and 20,000 results, thermal printer with abnormal flags, 20 incubating positions and room-temperature / 25 / 30 / 37 °C control. Endpoint, fixed-time and dynamic methods; direct-reading flow-through cuvette; wavelengths 340/405/450/510/546/578/630 nm + 2 open filters (±2 nm). Languages EN/FR/ES; RS-232 and USB; 150 VA; AC 110/220 V ±10 %, 50/60 Hz; size 400 × 410 × 190 mm; net 9 kg / gross 12 kg. Sample types: serum, plasma, urine and CSF. Final configuration in quotation.',
  '/assets/productos/bioquimica/biobase-silver/producto.jpg',
  ARRAY['/assets/productos/bioquimica/biobase-silver/producto.jpg', '/assets/productos/bioquimica/biobase-silver/hero-brochure.jpg'],
  '/assets/productos/bioquimica/biobase-silver/ficha-tecnica.pdf',
  '[{"clave": "Modelo","grupo": "Identificación","valor": "BIOBASE-Silver"},{"clave": "Tipos de muestra","grupo": "Muestreo","valor": "Suero, plasma, orina y líquido cefalorraquídeo (según ficha)"},{"clave": "Métodos","grupo": "Análisis","valor": "Punto final, tiempo fijo (dos puntos), dinámico (cinético)"},{"clave": "Incubación","grupo": "Temperatura","valor": "20 posiciones; T. ambiente, 25 °C, 30 °C, 37 °C"},{"clave": "Cubeta","grupo": "Muestreo","valor": "Celda de flujo de lectura directa"},{"clave": "Longitudes de onda","grupo": "Óptica","valor": "340/405/450/510/546/578/630 nm + 2 posiciones abiertas; precisión ±2 nm"},{"clave": "Pantalla","grupo": "Interfaz","valor": "LCD táctil 7,0\""},{"clave": "Idiomas","grupo": "Interfaz","valor": "Inglés, francés, español; otros personalizables"},{"clave": "Impresora","grupo": "Interfaz","valor": "Térmica integrada; marca resultados anormales"},{"clave": "Memoria","grupo": "Datos","valor": "300 ítems de prueba; 20.000 resultados"},{"clave": "Interfaces","grupo": "Conectividad","valor": "RS-232, USB"},{"clave": "Consumo y alimentación","grupo": "Instalación","valor": "150 VA; AC 110/220 V ±10 %, 50/60 Hz"},{"clave": "Dimensiones y peso","grupo": "Instalación","valor": "400 × 410 × 190 mm; neto 9 kg; embalaje 520 × 490 × 330 mm; bruto 12 kg"}]'::jsonb,
  ARRAY['Química clínica semiautomática con incubación integrada de 20 posiciones', 'Laboratorios que necesitan más memoria (300 ítems / 20.000 resultados) que Claire', 'Ensayos de suero, plasma, orina o LCR con control 25/30/37 °C'],
  ARRAY['Semi-automatic clinical chemistry with integrated 20-position incubation', 'Labs needing more memory (300 items / 20,000 results) than Claire', 'Serum, plasma, urine or CSF assays with 25/30/37 °C control'],
  'equipo',
  'cotizacion',
  NULL,
  'COP',
  0,
  TRUE, FALSE, TRUE, TRUE,
  470,
  '{"marca": "BIOBASE","fabricante": "BIOBASE","distribuidor": "I-ME","ref_proveedor": "BIOBASE-Silver","fuente_ficha": "19-20 Semi-auto Chemistry Analyzer BIOBASE-Claire&BIOBASE-Silver(4).pdf","nota_precio": "Sin precio público; fulfillment cotización.","beneficios_es": ["Sube la memoria a 300 ítems y 20.000 resultados frente a Claire (144 / 5.600) sin cambiar la huella 400×410×190 mm.","Aporta 20 posiciones de incubación con T. ambiente / 25 / 30 / 37 °C para protocolos que requieren preincubación en bancada.","Mantiene pantalla táctil 7\", impresora térmica con flags y misma batería óptica de 7+2 longitudes de onda.","Consumo 150 VA con USB/RS-232 para conectar a flujos de laboratorio existentes.","Misma familia visual BIOBASE que Claire, útil cuando la institución quiere estandarizar marca y subir capacidad."],"beneficios_en": ["Raises memory to 300 items and 20,000 results versus Claire (144 / 5,600) without changing the 400×410×190 mm footprint.","Adds 20 incubating positions with ambient / 25 / 30 / 37 °C for protocols that need bench pre-incubation.","Keeps the 7\" touchscreen, thermal printer with flags and the same 7+2 wavelength optical set.","150 VA draw with USB/RS-232 to connect into existing lab workflows.","Same BIOBASE visual family as Claire when institutions want brand standardization and more capacity."],"valor_es": "Claire+capacidad: mismos 7\" y óptica, con 20 incubaciones, 300 ítems y 20.000 resultados para laboratorios que ya cotizan Silver.","valor_en": "Claire+capacity: same 7\" and optics, with 20 incubations, 300 items and 20,000 results for labs already quoting Silver.","preguntas_frecuentes_es": [{"q": "¿Cuántas posiciones de incubación tiene?","a": "La ficha lista 20 posiciones de incubación con temperatura ambiente, 25 °C, 30 °C y 37 °C."},{"q": "¿Cuánta memoria tiene frente a Claire?","a": "Silver: 300 ítems y 20.000 resultados. Claire: 144 ítems y 5.600 resultados (misma ficha BIOBASE)."},{"q": "¿Comparte PDF con Claire?","a": "Sí. El archivo fuente es la hoja conjunta Claire & Silver; esta landing usa solo la columna Silver."},{"q": "¿Qué consumo eléctrico declara?","a": "150 VA a AC 110/220 V ±10 %, 50/60 Hz."},{"q": "¿Precio web?","a": "No. Modo cotización; precio institucional al comprador."}],"preguntas_frecuentes_en": [{"q": "How many incubating positions?","a": "The sheet lists 20 incubating positions with ambient, 25 °C, 30 °C and 37 °C."},{"q": "How does memory compare to Claire?","a": "Silver: 300 items and 20,000 results. Claire: 144 items and 5,600 results (same BIOBASE sheet)."},{"q": "Does it share a PDF with Claire?","a": "Yes. The source file is the joint Claire & Silver page; this landing uses only the Silver column."},{"q": "What power consumption is listed?","a": "150 VA at AC 110/220 V ±10 %, 50/60 Hz."},{"q": "Web price?","a": "None. Quotation mode; institutional price to the buyer."}],"seo_keywords_es": ["BIOBASE-Silver analizador bioquímico","analizador bioquímica 20 incubaciones","química semiautomática 300 ítems","BIOBASE Silver cotización","analizador clínico pantalla 7 pulgadas"],"seo_keywords_en": ["BIOBASE-Silver chemistry analyzer","20 incubating positions chemistry analyzer","semi-auto chemistry 300 test items","BIOBASE Silver quote","7 inch touchscreen clinical analyzer"],"imagen_principal": "/assets/productos/bioquimica/biobase-silver/producto.jpg","galeria": ["/assets/productos/bioquimica/biobase-silver/producto.jpg","/assets/productos/bioquimica/biobase-silver/hero-brochure.jpg"]}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  nombre_es = EXCLUDED.nombre_es,
  nombre_en = EXCLUDED.nombre_en,
  descripcion_corta_es = EXCLUDED.descripcion_corta_es,
  descripcion_corta_en = EXCLUDED.descripcion_corta_en,
  descripcion_larga_es = EXCLUDED.descripcion_larga_es,
  descripcion_larga_en = EXCLUDED.descripcion_larga_en,
  imagen_principal = EXCLUDED.imagen_principal,
  galeria = EXCLUDED.galeria,
  ficha_pdf = EXCLUDED.ficha_pdf,
  especificaciones = EXCLUDED.especificaciones,
  aplicaciones_es = EXCLUDED.aplicaciones_es,
  aplicaciones_en = EXCLUDED.aplicaciones_en,
  fulfillment_mode = EXCLUDED.fulfillment_mode,
  nuevo = EXCLUDED.nuevo,
  activo = EXCLUDED.activo,
  orden = EXCLUDED.orden,
  atributos = COALESCE(public.productos.atributos, '{}'::jsonb) || EXCLUDED.atributos;


INSERT INTO public.productos (
  id, slug, familia_id, tipo_id,
  nombre_es, nombre_en,
  descripcion_corta_es, descripcion_corta_en,
  descripcion_larga_es, descripcion_larga_en,
  imagen_principal, galeria, ficha_pdf,
  especificaciones, aplicaciones_es, aplicaciones_en,
  tipo_comercial, fulfillment_mode, precio, moneda, stock,
  disponible, destacado, nuevo, activo, orden, atributos
) VALUES (
  'e3c6b8a1-34f9-4e9b-96e2-937ad3ce3386'::uuid,
  'analizador-bioquimico-semiautomatico-biobase-silver-plus',
  '4d9a59cd-2c1e-4755-9584-28d6e9024d3c'::uuid,
  NULL,
  'Analizador bioquímico semiautomático BIOBASE-Silver Plus',
  'BIOBASE-Silver Plus Semi-auto Chemistry Analyzer',
  'Analizador bioquímico semiautomático BIOBASE-Silver Plus: 20 incubaciones, 200 programas, 1.000 resultados y QC con gráfica',
  'BIOBASE-Silver Plus semi-auto chemistry analyzer: 20 incubations, 200 programs, 1,000 results and chartable QC',
  'El BIOBASE-Silver Plus aparece en ficha de producto como analizador de química semiautomático con operación simplificada (un botón) y conexión a computador. La documentación lista métodos de punto final, dos puntos (tiempo fijo), cinético, multiestándar y bicromático; 20 posiciones de incubación; memoria para 200 programas de prueba y 1.000 resultados; función de control de calidad con gráfica almacenable, visualizable e imprimible; tres niveles de temperatura (25 °C, 30 °C, 37 °C) seleccionables en celda de flujo e incubación; y gráfica en tiempo real visualizable e imprimible. La ficha de origen no publica tabla completa de longitudes de onda ni dimensiones; esos datos se confirman en cotización. Configuración, reactivos, instalación y soporte institucionales se validan al cotizar.',
  'BIOBASE-Silver Plus is presented on the product sheet as a semi-automatic chemistry analyzer with one-button operation and computer connection. Documentation lists endpoint, two-point (fixed-time), kinetic, multi-standard and bichromatic methods; 20 incubating positions; memory for 200 test programs and 1,000 results; QC with charts that can be stored, displayed and printed; three temperature levels (25 °C, 30 °C, 37 °C) selectable in the flow cell and incubator; and real-time graphs that can be displayed and printed. The source sheet does not publish a full wavelength or dimension table; those details are confirmed in quotation. Institutional configuration, reagents, installation and support are validated when quoting.',
  '/assets/productos/bioquimica/biobase-silver-plus/producto.jpg',
  ARRAY['/assets/productos/bioquimica/biobase-silver-plus/producto.jpg', '/assets/productos/bioquimica/biobase-silver-plus/hero-brochure.jpg'],
  '/assets/productos/bioquimica/biobase-silver-plus/ficha-tecnica.pdf',
  '[{"clave": "Modelo","grupo": "Identificación","valor": "BIOBASE-Silver Plus"},{"clave": "Operación","grupo": "Interfaz","valor": "Operación simplificada por un botón; conexión a computador"},{"clave": "Métodos","grupo": "Análisis","valor": "Punto final, dos puntos (tiempo fijo), cinético, multiestándar, bicromático, entre otros"},{"clave": "Incubación","grupo": "Temperatura","valor": "20 posiciones de incubación"},{"clave": "Temperatura","grupo": "Temperatura","valor": "25 °C, 30 °C, 37 °C seleccionables en celda de flujo e incubación"},{"clave": "Memoria","grupo": "Datos","valor": "200 programas de prueba; 1.000 resultados"},{"clave": "Control de calidad","grupo": "Datos","valor": "Gráfica QC almacenable, visualizable e imprimible"},{"clave": "Visualización","grupo": "Datos","valor": "Gráfica en tiempo real visualizable e imprimible"}]'::jsonb,
  ARRAY['Química clínica semiautomática con incubación de 20 posiciones', 'Laboratorios que requieren QC documental con gráfica imprimible', 'Flujos con conexión a computador y operación simplificada'],
  ARRAY['Semi-automatic clinical chemistry with 20-position incubation', 'Labs needing documented QC with printable charts', 'Workflows with computer connection and simplified operation'],
  'equipo',
  'cotizacion',
  NULL,
  'COP',
  0,
  TRUE, FALSE, TRUE, TRUE,
  471,
  '{"marca": "BIOBASE","fabricante": "BIOBASE","distribuidor": "I-ME","ref_proveedor": "BIOBASE-Silver Plus","fuente_ficha": "BIOBASE_Silver_Plus_Ficha_Producto.pdf (hoja features; branding KGC en documento fuente)","nota_precio": "Sin precio público; fulfillment cotización. Specs limitadas a features publicadas en ficha.","beneficios_es": ["Opera con un botón y puede conectarse a computador, reduciendo fricción en puestos de bajo volumen.","Incluye 20 posiciones de incubación y temperatura 25/30/37 °C en celda de flujo e incubación.","Guarda 200 programas y 1.000 resultados con QC y gráficas en tiempo real imprimibles.","Cubre punto final, tiempo fijo, cinético, multiestándar y bicromático según la ficha Silver Plus.","Complementa la línea Silver cuando la institución pide la variante Plus documentada por fabricante/distribuidor."],"beneficios_en": ["One-button operation with computer connection reduces friction in low-volume benches.","Includes 20 incubating positions and 25/30/37 °C control in flow cell and incubator.","Stores 200 programs and 1,000 results with printable QC and real-time graphs.","Covers endpoint, fixed-time, kinetic, multi-standard and bichromatic methods per the Silver Plus sheet.","Extends the Silver line when institutions request the Plus variant documented by manufacturer/distributor."],"valor_es": "Variante Plus de la línea Silver: 20 incubaciones, QC con gráfica y operación a un botón para laboratorios que cotizan Silver Plus con ficha de producto.","valor_en": "Plus variant of the Silver line: 20 incubations, chartable QC and one-button operation for labs quoting Silver Plus from the product sheet.","preguntas_frecuentes_es": [{"q": "¿Qué memoria declara Silver Plus?","a": "La ficha indica 200 programas de prueba y 1.000 resultados."},{"q": "¿Tiene incubación?","a": "Sí. Lista 20 posiciones de incubación y temperaturas 25/30/37 °C en celda de flujo e incubación."},{"q": "¿Por qué hay menos specs que en Silver?","a": "La ficha Silver Plus de origen solo publica el bloque de características; no incluye la tabla completa de longitudes de onda/dimensiones de la hoja Claire&Silver. Lo faltante se confirma en cotización."},{"q": "¿La marca KGC del PDF es el fabricante?","a": "La hoja muestra branding KGC sobre el producto BIOBASE-Silver Plus. El modelo publicado es BIOBASE; el canal comercial se confirma al cotizar."},{"q": "¿Precio en web?","a": "No. Cotización institucional."}],"preguntas_frecuentes_en": [{"q": "What memory does Silver Plus list?","a": "The sheet lists 200 test programs and 1,000 results."},{"q": "Does it include incubation?","a": "Yes. It lists 20 incubating positions and 25/30/37 °C in the flow cell and incubator."},{"q": "Why fewer specs than Silver?","a": "The source Silver Plus sheet only publishes the features block; it lacks the full wavelength/dimension table from the Claire&Silver page. Missing items are confirmed in quotation."},{"q": "Is KGC on the PDF the manufacturer?","a": "The sheet shows KGC branding over the BIOBASE-Silver Plus product. The published model is BIOBASE; the commercial channel is confirmed when quoting."},{"q": "Web price?","a": "No. Institutional quotation."}],"seo_keywords_es": ["BIOBASE-Silver Plus analizador","química semiautomática 20 incubaciones","analizador bioquímico QC gráfica","BIOBASE Silver Plus cotización","analizador bioquímica un botón"],"seo_keywords_en": ["BIOBASE-Silver Plus analyzer","semi-auto chemistry 20 incubations","chemistry analyzer QC chart","BIOBASE Silver Plus quote","one-button biochemistry analyzer"],"imagen_principal": "/assets/productos/bioquimica/biobase-silver-plus/producto.jpg","galeria": ["/assets/productos/bioquimica/biobase-silver-plus/producto.jpg","/assets/productos/bioquimica/biobase-silver-plus/hero-brochure.jpg"]}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  nombre_es = EXCLUDED.nombre_es,
  nombre_en = EXCLUDED.nombre_en,
  descripcion_corta_es = EXCLUDED.descripcion_corta_es,
  descripcion_corta_en = EXCLUDED.descripcion_corta_en,
  descripcion_larga_es = EXCLUDED.descripcion_larga_es,
  descripcion_larga_en = EXCLUDED.descripcion_larga_en,
  imagen_principal = EXCLUDED.imagen_principal,
  galeria = EXCLUDED.galeria,
  ficha_pdf = EXCLUDED.ficha_pdf,
  especificaciones = EXCLUDED.especificaciones,
  aplicaciones_es = EXCLUDED.aplicaciones_es,
  aplicaciones_en = EXCLUDED.aplicaciones_en,
  fulfillment_mode = EXCLUDED.fulfillment_mode,
  nuevo = EXCLUDED.nuevo,
  activo = EXCLUDED.activo,
  orden = EXCLUDED.orden,
  atributos = COALESCE(public.productos.atributos, '{}'::jsonb) || EXCLUDED.atributos;


INSERT INTO public.productos (
  id, slug, familia_id, tipo_id,
  nombre_es, nombre_en,
  descripcion_corta_es, descripcion_corta_en,
  descripcion_larga_es, descripcion_larga_en,
  imagen_principal, galeria, ficha_pdf,
  especificaciones, aplicaciones_es, aplicaciones_en,
  tipo_comercial, fulfillment_mode, precio, moneda, stock,
  disponible, destacado, nuevo, activo, orden, atributos
) VALUES (
  'd2ff9c7c-ad3a-4d9b-bf40-6507370e5072'::uuid,
  'analizador-bioquimico-semiautomatico-sunnymed-sy-b010',
  '4d9a59cd-2c1e-4755-9584-28d6e9024d3c'::uuid,
  NULL,
  'Analizador bioquímico semiautomático SUNNYMED SY-B010',
  'SUNNYMED SY-B010 Semi-Auto Chemistry Analyzer',
  'Analizador bioquímico semiautomático SUNNYMED SY-B010: celda de cuarzo desde 32 µL, métodos cinético/punto final y alimentación 85–264 V',
  'SUNNYMED SY-B010 semi-auto chemistry analyzer: quartz cell from 32 µL, kinetic/endpoint methods and 85–264 V supply',
  'El SUNNYMED SY-B010 es un analizador de bioquímica / química clínica semiautomático de Sunny Medical Equipment Limited. La ficha técnica compilada a partir de información comercial publicada lista celda de flujo de cuarzo permanente con volumen mínimo indicado de 32 µL (opción de celda desechable), muestreo por sistema automático de presión para controlar la aspiración, y métodos de punto final, tiempo fijo, cinético, factor, multiestándar, bicromático y doble longitud de onda. Incorpora pantalla LCD de alto brillo, impresora térmica interna con posibilidad de impresora externa, volumen de muestra 10–50 µL, condiciones de trabajo 10–30 °C y humedad relativa 20–80 %, alimentación AC 85–264 V con adaptación automática, consumo ≤100 W y precisión de longitud de onda ±2 nm. Compatibilidad de software indicada: Windows Vista, XP y 2000. La fuente declara certificación CE en el listado comercial; no es un PDF original emitido por el fabricante. Configuración contractual, reactivos e instalación se confirman en cotización I-ME.',
  'The SUNNYMED SY-B010 is a semi-automatic biochemistry / clinical chemistry analyzer from Sunny Medical Equipment Limited. The datasheet compiled from published commercial information lists a permanent quartz flow cell with a stated minimum volume of 32 µL (disposable cell option), automatic pressure sampling to control aspiration, and endpoint, fixed-time, kinetic, factor, multi-standard, bichromatic and dual-wavelength methods. It includes a high-brightness LCD, internal thermal printer with external printer option, sample volume 10–50 µL, operating conditions 10–30 °C and 20–80 % RH, AC 85–264 V auto-ranging supply, ≤100 W consumption and ±2 nm wavelength accuracy. Listed software compatibility: Windows Vista, XP and 2000. The source states CE on the commercial listing; it is not an original manufacturer-issued PDF. Contractual configuration, reagents and installation are confirmed in the I-ME quotation.',
  '/assets/productos/bioquimica/sunnymed-sy-b010/producto.jpg',
  ARRAY['/assets/productos/bioquimica/sunnymed-sy-b010/producto.jpg', '/assets/productos/bioquimica/sunnymed-sy-b010/hero-brochure.jpg'],
  '/assets/productos/bioquimica/sunnymed-sy-b010/ficha-tecnica.pdf',
  '[{"clave": "Marca / modelo","grupo": "Identificación","valor": "SUNNYMED SY-B010"},{"clave": "Tipo","grupo": "Identificación","valor": "Analizador de bioquímica / química clínica semiautomático"},{"clave": "Celda de flujo","grupo": "Muestreo","valor": "Cuarzo permanente; volumen mínimo indicado 32 µL; opción celda desechable"},{"clave": "Muestreo","grupo": "Muestreo","valor": "Sistema automático de presión para controlar volumen de aspiración"},{"clave": "Volumen de muestra","grupo": "Muestreo","valor": "10–50 µL"},{"clave": "Métodos","grupo": "Análisis","valor": "Punto final, tiempo fijo, cinético, factor, multiestándar, bicromático y doble longitud de onda"},{"clave": "Precisión de longitud de onda","grupo": "Óptica","valor": "±2 nm (especificación publicada)"},{"clave": "Pantalla","grupo": "Interfaz","valor": "LCD de alto brillo"},{"clave": "Impresión","grupo": "Interfaz","valor": "Impresora térmica interna; posibilidad de impresora externa"},{"clave": "Condiciones de trabajo","grupo": "Instalación","valor": "10–30 °C; humedad relativa 20–80 %"},{"clave": "Alimentación y consumo","grupo": "Instalación","valor": "AC 85–264 V (adaptación automática); ≤100 W"},{"clave": "Compatibilidad indicada","grupo": "Software","valor": "Windows Vista, XP y 2000 (según ficha comercial)"},{"clave": "Certificación indicada","grupo": "Documentación","valor": "CE según listado comercial de origen; validar documentación regulatoria en cotización"}]'::jsonb,
  ARRAY['Química clínica semiautomática en laboratorios de bajo-medio volumen', 'Ensayos con microvolumen (10–50 µL) y celda de cuarzo desde 32 µL', 'Puestos que requieren impresora térmica y alimentación auto-rango 85–264 V'],
  ARRAY['Semi-automatic clinical chemistry in low-to-mid volume labs', 'Assays with micro-volume (10–50 µL) and quartz cell from 32 µL', 'Benches needing a thermal printer and 85–264 V auto-ranging supply'],
  'equipo',
  'cotizacion',
  NULL,
  'COP',
  0,
  TRUE, FALSE, TRUE, TRUE,
  472,
  '{"marca": "SUNNYMED","fabricante": "Sunny Medical Equipment Limited","distribuidor": "I-ME","ref_proveedor": "SY-B010","fuente_ficha": "SUNNYMED_SY-B010_Ficha_Tecnica.pdf (compilada desde listado comercial Made-in-China; no PDF OEM original)","fuente_url": "https://es.made-in-china.com/co_sunnymedgz/product_Clinical-Analytical-Device-Lab-Semi-Auto-Chemistry-Analyser-for-Sale_oyyririrg.html","nota_precio": "Sin precio público; fulfillment cotización. Validar documentación regulatoria en cotización.","beneficios_es": ["Celda de cuarzo permanente desde 32 µL (con opción desechable) orientada a paneles de bajo volumen.","Volumen de muestra 10–50 µL con aspiración controlada por presión automática.","Cubre punto final, tiempo fijo, cinético, factor, multiestándar, bicromático y doble longitud de onda.","Alimentación AC 85–264 V auto-rango y ≤100 W simplifica instalación en sedes con voltaje variable.","Impresora térmica interna (y externa opcional) para reporte en mesa sin PC dedicado."],"beneficios_en": ["Permanent quartz cell from 32 µL (disposable option) aimed at lower-volume panels.","Sample volume 10–50 µL with automatic pressure-controlled aspiration.","Covers endpoint, fixed-time, kinetic, factor, multi-standard, bichromatic and dual-wavelength methods.","AC 85–264 V auto-ranging supply and ≤100 W simplify installs on mixed-voltage sites.","Internal thermal printer (external optional) for bench reporting without a dedicated PC."],"valor_es": "Bioquímica semiautomática SUNNYMED con microvolumen y fuente 85–264 V para laboratorios que cotizan SY-B010 a partir de ficha comercial verificada.","valor_en": "SUNNYMED semi-auto chemistry with micro-volume and 85–264 V supply for labs quoting SY-B010 from verified commercial datasheet data.","preguntas_frecuentes_es": [{"q": "¿De dónde salen las especificaciones?","a": "De ficha maquetada con información comercial publicada por Sunny Medical Equipment Limited (Made-in-China). El propio PDF aclara que no es un PDF original del fabricante."},{"q": "¿Qué volumen de muestra usa?","a": "10–50 µL; la celda de cuarzo permanente indica volumen mínimo de 32 µL."},{"q": "¿Qué dice sobre certificación CE?","a": "El listado comercial de origen indica CE. La documentación regulatoria aplicable en Colombia se valida en la cotización; no se asume registro INVIMA desde esa mención."},{"q": "¿Qué sistemas operativos menciona?","a": "Vista, Windows XP y Windows 2000 según la ficha comercial; conviene confirmar compatibilidad real al cotizar."},{"q": "¿Hay precio en la web?","a": "No. Modo cotización."}],"preguntas_frecuentes_en": [{"q": "Where do the specs come from?","a": "From a datasheet compiled from commercial information published by Sunny Medical Equipment Limited (Made-in-China). The PDF itself states it is not an original manufacturer-issued PDF."},{"q": "What sample volume is used?","a": "10–50 µL; the permanent quartz cell states a 32 µL minimum volume."},{"q": "What about CE certification?","a": "The source commercial listing indicates CE. Applicable Colombian regulatory documentation is validated in quotation; INVIMA registration is not assumed from that mention."},{"q": "Which operating systems are listed?","a": "Vista, Windows XP and Windows 2000 per the commercial sheet; confirm real compatibility when quoting."},{"q": "Is there a web price?","a": "No. Quotation mode."}],"seo_keywords_es": ["SUNNYMED SY-B010","analizador bioquímico semiautomático SUNNYMED","química clínica celda cuarzo 32 µL","SY-B010 cotización Colombia","analizador bioquímica 85-264 V"],"seo_keywords_en": ["SUNNYMED SY-B010","SUNNYMED semi-auto chemistry analyzer","quartz flow cell 32 µL analyzer","SY-B010 quote Colombia","85-264 V biochemistry analyzer"],"imagen_principal": "/assets/productos/bioquimica/sunnymed-sy-b010/producto.jpg","galeria": ["/assets/productos/bioquimica/sunnymed-sy-b010/producto.jpg","/assets/productos/bioquimica/sunnymed-sy-b010/hero-brochure.jpg"]}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  nombre_es = EXCLUDED.nombre_es,
  nombre_en = EXCLUDED.nombre_en,
  descripcion_corta_es = EXCLUDED.descripcion_corta_es,
  descripcion_corta_en = EXCLUDED.descripcion_corta_en,
  descripcion_larga_es = EXCLUDED.descripcion_larga_es,
  descripcion_larga_en = EXCLUDED.descripcion_larga_en,
  imagen_principal = EXCLUDED.imagen_principal,
  galeria = EXCLUDED.galeria,
  ficha_pdf = EXCLUDED.ficha_pdf,
  especificaciones = EXCLUDED.especificaciones,
  aplicaciones_es = EXCLUDED.aplicaciones_es,
  aplicaciones_en = EXCLUDED.aplicaciones_en,
  fulfillment_mode = EXCLUDED.fulfillment_mode,
  nuevo = EXCLUDED.nuevo,
  activo = EXCLUDED.activo,
  orden = EXCLUDED.orden,
  atributos = COALESCE(public.productos.atributos, '{}'::jsonb) || EXCLUDED.atributos;
