-- Enriquecimiento de landings desde fichas técnicas oficiales del fabricante (konfort-plus-apoyo-marcha).
-- Contenido redactado solo con datos presentes en la ficha; ver informe docs/informe-fichas-fabricantes-2026-10-02.md.
-- Se aplica con el workflow manual "Deploy Supabase Migrations". Idempotente (UPDATE por slug).

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4102-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón con Empuñadura en T Ergonómico Konfort Plus está diseñado para proporcionar un apoyo elegante y cómodo para quienes necesitan asistencia al caminar. Fabricado en aluminio resistente y ligero, cuenta con una empuñadura de PVC ergonómica que garantiza un agarre cómodo y seguro. Con una altura ajustable entre 70 cm y 93 cm, este bastón se adapta a diferentes estaturas, proporcionando estabilidad y soporte en cada paso.

El bastón con empuñadura en T ergonómico Konfort Plus (negro) está fabricado en aluminio, es seguro, ligero y resistente, y cuenta con sistema de graduación de altura de ajuste firme, empuñadura ergonómica de elegante diseño y acabados de alta calidad. Según la ficha del fabricante soporta hasta 125 kg y se ajusta entre 70 y 93 cm.$d$,
  descripcion_larga_en = $d$The Konfort Plus Ergonomic T-Handle Walking Stick is designed to provide stylish and comfortable support for individuals requiring walking assistance. Constructed from lightweight yet durable aluminum, it features an ergonomic PVC handle that ensures a comfortable and secure grip. With an adjustable height range of 70 cm to 93 cm, the cane adapts to different statures, providing stability and support with each step.

The Konfort Plus ergonomic T-handle walking stick (black) is made of aluminium, is safe, light and sturdy, and features a firm-locking height adjustment system, an elegantly designed ergonomic handle and high-quality finishes. According to the manufacturer datasheet it supports up to 125 kg and adjusts between 70 and 93 cm.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4102-20"},{"clave":"Color","grupo":"Variante","valor":"Negro"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"70 - 93 cm"},{"clave":"Material","grupo":"Material","valor":"Aluminio; empuñadura PVC"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Aluminio ligero y resistente con capacidad de hasta 125 kg.","Altura graduable de 70 a 93 cm con ajuste firme.","Empuñadura ergonómica en T y acabado negro."],"beneficios_en":["Light, sturdy aluminium with capacity up to 125 kg.","Height adjustable from 70 to 93 cm with firm locking.","Ergonomic T handle and black finish."],"valor_es":"Un bastón de aluminio con empuñadura en T y altura graduable, con ficha técnica oficial de Konfort Plus.","valor_en":"An aluminium walking stick with T handle and adjustable height, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué peso soporta?","a":"Hasta 125 kg, según la ficha."},{"q":"¿Qué altura alcanza?","a":"Se gradúa entre 70 y 93 cm."},{"q":"¿Qué colores existen?","a":"Negro, cromo, madera nogal y bronce."},{"q":"¿Dónde descargo la ficha técnica de Baston Con Empuñadura En T Ergonómico Color Negro Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What weight does it support?","a":"Up to 125 kg, per the datasheet."},{"q":"What height does it reach?","a":"Adjustable between 70 and 93 cm."},{"q":"Which colours are available?","a":"Black, chrome, walnut wood and bronze."},{"q":"Where can I download the Konfort Plus Ergonomic T-Handle Walking Stick Black datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón con empuñadura en T negro","bastón de aluminio ergonómico","bastón para caminar graduable","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4102-20"],"seo_keywords_en":["T-handle walking stick black","ergonomic aluminium cane","adjustable walking cane","Konfort Plus cane","orthopaedic cane Colombia","KP4102-20 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCI3DXPM6KQNC3TPU7V3SDTYLOW4?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-con-empunadura-en-t-ergonomico-color-negro-ref-kp4102-20-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4102-24-ft.pdf',
  descripcion_larga_es = $d$El Bastón con Empuñadura en T Ergonómico Konfort Plus está diseñado para proporcionar un apoyo elegante y cómodo para quienes necesitan asistencia al caminar. Fabricado en aluminio resistente y ligero, cuenta con una empuñadura de PVC ergonómica que garantiza un agarre cómodo y seguro. Con una altura ajustable entre 70 cm y 93 cm, este bastón se adapta a diferentes estaturas, proporcionando estabilidad y soporte en cada paso.

El bastón con empuñadura en T ergonómico Konfort Plus (madera nogal) está fabricado en aluminio, es seguro, ligero y resistente, y cuenta con sistema de graduación de altura de ajuste firme, empuñadura ergonómica de elegante diseño y acabados de alta calidad. Según la ficha del fabricante soporta hasta 125 kg y se ajusta entre 70 y 93 cm.$d$,
  descripcion_larga_en = $d$Lightweight and resistant aluminum cane with ergonomic PVC T-shaped grip. Adjustable height between 70 cm and 93 cm, adaptable to different statures. Designed to provide support and stability in walking for elderly adults and rehabilitation patients.

The Konfort Plus ergonomic T-handle walking stick (walnut wood) is made of aluminium, is safe, light and sturdy, and features a firm-locking height adjustment system, an elegantly designed ergonomic handle and high-quality finishes. According to the manufacturer datasheet it supports up to 125 kg and adjusts between 70 and 93 cm.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4102-24"},{"clave":"Color","grupo":"Variante","valor":"Madera nogal"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"70 - 93 cm"},{"clave":"Material","grupo":"Material","valor":"Aluminio; empuñadura PVC"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Aluminio ligero y resistente con capacidad de hasta 125 kg.","Altura graduable de 70 a 93 cm con ajuste firme.","Empuñadura ergonómica en T y acabado madera nogal."],"beneficios_en":["Light, sturdy aluminium with capacity up to 125 kg.","Height adjustable from 70 to 93 cm with firm locking.","Ergonomic T handle and walnut wood finish."],"valor_es":"Un bastón de aluminio con empuñadura en T y altura graduable, con ficha técnica oficial de Konfort Plus.","valor_en":"An aluminium walking stick with T handle and adjustable height, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué peso soporta?","a":"Hasta 125 kg, según la ficha."},{"q":"¿Qué altura alcanza?","a":"Se gradúa entre 70 y 93 cm."},{"q":"¿Qué colores existen?","a":"Negro, cromo, madera nogal y bronce."},{"q":"¿Dónde descargo la ficha técnica de Baston Con Empuñadura En T Ergonómico Color Madera Nogal Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What weight does it support?","a":"Up to 125 kg, per the datasheet."},{"q":"What height does it reach?","a":"Adjustable between 70 and 93 cm."},{"q":"Which colours are available?","a":"Black, chrome, walnut wood and bronze."},{"q":"Where can I download the Walking Cane with Ergonomic T-Shaped Grip, Walnut Wood Color, Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón con empuñadura en T madera nogal","bastón de aluminio ergonómico","bastón para caminar graduable","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4102-24"],"seo_keywords_en":["T-handle walking stick walnut wood","ergonomic aluminium cane","adjustable walking cane","Konfort Plus cane","orthopaedic cane Colombia","KP4102-24 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCAIDL7OH6UVCEVPZDT5JD32SRHI?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-con-empunadura-en-t-ergonomico-color-madera-nogal-ref-kp4102-24-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4102-28-ft.pdf',
  descripcion_larga_es = $d$El Bastón con Empuñadura en T Ergonómico Konfort Plus está diseñado para proporcionar un apoyo elegante y cómodo para quienes necesitan asistencia al caminar. Fabricado en aluminio resistente y ligero, cuenta con una empuñadura de PVC ergonómica que garantiza un agarre cómodo y seguro. Con una altura ajustable entre 70 cm y 93 cm, este bastón se adapta a diferentes estaturas, proporcionando estabilidad y soporte en cada paso.

El bastón con empuñadura en T ergonómico Konfort Plus (bronce) está fabricado en aluminio, es seguro, ligero y resistente, y cuenta con sistema de graduación de altura de ajuste firme, empuñadura ergonómica de elegante diseño y acabados de alta calidad. Según la ficha del fabricante soporta hasta 125 kg y se ajusta entre 70 y 93 cm.$d$,
  descripcion_larga_en = $d$The Ergonomic T-Shaped Grip Cane Konfort Plus is designed to provide elegant, comfortable support for those needing walking assistance. Made from durable, lightweight aluminum, it features an ergonomic PVC handle that ensures comfortable, secure grip. With adjustable height between 70 cm and 93 cm, this cane adapts to different statures, providing stability and support with each step.

The Konfort Plus ergonomic T-handle walking stick (bronze) is made of aluminium, is safe, light and sturdy, and features a firm-locking height adjustment system, an elegantly designed ergonomic handle and high-quality finishes. According to the manufacturer datasheet it supports up to 125 kg and adjusts between 70 and 93 cm.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4102-28"},{"clave":"Color","grupo":"Variante","valor":"Bronce"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"70 - 93 cm"},{"clave":"Material","grupo":"Material","valor":"Aluminio; empuñadura PVC"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Aluminio ligero y resistente con capacidad de hasta 125 kg.","Altura graduable de 70 a 93 cm con ajuste firme.","Empuñadura ergonómica en T y acabado bronce."],"beneficios_en":["Light, sturdy aluminium with capacity up to 125 kg.","Height adjustable from 70 to 93 cm with firm locking.","Ergonomic T handle and bronze finish."],"valor_es":"Un bastón de aluminio con empuñadura en T y altura graduable, con ficha técnica oficial de Konfort Plus.","valor_en":"An aluminium walking stick with T handle and adjustable height, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué peso soporta?","a":"Hasta 125 kg, según la ficha."},{"q":"¿Qué altura alcanza?","a":"Se gradúa entre 70 y 93 cm."},{"q":"¿Qué colores existen?","a":"Negro, cromo, madera nogal y bronce."},{"q":"¿Dónde descargo la ficha técnica de Baston Con Empuñadura En T Ergonómico Color Bronce Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What weight does it support?","a":"Up to 125 kg, per the datasheet."},{"q":"What height does it reach?","a":"Adjustable between 70 and 93 cm."},{"q":"Which colours are available?","a":"Black, chrome, walnut wood and bronze."},{"q":"Where can I download the Ergonomic T-Shaped Grip Cane Bronze Color Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón con empuñadura en T bronce","bastón de aluminio ergonómico","bastón para caminar graduable","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4102-28"],"seo_keywords_en":["T-handle walking stick bronze","ergonomic aluminium cane","adjustable walking cane","Konfort Plus cane","orthopaedic cane Colombia","KP4102-28 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MC7JOO53F6P5BIFG7XIVCGOPDVD4?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-con-empunadura-en-t-ergonomico-color-bronce-ref-kp4102-28-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4202-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón Cuatro Apoyos Konfort Plus ofrece estabilidad y firmeza gracias a su base pequeña de cuatro puntos y su empuñadura de cuello en cisne, brindando un apoyo seguro a personas con movilidad reducida. Fabricado en aluminio resistente con una base en acero cromado, este bastón combina ligereza y durabilidad. Su altura es fácilmente ajustable por medio de un botón de pin, lo que permite adaptarse a diferentes estaturas.

El bastón de 4 apoyos con base pequeña Konfort Plus (negro) ofrece gran estabilidad y resistencia gracias a sus cuatro apoyos, con sistema de graduación de altura de ajuste firme, base en acero cromado y acabados de alta calidad. La empuñadura es de PVC. La ficha del fabricante indica capacidad de 125 kg y altura entre 72,5 y 95 cm.$d$,
  descripcion_larga_en = $d$The Konfort Plus Four-Prong Walking Stick provides stability and firmness through its small four-point base and swan-neck handle, offering secure support for individuals with reduced mobility. Made from durable aluminum with a chromed steel base, this cane combines lightweight construction with long-term durability. Its height is easily adjustable via a pin button, allowing adaptation to different statures.

The Konfort Plus small-base 4-point cane (black) offers great stability and strength thanks to its four supports, with a firm-locking height adjustment system, chrome-steel base and high-quality finishes. The handle is PVC. The manufacturer datasheet states 125 kg capacity and a height between 72.5 and 95 cm.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4202-20"},{"clave":"Color","grupo":"Variante","valor":"Negro"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"72,5 - 95 cm"},{"clave":"Base","grupo":"Material","valor":"Acero cromado"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Cuatro apoyos para mayor estabilidad al caminar.","Base en acero cromado y altura graduable de 72,5 a 95 cm.","Capacidad de hasta 125 kg y empuñadura de PVC."],"beneficios_en":["Four supports for greater stability when walking.","Chrome-steel base and height adjustable from 72.5 to 95 cm.","Capacity up to 125 kg and PVC handle."],"valor_es":"Un bastón de cuatro apoyos para mayor estabilidad, con ficha técnica oficial de Konfort Plus (ficha de la variante cromo de la misma referencia base).","valor_en":"A four-point cane for greater stability, with official Konfort Plus datasheet (datasheet of the chrome variant of the same base model).","preguntas_frecuentes_es":[{"q":"¿Qué ventaja tiene frente a un bastón simple?","a":"Sus cuatro apoyos brindan mayor estabilidad, según el fabricante."},{"q":"¿Qué peso soporta?","a":"Hasta 125 kg."},{"q":"¿Qué altura permite?","a":"Entre 72,5 y 95 cm."},{"q":"¿Dónde descargo la ficha técnica de Bastón 4 Apoyos Base Pequeña Color Negro Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What advantage does it have over a simple cane?","a":"Its four supports provide greater stability, per the manufacturer."},{"q":"What weight does it support?","a":"Up to 125 kg."},{"q":"What height does it allow?","a":"Between 72.5 and 95 cm."},{"q":"Where can I download the Konfort Plus Four-Prong Small Base Walking Stick Black datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón de 4 apoyos negro","bastón cuatro apoyos base pequeña","bastón de apoyo estable","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4202-20"],"seo_keywords_en":["4-point cane black","small base quad cane","stable support cane","Konfort Plus cane","orthopaedic cane Colombia","KP4202-20 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCII6BK6SHAVBKVDRNCZBYNGN7KE?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-4-apoyos-base-pequena-color-negro-ref-kp4202-20-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4202-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón Cuatro Apoyos Konfort Plus ofrece estabilidad y firmeza gracias a su base pequeña de cuatro puntos y su empuñadura de cuello en cisne, brindando un apoyo seguro a personas con movilidad reducida. Fabricado en aluminio resistente con una base en acero cromado, este bastón combina ligereza y durabilidad. Su altura es fácilmente ajustable por medio de un botón de pin, lo que permite adaptarse a diferentes estaturas.

El bastón de 4 apoyos con base pequeña Konfort Plus (bronce) ofrece gran estabilidad y resistencia gracias a sus cuatro apoyos, con sistema de graduación de altura de ajuste firme, base en acero cromado y acabados de alta calidad. La empuñadura es de PVC. La ficha del fabricante indica capacidad de 125 kg y altura entre 72,5 y 95 cm.$d$,
  descripcion_larga_en = $d$The Konfort Plus Four-Prong Walking Stick provides stability and firmness through its small four-point base and swan-neck handle, offering secure support for individuals with reduced mobility. Made from durable aluminum with a chromed steel base, this cane combines lightweight construction with long-term durability. Its height is easily adjustable via a pin button, allowing adaptation to different statures.

The Konfort Plus small-base 4-point cane (bronze) offers great stability and strength thanks to its four supports, with a firm-locking height adjustment system, chrome-steel base and high-quality finishes. The handle is PVC. The manufacturer datasheet states 125 kg capacity and a height between 72.5 and 95 cm.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4202-28"},{"clave":"Color","grupo":"Variante","valor":"Bronce"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"72,5 - 95 cm"},{"clave":"Base","grupo":"Material","valor":"Acero cromado"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Cuatro apoyos para mayor estabilidad al caminar.","Base en acero cromado y altura graduable de 72,5 a 95 cm.","Capacidad de hasta 125 kg y empuñadura de PVC."],"beneficios_en":["Four supports for greater stability when walking.","Chrome-steel base and height adjustable from 72.5 to 95 cm.","Capacity up to 125 kg and PVC handle."],"valor_es":"Un bastón de cuatro apoyos para mayor estabilidad, con ficha técnica oficial de Konfort Plus (ficha de la variante cromo de la misma referencia base).","valor_en":"A four-point cane for greater stability, with official Konfort Plus datasheet (datasheet of the chrome variant of the same base model).","preguntas_frecuentes_es":[{"q":"¿Qué ventaja tiene frente a un bastón simple?","a":"Sus cuatro apoyos brindan mayor estabilidad, según el fabricante."},{"q":"¿Qué peso soporta?","a":"Hasta 125 kg."},{"q":"¿Qué altura permite?","a":"Entre 72,5 y 95 cm."},{"q":"¿Dónde descargo la ficha técnica de Bastón 4 Apoyos Base Pequeña Color Bronce Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What advantage does it have over a simple cane?","a":"Its four supports provide greater stability, per the manufacturer."},{"q":"What weight does it support?","a":"Up to 125 kg."},{"q":"What height does it allow?","a":"Between 72.5 and 95 cm."},{"q":"Where can I download the Konfort Plus Four-Prong Small Base Walking Stick Bronze datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón de 4 apoyos bronce","bastón cuatro apoyos base pequeña","bastón de apoyo estable","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4202-28"],"seo_keywords_en":["4-point cane bronze","small base quad cane","stable support cane","Konfort Plus cane","orthopaedic cane Colombia","KP4202-28 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCII6BK6SHAVBKVDRNCZBYNGN7KE?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-4-apoyos-base-pequena-color-bronce-ref-kp4202-28-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4152-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón Cuello de Cisne Konfort Plus está diseñado para proporcionar un apoyo seguro y ergonómico, ideal para quienes requieren asistencia en su movilidad diaria. Fabricado en aluminio resistente y ligero, cuenta con una empuñadura ergonómica de espuma y un sistema de graduación de altura ajustable desde 77 cm hasta 100 cm, lo que lo hace adecuado para usuarios de diferentes estaturas. Su diseño de cuello de cisne distribuye mejor el peso del usuario, proporcionando mayor estabilidad.

El bastón cuello de cisne con correa de seguridad Konfort Plus (negro) es de aluminio, seguro, ligero y resistente, con graduación de altura de ajuste firme y empuñadura de PVC de fácil limpieza y larga duración. Su correa de seguridad evita que se caiga y su diseño elegante conserva acabados de alta calidad; la ficha indica capacidad de 125 kg.$d$,
  descripcion_larga_en = $d$The Swan-Neck Cane Konfort Plus is designed to provide safe, ergonomic support, ideal for those requiring assistance in daily mobility. Made from durable, lightweight aluminum, it features an ergonomic foam handle and an adjustable height graduation system from 77 cm to 100 cm, making it suitable for users of different statures. Its swan-neck design better distributes the user's weight, providing greater stability.

The Konfort Plus swan-neck cane with safety strap (black) is aluminium, safe, light and sturdy, with firm-locking height adjustment and an easy-to-clean, long-lasting PVC handle. Its safety strap keeps it from dropping and its elegant design keeps high-quality finishes; the datasheet states a 125 kg capacity.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4152-20"},{"clave":"Color","grupo":"Variante","valor":"Negro"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Material","grupo":"Material","valor":"Aluminio; empuñadura PVC"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Cuello de cisne con correa de seguridad para no soltarlo.","Aluminio ligero y resistente con capacidad de 125 kg.","Empuñadura PVC de fácil limpieza y altura graduable."],"beneficios_en":["Swan-neck with safety strap to keep hold of it.","Light, sturdy aluminium with 125 kg capacity.","Easy-clean PVC handle and adjustable height."],"valor_es":"Un bastón cuello de cisne con correa de seguridad, con ficha oficial de Konfort Plus (ficha compartida con los colores de la misma referencia).","valor_en":"A swan-neck cane with safety strap, with official Konfort Plus datasheet (shared across the colours of the same model).","preguntas_frecuentes_es":[{"q":"¿Qué incluye de seguridad?","a":"Una correa de seguridad en la empuñadura."},{"q":"¿Qué peso soporta?","a":"125 kg."},{"q":"¿De qué es la empuñadura?","a":"De PVC, de fácil limpieza y larga duración."},{"q":"¿Dónde descargo la ficha técnica de Bastón Cuello De Cisne Y Correa De Seguridad Color Negro Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What safety feature does it include?","a":"A safety strap on the handle."},{"q":"What weight does it support?","a":"125 kg."},{"q":"What is the handle made of?","a":"PVC, easy to clean and long-lasting."},{"q":"Where can I download the Swan-Neck Cane with Safety Strap Black Color Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón cuello de cisne negro","bastón con correa de seguridad","bastón de aluminio","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4152-20"],"seo_keywords_en":["swan-neck cane black","cane with safety strap","aluminium cane","Konfort Plus cane","orthopaedic cane Colombia","KP4152-20 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCFH732SK5VNCGDDHNRFRBNH4264?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-cuello-de-cisne-y-correa-de-seguridad-color-negro-ref-kp4152-20-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4152-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón Cuello de Cisne Konfort Plus está diseñado para proporcionar un apoyo seguro y ergonómico, ideal para quienes requieren asistencia en su movilidad diaria. Fabricado en aluminio resistente y ligero, cuenta con una empuñadura ergonómica de espuma y un sistema de graduación de altura ajustable desde 77 cm hasta 100 cm, lo que lo hace adecuado para usuarios de diferentes estaturas. Su diseño de cuello de cisne distribuye mejor el peso del usuario, proporcionando mayor estabilidad.

El bastón cuello de cisne con correa de seguridad Konfort Plus (bronce) es de aluminio, seguro, ligero y resistente, con graduación de altura de ajuste firme y empuñadura de PVC de fácil limpieza y larga duración. Su correa de seguridad evita que se caiga y su diseño elegante conserva acabados de alta calidad; la ficha indica capacidad de 125 kg.$d$,
  descripcion_larga_en = $d$The Swan-Neck Cane Konfort Plus is designed to provide safe, ergonomic support, ideal for those requiring assistance in daily mobility. Made from durable, lightweight aluminum, it features an ergonomic foam handle and an adjustable height graduation system from 77 cm to 100 cm, making it suitable for users of different statures. Its swan-neck design better distributes the user's weight, providing greater stability.

The Konfort Plus swan-neck cane with safety strap (bronze) is aluminium, safe, light and sturdy, with firm-locking height adjustment and an easy-to-clean, long-lasting PVC handle. Its safety strap keeps it from dropping and its elegant design keeps high-quality finishes; the datasheet states a 125 kg capacity.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4152-28"},{"clave":"Color","grupo":"Variante","valor":"Bronce"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Material","grupo":"Material","valor":"Aluminio; empuñadura PVC"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Cuello de cisne con correa de seguridad para no soltarlo.","Aluminio ligero y resistente con capacidad de 125 kg.","Empuñadura PVC de fácil limpieza y altura graduable."],"beneficios_en":["Swan-neck with safety strap to keep hold of it.","Light, sturdy aluminium with 125 kg capacity.","Easy-clean PVC handle and adjustable height."],"valor_es":"Un bastón cuello de cisne con correa de seguridad, con ficha oficial de Konfort Plus (ficha compartida con los colores de la misma referencia).","valor_en":"A swan-neck cane with safety strap, with official Konfort Plus datasheet (shared across the colours of the same model).","preguntas_frecuentes_es":[{"q":"¿Qué incluye de seguridad?","a":"Una correa de seguridad en la empuñadura."},{"q":"¿Qué peso soporta?","a":"125 kg."},{"q":"¿De qué es la empuñadura?","a":"De PVC, de fácil limpieza y larga duración."},{"q":"¿Dónde descargo la ficha técnica de Bastón Cuello De Cisne Y Correa De Seguridad Color Bronce Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What safety feature does it include?","a":"A safety strap on the handle."},{"q":"What weight does it support?","a":"125 kg."},{"q":"What is the handle made of?","a":"PVC, easy to clean and long-lasting."},{"q":"Where can I download the Swan-Neck Cane with Safety Strap Bronze Color Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón cuello de cisne bronce","bastón con correa de seguridad","bastón de aluminio","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4152-28"],"seo_keywords_en":["swan-neck cane bronze","cane with safety strap","aluminium cane","Konfort Plus cane","orthopaedic cane Colombia","KP4152-28 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCFH732SK5VNCGDDHNRFRBNH4264?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-cuello-de-cisne-y-correa-de-seguridad-color-bronce-ref-kp4152-28-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4192-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón Tipo Paraguas Konfort Plus está diseñado para proporcionar un apoyo seguro y resistente a las personas que requieren asistencia en su movilidad diaria. Fabricado en aluminio ligero, este bastón cuenta con un sistema de graduación de altura ajustable que permite adaptarse a diferentes estaturas, brindando un ajuste firme y preciso. Su empuñadura ergonómica de espuma, junto con su diseño elegante y acabados de alta calidad, garantiza comodidad y estilo en cada uso.

El bastón tipo paraguas Konfort Plus (negro) es de aluminio, ligero, seguro y resistente, con sistema de graduación de altura de ajuste firme, empuñadura ergonómica de elegante diseño y acabados de alta calidad. Según la ficha soporta 125 kg y se ajusta entre 76 y 99 cm; la empuñadura es de espuma.$d$,
  descripcion_larga_en = $d$The Umbrella-Type Cane Konfort Plus is designed to provide secure and sturdy support for people requiring assistance in their daily mobility. Made from lightweight aluminum, this cane includes an adjustable height graduation system to adapt to different statures, providing firm and precise adjustment. Its ergonomic foam handle, combined with an elegant design and high-quality finishes, ensures comfort and style with each use.

The Konfort Plus umbrella-type cane (black) is aluminium, light, safe and sturdy, with firm-locking height adjustment, an elegantly designed ergonomic handle and high-quality finishes. Per the datasheet it supports 125 kg and adjusts between 76 and 99 cm; the handle is foam.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4192-20"},{"clave":"Color","grupo":"Variante","valor":"Negro"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"76 - 99 cm"},{"clave":"Material","grupo":"Material","valor":"Aluminio; empuñadura de espuma"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Empuñadura tipo paraguas de espuma, ergonómica y cómoda.","Altura graduable de 76 a 99 cm.","Aluminio ligero con capacidad de 125 kg."],"beneficios_en":["Comfortable ergonomic foam umbrella-type handle.","Height adjustable from 76 to 99 cm.","Light aluminium with 125 kg capacity."],"valor_es":"Un bastón tipo paraguas ligero y graduable, con ficha oficial de Konfort Plus.","valor_en":"A light, adjustable umbrella-type cane, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué altura tiene?","a":"Entre 76 y 99 cm."},{"q":"¿Qué peso soporta?","a":"125 kg."},{"q":"¿De qué es la empuñadura?","a":"De espuma."},{"q":"¿Dónde descargo la ficha técnica de Bastón Tipo Paraguas Color Negro Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What height does it have?","a":"Between 76 and 99 cm."},{"q":"What weight does it support?","a":"125 kg."},{"q":"What is the handle made of?","a":"Foam."},{"q":"Where can I download the Umbrella-Type Cane Black Color Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón tipo paraguas negro","bastón de aluminio graduable","bastón con empuñadura de espuma","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4192-20"],"seo_keywords_en":["umbrella-type cane black","adjustable aluminium cane","foam-handle cane","Konfort Plus cane","orthopaedic cane Colombia","KP4192-20 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCLQ2JGV6C6RHSXGVA6LHX2HUOUY?version=4.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-tipo-paraguas-color-negro-ref-kp4192-20-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4192-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón Tipo Paraguas Konfort Plus está diseñado para proporcionar un apoyo seguro y resistente a las personas que requieren asistencia en su movilidad diaria. Fabricado en aluminio ligero, este bastón cuenta con un sistema de graduación de altura ajustable que permite adaptarse a diferentes estaturas, brindando un ajuste firme y preciso. Su empuñadura ergonómica de espuma, junto con su diseño elegante y acabados de alta calidad, garantiza comodidad y estilo en cada uso.

El bastón tipo paraguas Konfort Plus (bronce) es de aluminio, ligero, seguro y resistente, con sistema de graduación de altura de ajuste firme, empuñadura ergonómica de elegante diseño y acabados de alta calidad. Según la ficha soporta 125 kg y se ajusta entre 76 y 99 cm; la empuñadura es de espuma.$d$,
  descripcion_larga_en = $d$The Umbrella-Type Cane Konfort Plus is designed to provide secure and sturdy support for people requiring assistance in their daily mobility. Made from lightweight aluminum, this cane includes an adjustable height graduation system to adapt to different statures, providing firm and precise adjustment. Its ergonomic foam handle, combined with an elegant design and high-quality finishes, ensures comfort and style with each use.

The Konfort Plus umbrella-type cane (bronze) is aluminium, light, safe and sturdy, with firm-locking height adjustment, an elegantly designed ergonomic handle and high-quality finishes. Per the datasheet it supports 125 kg and adjusts between 76 and 99 cm; the handle is foam.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4192-28"},{"clave":"Color","grupo":"Variante","valor":"Bronce"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"76 - 99 cm"},{"clave":"Material","grupo":"Material","valor":"Aluminio; empuñadura de espuma"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Empuñadura tipo paraguas de espuma, ergonómica y cómoda.","Altura graduable de 76 a 99 cm.","Aluminio ligero con capacidad de 125 kg."],"beneficios_en":["Comfortable ergonomic foam umbrella-type handle.","Height adjustable from 76 to 99 cm.","Light aluminium with 125 kg capacity."],"valor_es":"Un bastón tipo paraguas ligero y graduable, con ficha oficial de Konfort Plus.","valor_en":"A light, adjustable umbrella-type cane, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué altura tiene?","a":"Entre 76 y 99 cm."},{"q":"¿Qué peso soporta?","a":"125 kg."},{"q":"¿De qué es la empuñadura?","a":"De espuma."},{"q":"¿Dónde descargo la ficha técnica de Bastón Tipo Paraguas Color Bronce Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What height does it have?","a":"Between 76 and 99 cm."},{"q":"What weight does it support?","a":"125 kg."},{"q":"What is the handle made of?","a":"Foam."},{"q":"Where can I download the Umbrella-Type Cane Bronze Color Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón tipo paraguas bronce","bastón de aluminio graduable","bastón con empuñadura de espuma","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4192-28"],"seo_keywords_en":["umbrella-type cane bronze","adjustable aluminium cane","foam-handle cane","Konfort Plus cane","orthopaedic cane Colombia","KP4192-28 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCLQ2JGV6C6RHSXGVA6LHX2HUOUY?version=4.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-tipo-paraguas-color-bronce-ref-kp4192-28-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4-76085-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón Plegable con Empuñadura en T Konfort Plus está diseñado para ofrecer un apoyo seguro y estable a las personas con movilidad reducida. Fabricado en aluminio resistente y ligero, este bastón cuenta con un sistema plegable que lo hace fácil de almacenar y transportar. Su empuñadura ergonómica en PVC garantiza un agarre cómodo, mientras que su sistema de graduación de altura permite ajustar el bastón de manera firme y precisa para adaptarse a diferentes estaturas.

El bastón plegable con empuñadura en T Konfort Plus (negro) se guarda fácilmente gracias a su sistema plegable y está fabricado en aluminio, seguro, ligero y resistente. Tiene graduación de altura de ajuste firme, empuñadura ergonómica de PVC y acabados de alta calidad. La ficha indica capacidad de 125 kg y altura entre 81 y 91 cm.$d$,
  descripcion_larga_en = $d$The Folding Cane with T-Shaped Grip Konfort Plus is designed to provide safe and stable support for people with reduced mobility. Constructed from durable, lightweight aluminum, this cane features a folding system that facilitates storage and transport. Its ergonomic PVC handle ensures comfortable grip, while the height adjustment system allows firm and precise adjustment to accommodate different statures.

The Konfort Plus folding T-handle cane (black) stores easily thanks to its folding system and is made of aluminium, safe, light and sturdy. It has firm-locking height adjustment, an ergonomic PVC handle and high-quality finishes. The datasheet states a 125 kg capacity and a height between 81 and 91 cm.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4-76085-20"},{"clave":"Color","grupo":"Variante","valor":"Negro"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"81 - 91 cm"},{"clave":"Material","grupo":"Material","valor":"Aluminio; empuñadura PVC"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Plegable: cabe en bolso o maleta y se guarda sin esfuerzo.","Altura de 81 a 91 cm y capacidad de 125 kg.","Aluminio ligero con empuñadura ergonómica de PVC."],"beneficios_en":["Folding: fits in a bag or suitcase and stores easily.","Height from 81 to 91 cm and 125 kg capacity.","Light aluminium with ergonomic PVC handle."],"valor_es":"Un bastón plegable de aluminio para llevar a cualquier parte, con ficha oficial de Konfort Plus.","valor_en":"A folding aluminium cane to take anywhere, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Se pliega?","a":"Sí, tiene sistema plegable para guardarlo fácilmente."},{"q":"¿Qué peso soporta?","a":"125 kg."},{"q":"¿Qué altura tiene?","a":"Entre 81 y 91 cm."},{"q":"¿Dónde descargo la ficha técnica de Baston Plegable Con Empuñadura En T Color Negro Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Does it fold?","a":"Yes, it has a folding system for easy storage."},{"q":"What weight does it support?","a":"125 kg."},{"q":"What height does it have?","a":"Between 81 and 91 cm."},{"q":"Where can I download the Folding Cane with T-Shaped Grip Black Color Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón plegable negro","bastón plegable con empuñadura en T","bastón de viaje plegable","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4-76085-20"],"seo_keywords_en":["folding cane black","folding T-handle cane","folding travel cane","Konfort Plus cane","orthopaedic cane Colombia","KP4-76085-20 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCVH66724RXZENHNRFP74HAHJPNA?version=2.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-plegable-con-empunadura-en-t-color-negro-ref-kp4-76085-20-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4-76085-22-ft.pdf',
  descripcion_larga_es = $d$El Bastón Plegable con Empuñadura en T Konfort Plus está diseñado para ofrecer un apoyo seguro y estable a las personas con movilidad reducida. Fabricado en aluminio resistente y ligero, este bastón cuenta con un sistema plegable que lo hace fácil de almacenar y transportar. Su empuñadura ergonómica en PVC garantiza un agarre cómodo, mientras que su sistema de graduación de altura permite ajustar el bastón de manera firme y precisa para adaptarse a diferentes estaturas.

El bastón plegable con empuñadura en T Konfort Plus (cromo) se guarda fácilmente gracias a su sistema plegable y está fabricado en aluminio, seguro, ligero y resistente. Tiene graduación de altura de ajuste firme, empuñadura ergonómica de PVC y acabados de alta calidad. La ficha indica capacidad de 125 kg y altura entre 81 y 91 cm.$d$,
  descripcion_larga_en = $d$The Folding Cane with T-Shaped Grip Konfort Plus is designed to provide safe and stable support for people with reduced mobility. Constructed from durable, lightweight aluminum, this cane features a folding system that facilitates storage and transport. Its ergonomic PVC handle ensures comfortable grip, while the height adjustment system allows firm and precise adjustment to accommodate different statures.

The Konfort Plus folding T-handle cane (chrome) stores easily thanks to its folding system and is made of aluminium, safe, light and sturdy. It has firm-locking height adjustment, an ergonomic PVC handle and high-quality finishes. The datasheet states a 125 kg capacity and a height between 81 and 91 cm.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4-76085-22"},{"clave":"Color","grupo":"Variante","valor":"Cromo"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"81 - 91 cm"},{"clave":"Material","grupo":"Material","valor":"Aluminio; empuñadura PVC"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Plegable: cabe en bolso o maleta y se guarda sin esfuerzo.","Altura de 81 a 91 cm y capacidad de 125 kg.","Aluminio ligero con empuñadura ergonómica de PVC."],"beneficios_en":["Folding: fits in a bag or suitcase and stores easily.","Height from 81 to 91 cm and 125 kg capacity.","Light aluminium with ergonomic PVC handle."],"valor_es":"Un bastón plegable de aluminio para llevar a cualquier parte, con ficha oficial de Konfort Plus.","valor_en":"A folding aluminium cane to take anywhere, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Se pliega?","a":"Sí, tiene sistema plegable para guardarlo fácilmente."},{"q":"¿Qué peso soporta?","a":"125 kg."},{"q":"¿Qué altura tiene?","a":"Entre 81 y 91 cm."},{"q":"¿Dónde descargo la ficha técnica de Baston Plegable Con Empuñadura En T Color Cromo Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Does it fold?","a":"Yes, it has a folding system for easy storage."},{"q":"What weight does it support?","a":"125 kg."},{"q":"What height does it have?","a":"Between 81 and 91 cm."},{"q":"Where can I download the Folding Cane with T-Shaped Grip Chrome Color Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón plegable cromo","bastón plegable con empuñadura en T","bastón de viaje plegable","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4-76085-22"],"seo_keywords_en":["folding cane chrome","folding T-handle cane","folding travel cane","Konfort Plus cane","orthopaedic cane Colombia","KP4-76085-22 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCROSA3DPMHBGRBI23UOHVIKQU4Y?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-plegable-con-empunadura-en-t-color-cromo-ref-kp4-76085-22-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4-76085-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón Plegable con Empuñadura en T Konfort Plus está diseñado para ofrecer un apoyo seguro y estable a las personas con movilidad reducida. Fabricado en aluminio resistente y ligero, este bastón cuenta con un sistema plegable que lo hace fácil de almacenar y transportar. Su empuñadura ergonómica en PVC garantiza un agarre cómodo, mientras que su sistema de graduación de altura permite ajustar el bastón de manera firme y precisa para adaptarse a diferentes estaturas.

El bastón plegable con empuñadura en T Konfort Plus (bronce) se guarda fácilmente gracias a su sistema plegable y está fabricado en aluminio, seguro, ligero y resistente. Tiene graduación de altura de ajuste firme, empuñadura ergonómica de PVC y acabados de alta calidad. La ficha indica capacidad de 125 kg y altura entre 81 y 91 cm.$d$,
  descripcion_larga_en = $d$The Folding Cane with T-Shaped Grip Konfort Plus is designed to provide safe and stable support for people with reduced mobility. Constructed from durable, lightweight aluminum, this cane features a folding system that facilitates storage and transport. Its ergonomic PVC handle ensures comfortable grip, while the height adjustment system allows firm and precise adjustment to accommodate different statures.

The Konfort Plus folding T-handle cane (bronze) stores easily thanks to its folding system and is made of aluminium, safe, light and sturdy. It has firm-locking height adjustment, an ergonomic PVC handle and high-quality finishes. The datasheet states a 125 kg capacity and a height between 81 and 91 cm.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4-76085-28"},{"clave":"Color","grupo":"Variante","valor":"Bronce"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"81 - 91 cm"},{"clave":"Material","grupo":"Material","valor":"Aluminio; empuñadura PVC"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Plegable: cabe en bolso o maleta y se guarda sin esfuerzo.","Altura de 81 a 91 cm y capacidad de 125 kg.","Aluminio ligero con empuñadura ergonómica de PVC."],"beneficios_en":["Folding: fits in a bag or suitcase and stores easily.","Height from 81 to 91 cm and 125 kg capacity.","Light aluminium with ergonomic PVC handle."],"valor_es":"Un bastón plegable de aluminio para llevar a cualquier parte, con ficha oficial de Konfort Plus.","valor_en":"A folding aluminium cane to take anywhere, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Se pliega?","a":"Sí, tiene sistema plegable para guardarlo fácilmente."},{"q":"¿Qué peso soporta?","a":"125 kg."},{"q":"¿Qué altura tiene?","a":"Entre 81 y 91 cm."},{"q":"¿Dónde descargo la ficha técnica de Baston Plegable Con Empuñadura En T Color Bronce Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Does it fold?","a":"Yes, it has a folding system for easy storage."},{"q":"What weight does it support?","a":"125 kg."},{"q":"What height does it have?","a":"Between 81 and 91 cm."},{"q":"Where can I download the Folding Cane with T-Shaped Grip Bronze Color Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón plegable bronce","bastón plegable con empuñadura en T","bastón de viaje plegable","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4-76085-28"],"seo_keywords_en":["folding cane bronze","folding T-handle cane","folding travel cane","Konfort Plus cane","orthopaedic cane Colombia","KP4-76085-28 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCDRM4WL4MGVCRHGVP6EGZIQ4XTM?version=2.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-plegable-con-empunadura-en-t-color-bronce-ref-kp4-76085-28-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4-832l6-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón para Invidente Plegable Konfort Plus es una herramienta esencial para proporcionar seguridad y orientación a personas con discapacidad visual. Fabricado en aluminio anodizado, este bastón es ligero, seguro y resistente. Su sistema plegable en 4 secciones facilita su almacenamiento y transporte, mientras que su empuñadura plástica ergonómica y tapón giratorio brindan comodidad y estabilidad. Además, incluye bandas reflectivas para mejorar la visibilidad en entornos con poca luz.

El bastón para invidente plegable Konfort Plus es de aluminio anodizado, ligero, seguro y resistente. Se pliega en 4 secciones, incluye correa de seguridad, empuñadura de TPR, tapón giratorio, bandas reflectivas y estuche de transporte, con estructura liviana y almacenamiento sencillo.$d$,
  descripcion_larga_en = $d$The Konfort Plus Foldable Cane for the Visually Impaired is an essential tool to provide safety and orientation to people with visual disabilities. Made of anodized aluminum, this cane is lightweight, safe and resistant. Its 4-section folding system facilitates storage and transportation, while its ergonomic plastic handle and swivel tip provide comfort and stability. It also includes reflective bands to improve visibility in low-light environments.

The Konfort Plus folding cane for the blind is made of anodised aluminium, light, safe and sturdy. It folds into 4 sections and includes a safety strap, TPR handle, rotating tip, reflective bands and a carrying case, with a lightweight structure and simple storage.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4-832L6-20"},{"clave":"Plegado","grupo":"Configuración","valor":"4 secciones"},{"clave":"Estructura / empuñadura","grupo":"Material","valor":"Aluminio anodizado / TPR"},{"clave":"Visibilidad","grupo":"Seguridad","valor":"Bandas reflectivas; correa de seguridad"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Plegable en 4 secciones con estuche de transporte.","Bandas reflectivas, correa de seguridad y tapón giratorio.","Aluminio anodizado liviano con empuñadura de TPR."],"beneficios_en":["Folds into 4 sections with carrying case.","Reflective bands, safety strap and rotating tip.","Lightweight anodised aluminium with TPR handle."],"valor_es":"Un bastón blanco plegable para personas con discapacidad visual, con ficha oficial de Konfort Plus.","valor_en":"A folding white cane for people with visual impairment, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿En cuántas secciones se pliega?","a":"En 4 secciones."},{"q":"¿Incluye estuche?","a":"Sí, incluye estuche de transporte."},{"q":"¿Tiene elementos de visibilidad?","a":"Sí, bandas reflectivas."},{"q":"¿Dónde descargo la ficha técnica de Bastón Para Invidente Plegable Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"How many sections does it fold into?","a":"4 sections."},{"q":"Does it include a case?","a":"Yes, a carrying case is included."},{"q":"Does it have visibility features?","a":"Yes, reflective bands."},{"q":"Where can I download the Konfort Plus Foldable White Cane for the Visually Impaired datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón para invidente plegable","bastón blanco para personas ciegas","bastón guía plegable","bastón Konfort Plus","ayudas para la movilidad visual Colombia","ficha técnica KP4-832L6-20"],"seo_keywords_en":["folding cane for the blind","white cane for blind people","folding guide cane","Konfort Plus cane","visual mobility aids Colombia","KP4-832L6-20 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCLA3EXG5OOJEZXF63RP3WHZ62NA?version=4.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-para-invidente-plegable-ref-kp4-832l6-20-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4819-21-ft.pdf',
  descripcion_larga_es = $d$El bastón de 4 apoyos con linterna de Konfort Plus está diseñado para ofrecer una combinación única de seguridad, comodidad y funcionalidad. Su estructura de aluminio ligera pero duradera, junto con la base de 4 apoyos, proporciona una estabilidad excepcional, ideal para personas con alteraciones en el equilibrio o la fuerza. Ajustable en altura, este bastón se adapta perfectamente a cada usuario, ofreciendo un soporte ergonómico y personalizado.

El bastón de 4 apoyos con linterna Konfort Plus tiene base pequeña con contacto estable con el suelo, linterna y alarma, y un sistema de articulación fija que mejora el agarre y la facilidad de manejo. Su altura se gradúa en diez posiciones.$d$,
  descripcion_larga_en = $d$The Konfort Plus 4-support cane with flashlight is designed to offer a unique combination of safety, comfort and functionality. Its lightweight yet durable aluminum structure, together with the 4-support base, provides exceptional stability, ideal for people with balance or strength alterations. Height-adjustable, this cane adapts perfectly to each user, offering ergonomic and personalized support.

The Konfort Plus 4-point cane with flashlight has a small base with stable ground contact, a flashlight and alarm, and a fixed articulation system that improves grip and ease of handling. Its height adjusts in ten positions.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4819-21"},{"clave":"Apoyos","grupo":"Configuración","valor":"4, base pequeña"},{"clave":"Alturas","grupo":"Configuración","valor":"10 posiciones"},{"clave":"Extras","grupo":"Extras","valor":"Linterna y alarma"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Linterna y alarma integradas para usarlo con poca luz y pedir ayuda.","Cuatro apoyos con base pequeña de contacto estable.","Altura graduable en diez posiciones."],"beneficios_en":["Integrated flashlight and alarm for use in low light and to call for help.","Four supports with a small, stable-contact base.","Height adjustable in ten positions."],"valor_es":"Un bastón de cuatro apoyos con linterna y alarma, con ficha oficial de Konfort Plus.","valor_en":"A four-point cane with flashlight and alarm, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Tiene luz?","a":"Sí, incluye linterna y alarma."},{"q":"¿Cuántas posiciones de altura tiene?","a":"Diez."},{"q":"¿Cuántos apoyos tiene?","a":"Cuatro, con base pequeña."},{"q":"¿Dónde descargo la ficha técnica de Bastón 4 Apoyos Con Linterna Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Does it have a light?","a":"Yes, it includes a flashlight and alarm."},{"q":"How many height positions does it have?","a":"Ten."},{"q":"How many supports does it have?","a":"Four, with a small base."},{"q":"Where can I download the Konfort Plus 4-Support Cane with Flashlight datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón de 4 apoyos con linterna","bastón con luz y alarma","bastón cuatro apoyos","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4819-21"],"seo_keywords_en":["4-point cane with flashlight","cane with light and alarm","quad cane","Konfort Plus cane","orthopaedic cane Colombia","KP4819-21 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCT5RYMYSVQJBMVMDVYBVP7FDL5M?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-4-apoyos-con-linterna-ref-kp4819-21-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kb311s-al19-ft.pdf',
  descripcion_larga_es = $d$La Muleta Convencional Konfort Plus está diseñada para proporcionar un apoyo seguro, cómodo y eficaz a personas con movilidad reducida. Fabricada en aluminio anodizado de color gris, es ligera pero resistente, con un centro reforzado que soporta una mayor carga y asegura durabilidad.

La muleta convencional Konfort Plus en aluminio anodizado gris (talla S) cuenta con ajuste de altura en su parte inferior, es ligera y brinda una asistencia segura al caminar. Pesa alrededor de 0,82 a 0,86 kg y se ofrece en tallas S, M y L.$d$,
  descripcion_larga_en = $d$The Konfort Plus Conventional Crutch is designed to provide safe, comfortable and effective support for people with reduced mobility. Made of anodized grey aluminum, it is lightweight yet resistant, with a reinforced center that supports a greater load and ensures durability. Available in size S, it fits users of short stature with ease. Its ergonomic design allows proper posture during walking.

The Konfort Plus conventional crutch in grey anodised aluminium (size S) has height adjustment at the bottom, is light and provides safe walking assistance. It weighs around 0.82 to 0.86 kg and comes in sizes S, M and L.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KB311S-AL19"},{"clave":"Talla / altura del usuario","grupo":"Talla","valor":"S: 92 - 112 cm"},{"clave":"Material","grupo":"Material","valor":"Aluminio anodizado gris"},{"clave":"Peso unitario","grupo":"Peso","valor":"0,82 - 0,86 kg"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Aluminio anodizado ligero (0,82 - 0,86 kg por muleta).","Ajuste de altura en la parte inferior.","Tres tallas (S, M, L) para adaptarse a la estatura."],"beneficios_en":["Light anodised aluminium (0.82 - 0.86 kg per crutch).","Height adjustment at the bottom.","Three sizes (S, M, L) to fit the user's height."],"valor_es":"Una muleta de aluminio con ajuste de altura, con ficha oficial de Konfort Plus.","valor_en":"An aluminium crutch with height adjustment, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué tallas hay?","a":"S (92-112 cm), M (112-132 cm) y L (132-152 cm)."},{"q":"¿De qué material es?","a":"Aluminio anodizado en color gris."},{"q":"¿Cómo se ajusta?","a":"Con ajuste de altura en la parte inferior."},{"q":"¿Dónde descargo la ficha técnica de Muleta Convencional En Aluminio Talla S Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which sizes are there?","a":"S (92-112 cm), M (112-132 cm) and L (132-152 cm)."},{"q":"What material is it?","a":"Grey anodised aluminium."},{"q":"How is it adjusted?","a":"With height adjustment at the bottom."},{"q":"Where can I download the Conventional Aluminum Crutch Size S Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["muleta convencional talla S","muleta de aluminio","muletas ortopédicas","muleta Konfort Plus","muletas Colombia","ficha técnica KB311S-AL19"],"seo_keywords_en":["conventional crutch size S","aluminium crutch","orthopaedic crutches","Konfort Plus crutch","crutches Colombia","KB311S-AL19 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MC5S6QN2AQLBGRVLLHSZGDLFBI2A?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'muleta-convencional-en-aluminio-talla-s-ref-kb311s-al19-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kb311s-al19-ft.pdf',
  descripcion_larga_es = $d$La Muleta Convencional Konfort Plus está diseñada para proporcionar un apoyo seguro, cómodo y eficaz a personas con movilidad reducida. Fabricada en aluminio anodizado de color gris, es ligera pero resistente, con un centro reforzado que soporta una mayor carga y asegura durabilidad.

La muleta convencional Konfort Plus en aluminio anodizado gris (talla M) cuenta con ajuste de altura en su parte inferior, es ligera y brinda una asistencia segura al caminar. Pesa alrededor de 0,82 a 0,86 kg y se ofrece en tallas S, M y L.$d$,
  descripcion_larga_en = $d$The Konfort Plus Conventional Crutch is designed to provide safe, comfortable and effective support for people with reduced mobility. Made of anodized grey aluminum, it is lightweight yet resistant, with a reinforced center that supports a greater load and ensures durability. Size M fits users of medium stature. Its ergonomic handgrip reduces hand fatigue during prolonged use.

The Konfort Plus conventional crutch in grey anodised aluminium (size M) has height adjustment at the bottom, is light and provides safe walking assistance. It weighs around 0.82 to 0.86 kg and comes in sizes S, M and L.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KB311M-AL19"},{"clave":"Talla / altura del usuario","grupo":"Talla","valor":"M: 112 - 132 cm"},{"clave":"Material","grupo":"Material","valor":"Aluminio anodizado gris"},{"clave":"Peso unitario","grupo":"Peso","valor":"0,82 - 0,86 kg"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Aluminio anodizado ligero (0,82 - 0,86 kg por muleta).","Ajuste de altura en la parte inferior.","Tres tallas (S, M, L) para adaptarse a la estatura."],"beneficios_en":["Light anodised aluminium (0.82 - 0.86 kg per crutch).","Height adjustment at the bottom.","Three sizes (S, M, L) to fit the user's height."],"valor_es":"Una muleta de aluminio con ajuste de altura, con ficha oficial de Konfort Plus.","valor_en":"An aluminium crutch with height adjustment, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué tallas hay?","a":"S (92-112 cm), M (112-132 cm) y L (132-152 cm)."},{"q":"¿De qué material es?","a":"Aluminio anodizado en color gris."},{"q":"¿Cómo se ajusta?","a":"Con ajuste de altura en la parte inferior."},{"q":"¿Dónde descargo la ficha técnica de Muleta Convencional En Aluminio Talla M Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which sizes are there?","a":"S (92-112 cm), M (112-132 cm) and L (132-152 cm)."},{"q":"What material is it?","a":"Grey anodised aluminium."},{"q":"How is it adjusted?","a":"With height adjustment at the bottom."},{"q":"Where can I download the Conventional Aluminum Crutch Size M Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["muleta convencional talla M","muleta de aluminio","muletas ortopédicas","muleta Konfort Plus","muletas Colombia","ficha técnica KB311M-AL19"],"seo_keywords_en":["conventional crutch size M","aluminium crutch","orthopaedic crutches","Konfort Plus crutch","crutches Colombia","KB311M-AL19 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MC5S6QN2AQLBGRVLLHSZGDLFBI2A?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'muleta-convencional-en-aluminio-talla-m-ref-kb311m-al19-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kb311s-al19-ft.pdf',
  descripcion_larga_es = $d$La Muleta Convencional de Konfort Plus es una solución ligera y resistente, ideal para brindar soporte y estabilidad durante la marcha. Fabricada en aluminio anodizado de color gris, esta muleta ofrece un ajuste de altura en su parte inferior para adaptarse a diferentes usuarios. Disponible en tres tallas (L, M, S), es una herramienta práctica para facilitar el desplazamiento de personas que necesitan asistencia al caminar.

La muleta convencional Konfort Plus en aluminio anodizado gris (talla L) cuenta con ajuste de altura en su parte inferior, es ligera y brinda una asistencia segura al caminar. Pesa alrededor de 0,82 a 0,86 kg y se ofrece en tallas S, M y L.$d$,
  descripcion_larga_en = $d$The Konfort Plus Conventional Crutch is a lightweight and resistant solution, ideal for providing support and stability during walking. Made of anodized grey aluminum, this crutch offers height adjustment at the lower part to suit different users. Available in three sizes (L, M, S), it is a practical tool to facilitate the movement of people who need walking assistance. Size L is recommended for taller users due to its greater length. Its non-slip tip provides grip on smooth and wet floors.

The Konfort Plus conventional crutch in grey anodised aluminium (size L) has height adjustment at the bottom, is light and provides safe walking assistance. It weighs around 0.82 to 0.86 kg and comes in sizes S, M and L.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KB311L-AL19"},{"clave":"Talla / altura del usuario","grupo":"Talla","valor":"L: 132 - 152 cm"},{"clave":"Material","grupo":"Material","valor":"Aluminio anodizado gris"},{"clave":"Peso unitario","grupo":"Peso","valor":"0,82 - 0,86 kg"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Aluminio anodizado ligero (0,82 - 0,86 kg por muleta).","Ajuste de altura en la parte inferior.","Tres tallas (S, M, L) para adaptarse a la estatura."],"beneficios_en":["Light anodised aluminium (0.82 - 0.86 kg per crutch).","Height adjustment at the bottom.","Three sizes (S, M, L) to fit the user's height."],"valor_es":"Una muleta de aluminio con ajuste de altura, con ficha oficial de Konfort Plus.","valor_en":"An aluminium crutch with height adjustment, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué tallas hay?","a":"S (92-112 cm), M (112-132 cm) y L (132-152 cm)."},{"q":"¿De qué material es?","a":"Aluminio anodizado en color gris."},{"q":"¿Cómo se ajusta?","a":"Con ajuste de altura en la parte inferior."},{"q":"¿Dónde descargo la ficha técnica de Muleta Convencional En Aluminio Talla L Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which sizes are there?","a":"S (92-112 cm), M (112-132 cm) and L (132-152 cm)."},{"q":"What material is it?","a":"Grey anodised aluminium."},{"q":"How is it adjusted?","a":"With height adjustment at the bottom."},{"q":"Where can I download the Conventional Aluminum Crutch Size L Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["muleta convencional talla L","muleta de aluminio","muletas ortopédicas","muleta Konfort Plus","muletas Colombia","ficha técnica KB311L-AL19"],"seo_keywords_en":["conventional crutch size L","aluminium crutch","orthopaedic crutches","Konfort Plus crutch","crutches Colombia","KB311L-AL19 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MC5S6QN2AQLBGRVLLHSZGDLFBI2A?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'muleta-convencional-en-aluminio-talla-l-ref-kb311l-al19-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp3-856m-19-ft.pdf',
  descripcion_larga_es = $d$La Muleta Canadiense Doble Regulación de Konfort Plus está diseñada para proporcionar un apoyo firme y seguro a personas con movilidad reducida. Fabricada en aluminio anodizado, esta muleta es resistente y ligera, con un sistema de doble ajuste que permite regular tanto la altura de la muleta como la posición de la empuñadura. Disponible en dos tallas (L y M), se adapta a usuarios de distintas estaturas, ofreciendo una excelente ergonomía y estabilidad en cada paso.

La muleta canadiense de doble regulación Konfort Plus (talla M) permite regular la altura entre el suelo y la empuñadura y entre la empuñadura y la abrazadera. Es de aluminio anodizado, resistente y ligera, con tapones antideslizantes para mayor tracción, graduación por pines, extensión telescópica y no requiere ensamble.$d$,
  descripcion_larga_en = $d$The Konfort Plus Canadian Double Adjustment Crutch is designed to provide firm and safe support for people with reduced mobility. Made of anodized aluminum, this crutch is resistant and lightweight, with a double adjustment system that allows regulating both the crutch height and the handle position. Available in two sizes (L and M), it adapts to users of different statures, offering excellent ergonomics and stability in each step. The Canadian configuration distributes the load between the hand and forearm, reducing pressure on the wrist joint. It is suitable for prolonged rehabilitation and demanding clinical environments.

The Konfort Plus double-adjustment forearm crutch (size M) lets you adjust height between the floor and the handgrip and between the handgrip and the cuff. It is sturdy, light anodised aluminium with anti-slip tips for better traction, pin-based adjustment and telescopic extension, and requires no assembly.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP3-856M-19"},{"clave":"Material","grupo":"Material","valor":"Aluminio anodizado"},{"clave":"Regulación","grupo":"Ajustes","valor":"Doble: suelo-empuñadura y empuñadura-abrazadera"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Doble regulación de altura: suelo-empuñadura y empuñadura-abrazadera.","Aluminio anodizado ligero con tapones antideslizantes.","Graduación por pines, extensión telescópica y sin ensamble."],"beneficios_en":["Double height adjustment: floor-to-handgrip and handgrip-to-cuff.","Light anodised aluminium with anti-slip tips.","Pin adjustment, telescopic extension and no assembly."],"valor_es":"Una muleta canadiense de aluminio con doble regulación, con ficha oficial de Konfort Plus.","valor_en":"An aluminium forearm crutch with double adjustment, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué es la doble regulación?","a":"Permite ajustar la altura suelo-empuñadura y empuñadura-abrazadera."},{"q":"¿Requiere ensamble?","a":"No, viene lista para usar."},{"q":"¿Qué tallas hay?","a":"Tallas M (KP3-856M-19) y L (KP3-856L-19)."},{"q":"¿Dónde descargo la ficha técnica de Muleta Canadiense Doble Regulación Talla M Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What is double adjustment?","a":"It lets you adjust floor-to-handgrip and handgrip-to-cuff height."},{"q":"Does it require assembly?","a":"No, it comes ready to use."},{"q":"Which sizes are there?","a":"Sizes M (KP3-856M-19) and L (KP3-856L-19)."},{"q":"Where can I download the Canadian Double Adjustment Crutch Size M Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["muleta canadiense talla M","muleta canadiense doble regulación","muleta con abrazadera","muleta Konfort Plus","muletas canadienses Colombia","ficha técnica KP3-856M-19"],"seo_keywords_en":["forearm crutch size M","double-adjustment forearm crutch","cuffed crutch","Konfort Plus crutch","forearm crutches Colombia","KP3-856M-19 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MC7Q3GJW6NWFH37JV5NZQTT57ATM?version=3.2&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'muleta-canadiense-doble-regulacion-talla-m-ref-kp3-856m-19-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp3-856m-19-ft.pdf',
  descripcion_larga_es = $d$La Muleta Canadiense Doble Regulación de Konfort Plus está diseñada para proporcionar un apoyo firme y seguro a personas con movilidad reducida. Fabricada en aluminio anodizado, esta muleta es resistente y ligera, con un sistema de doble ajuste que permite regular tanto la altura de la muleta como la posición de la empuñadura. Disponible en dos tallas (L y M), se adapta a usuarios de distintas estaturas, ofreciendo una excelente ergonomía y estabilidad en cada paso.

La muleta canadiense de doble regulación Konfort Plus (talla L) permite regular la altura entre el suelo y la empuñadura y entre la empuñadura y la abrazadera. Es de aluminio anodizado, resistente y ligera, con tapones antideslizantes para mayor tracción, graduación por pines, extensión telescópica y no requiere ensamble.$d$,
  descripcion_larga_en = $d$Double-regulation Canadian crutch from Konfort Plus, designed to provide firm, secure support for individuals with reduced mobility. Made of anodized aluminum, this crutch is resistant and lightweight, featuring a dual-adjustment system that regulates both the shaft height and the handle position. Available in two sizes (L and M), it adapts to users of different heights, delivering excellent ergonomics and stability with every step.

The Konfort Plus double-adjustment forearm crutch (size L) lets you adjust height between the floor and the handgrip and between the handgrip and the cuff. It is sturdy, light anodised aluminium with anti-slip tips for better traction, pin-based adjustment and telescopic extension, and requires no assembly.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP3-856L-19"},{"clave":"Material","grupo":"Material","valor":"Aluminio anodizado"},{"clave":"Regulación","grupo":"Ajustes","valor":"Doble: suelo-empuñadura y empuñadura-abrazadera"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Doble regulación de altura: suelo-empuñadura y empuñadura-abrazadera.","Aluminio anodizado ligero con tapones antideslizantes.","Graduación por pines, extensión telescópica y sin ensamble."],"beneficios_en":["Double height adjustment: floor-to-handgrip and handgrip-to-cuff.","Light anodised aluminium with anti-slip tips.","Pin adjustment, telescopic extension and no assembly."],"valor_es":"Una muleta canadiense de aluminio con doble regulación, con ficha oficial de Konfort Plus.","valor_en":"An aluminium forearm crutch with double adjustment, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué es la doble regulación?","a":"Permite ajustar la altura suelo-empuñadura y empuñadura-abrazadera."},{"q":"¿Requiere ensamble?","a":"No, viene lista para usar."},{"q":"¿Qué tallas hay?","a":"Tallas M (KP3-856M-19) y L (KP3-856L-19)."},{"q":"¿Dónde descargo la ficha técnica de Muleta Canadiense Doble Regulación Talla L Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What is double adjustment?","a":"It lets you adjust floor-to-handgrip and handgrip-to-cuff height."},{"q":"Does it require assembly?","a":"No, it comes ready to use."},{"q":"Which sizes are there?","a":"Sizes M (KP3-856M-19) and L (KP3-856L-19)."},{"q":"Where can I download the Canadian Crutch Double Regulation Size L Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["muleta canadiense talla L","muleta canadiense doble regulación","muleta con abrazadera","muleta Konfort Plus","muletas canadienses Colombia","ficha técnica KP3-856L-19"],"seo_keywords_en":["forearm crutch size L","double-adjustment forearm crutch","cuffed crutch","Konfort Plus crutch","forearm crutches Colombia","KP3-856L-19 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MC7Q3GJW6NWFH37JV5NZQTT57ATM?version=3.2&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'muleta-canadiense-doble-regulacion-talla-l-ref-kp3-856l-19-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp321-al-19-ft.pdf',
  descripcion_larga_es = $d$La Muleta Canadiense Adulto Integral Konfort Plus es una herramienta indispensable para mejorar la movilidad de personas con dificultades para caminar. Fabricada en aluminio anodizado, combina ligereza con resistencia, proporcionando un soporte estable y seguro. Con un diseño ergonómico y ajuste de altura desde 72 cm hasta 94 cm, esta muleta se adapta fácilmente a usuarios de diferentes estaturas, garantizando comodidad y funcionalidad en el uso diario.

La muleta canadiense para adulto Konfort Plus (color plata) está fabricada en aluminio anodizado, resistente, duradera y ligera, y brinda apoyo seguro y confortable durante la marcha. Tiene tapones antideslizantes, graduación de altura por pines y angulación para mayor estabilidad; no requiere ensamble.$d$,
  descripcion_larga_en = $d$The Konfort Plus Integrated Adult Canadian Crutch is an indispensable tool to improve mobility in people with walking difficulties. Manufactured in anodized aluminum, it combines lightness with strength, providing stable and safe support. With an ergonomic design and height adjustment from 72 cm to 94 cm, this crutch easily adapts to users of different heights, ensuring comfort and functionality in daily use.

The Konfort Plus adult forearm crutch (silver) is made of anodised aluminium, sturdy, durable and light, and provides safe, comfortable support when walking. It has anti-slip tips, pin height adjustment and angulation for greater stability; no assembly required.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP321-AL-19"},{"clave":"Material","grupo":"Material","valor":"Aluminio anodizado, color plata"},{"clave":"Regulación","grupo":"Ajustes","valor":"Pines"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Aluminio anodizado resistente y ligero.","Angulación para mayor estabilidad y mejor distribución del peso.","Tapones antideslizantes, graduación por pines y sin ensamble."],"beneficios_en":["Sturdy, light anodised aluminium.","Angulation for greater stability and better weight distribution.","Anti-slip tips, pin adjustment and no assembly."],"valor_es":"Una muleta canadiense de aluminio para adulto, con ficha oficial de Konfort Plus.","valor_en":"An aluminium adult forearm crutch, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Es para adultos?","a":"Sí, es una muleta canadiense para adulto."},{"q":"¿Cómo se regula la altura?","a":"Por medio de pines."},{"q":"¿Requiere ensamble?","a":"No."},{"q":"¿Dónde descargo la ficha técnica de Muleta Canadiense Adulto Integral Color Plata Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Is it for adults?","a":"Yes, it is an adult forearm crutch."},{"q":"How is height adjusted?","a":"By pins."},{"q":"Does it require assembly?","a":"No."},{"q":"Where can I download the Konfort Plus Integrated Adult Canadian Crutch Silver Color datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["muleta canadiense adulto","muleta de aluminio plata","muleta con apoyo de antebrazo","muleta Konfort Plus","muletas Colombia","ficha técnica KP321-AL-19"],"seo_keywords_en":["adult forearm crutch","silver aluminium crutch","forearm support crutch","Konfort Plus crutch","crutches Colombia","KP321-AL-19 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCDFBN7Y2S5NFN3BC3SDOIGSLVQM?version=2.2&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'muleta-canadiense-adulto-integral-color-plata-ref-kp321-al-19-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4202-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón Cuatro Apoyos Konfort Plus ofrece estabilidad y firmeza gracias a su base pequeña de cuatro puntos y su empuñadura de cuello en cisne, brindando un apoyo seguro a personas con movilidad reducida. Fabricado en aluminio resistente con una base en acero cromado, este bastón combina ligereza y durabilidad. Su altura es fácilmente ajustable por medio de un botón de pin, lo que permite adaptarse a diferentes estaturas.

El bastón de 4 apoyos con base pequeña Konfort Plus (cromo) ofrece gran estabilidad y resistencia gracias a sus cuatro apoyos, con sistema de graduación de altura de ajuste firme, base en acero cromado y acabados de alta calidad. La empuñadura es de PVC. La ficha del fabricante indica capacidad de 125 kg y altura entre 72,5 y 95 cm.$d$,
  descripcion_larga_en = $d$The Konfort Plus Four-Prong Walking Stick provides stability and firmness through its small four-point base and swan-neck handle, offering secure support for individuals with reduced mobility. Made from durable aluminum with a chromed steel base, this cane combines lightweight construction with long-term durability. Its height is easily adjustable via a pin button, allowing adaptation to different statures.

The Konfort Plus small-base 4-point cane (chrome) offers great stability and strength thanks to its four supports, with a firm-locking height adjustment system, chrome-steel base and high-quality finishes. The handle is PVC. The manufacturer datasheet states 125 kg capacity and a height between 72.5 and 95 cm.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4202-22"},{"clave":"Color","grupo":"Variante","valor":"Cromo"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"72,5 - 95 cm"},{"clave":"Base","grupo":"Material","valor":"Acero cromado"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Cuatro apoyos para mayor estabilidad al caminar.","Base en acero cromado y altura graduable de 72,5 a 95 cm.","Capacidad de hasta 125 kg y empuñadura de PVC."],"beneficios_en":["Four supports for greater stability when walking.","Chrome-steel base and height adjustable from 72.5 to 95 cm.","Capacity up to 125 kg and PVC handle."],"valor_es":"Un bastón de cuatro apoyos para mayor estabilidad, con ficha técnica oficial de Konfort Plus (ficha de la variante cromo de la misma referencia base).","valor_en":"A four-point cane for greater stability, with official Konfort Plus datasheet (datasheet of the chrome variant of the same base model).","preguntas_frecuentes_es":[{"q":"¿Qué ventaja tiene frente a un bastón simple?","a":"Sus cuatro apoyos brindan mayor estabilidad, según el fabricante."},{"q":"¿Qué peso soporta?","a":"Hasta 125 kg."},{"q":"¿Qué altura permite?","a":"Entre 72,5 y 95 cm."},{"q":"¿Dónde descargo la ficha técnica de Bastón 4 Apoyos Base Pequeña Color Cromo Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What advantage does it have over a simple cane?","a":"Its four supports provide greater stability, per the manufacturer."},{"q":"What weight does it support?","a":"Up to 125 kg."},{"q":"What height does it allow?","a":"Between 72.5 and 95 cm."},{"q":"Where can I download the Konfort Plus Four-Prong Small Base Walking Stick Chrome datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón de 4 apoyos cromo","bastón cuatro apoyos base pequeña","bastón de apoyo estable","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4202-22"],"seo_keywords_en":["4-point cane chrome","small base quad cane","stable support cane","Konfort Plus cane","orthopaedic cane Colombia","KP4202-22 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCII6BK6SHAVBKVDRNCZBYNGN7KE?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-4-apoyos-base-pequena-color-cromo-ref-kp4202-22-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4152-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón Cuello de Cisne Konfort Plus está diseñado para proporcionar un apoyo seguro y ergonómico, ideal para quienes requieren asistencia en su movilidad diaria. Fabricado en aluminio resistente y ligero, cuenta con una empuñadura ergonómica de espuma y un sistema de graduación de altura ajustable desde 77 cm hasta 100 cm, lo que lo hace adecuado para usuarios de diferentes estaturas. Su diseño de cuello de cisne distribuye mejor el peso del usuario, proporcionando mayor estabilidad.

El bastón cuello de cisne con correa de seguridad Konfort Plus (cromo) es de aluminio, seguro, ligero y resistente, con graduación de altura de ajuste firme y empuñadura de PVC de fácil limpieza y larga duración. Su correa de seguridad evita que se caiga y su diseño elegante conserva acabados de alta calidad; la ficha indica capacidad de 125 kg.$d$,
  descripcion_larga_en = $d$The Swan-Neck Cane Konfort Plus is designed to provide safe, ergonomic support, ideal for those requiring assistance in daily mobility. Made from durable, lightweight aluminum, it features an ergonomic foam handle and an adjustable height graduation system from 77 cm to 100 cm, making it suitable for users of different statures. Its swan-neck design better distributes the user's weight, providing greater stability.

The Konfort Plus swan-neck cane with safety strap (chrome) is aluminium, safe, light and sturdy, with firm-locking height adjustment and an easy-to-clean, long-lasting PVC handle. Its safety strap keeps it from dropping and its elegant design keeps high-quality finishes; the datasheet states a 125 kg capacity.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4152-22"},{"clave":"Color","grupo":"Variante","valor":"Cromo"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Material","grupo":"Material","valor":"Aluminio; empuñadura PVC"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Cuello de cisne con correa de seguridad para no soltarlo.","Aluminio ligero y resistente con capacidad de 125 kg.","Empuñadura PVC de fácil limpieza y altura graduable."],"beneficios_en":["Swan-neck with safety strap to keep hold of it.","Light, sturdy aluminium with 125 kg capacity.","Easy-clean PVC handle and adjustable height."],"valor_es":"Un bastón cuello de cisne con correa de seguridad, con ficha oficial de Konfort Plus (ficha compartida con los colores de la misma referencia).","valor_en":"A swan-neck cane with safety strap, with official Konfort Plus datasheet (shared across the colours of the same model).","preguntas_frecuentes_es":[{"q":"¿Qué incluye de seguridad?","a":"Una correa de seguridad en la empuñadura."},{"q":"¿Qué peso soporta?","a":"125 kg."},{"q":"¿De qué es la empuñadura?","a":"De PVC, de fácil limpieza y larga duración."},{"q":"¿Dónde descargo la ficha técnica de Bastón Cuello De Cisne Y Correa De Seguridad Color Cromo Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What safety feature does it include?","a":"A safety strap on the handle."},{"q":"What weight does it support?","a":"125 kg."},{"q":"What is the handle made of?","a":"PVC, easy to clean and long-lasting."},{"q":"Where can I download the Swan-Neck Cane with Safety Strap Chrome Color Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón cuello de cisne cromo","bastón con correa de seguridad","bastón de aluminio","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4152-22"],"seo_keywords_en":["swan-neck cane chrome","cane with safety strap","aluminium cane","Konfort Plus cane","orthopaedic cane Colombia","KP4152-22 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCFH732SK5VNCGDDHNRFRBNH4264?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-cuello-de-cisne-y-correa-de-seguridad-color-cromo-ref-kp4152-22-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp4192-20-ft.pdf',
  descripcion_larga_es = $d$El Bastón Tipo Paraguas Konfort Plus está diseñado para proporcionar un apoyo seguro y resistente a las personas que requieren asistencia en su movilidad diaria. Fabricado en aluminio ligero, este bastón cuenta con un sistema de graduación de altura ajustable que permite adaptarse a diferentes estaturas, brindando un ajuste firme y preciso. Su empuñadura ergonómica de espuma, junto con su diseño elegante y acabados de alta calidad, garantiza comodidad y estilo en cada uso.

El bastón tipo paraguas Konfort Plus (cromo) es de aluminio, ligero, seguro y resistente, con sistema de graduación de altura de ajuste firme, empuñadura ergonómica de elegante diseño y acabados de alta calidad. Según la ficha soporta 125 kg y se ajusta entre 76 y 99 cm; la empuñadura es de espuma.$d$,
  descripcion_larga_en = $d$The Umbrella-Type Cane Konfort Plus is designed to provide secure and sturdy support for people requiring assistance in their daily mobility. Made from lightweight aluminum, this cane includes an adjustable height graduation system to adapt to different statures, providing firm and precise adjustment. Its ergonomic foam handle, combined with an elegant design and high-quality finishes, ensures comfort and style with each use.

The Konfort Plus umbrella-type cane (chrome) is aluminium, light, safe and sturdy, with firm-locking height adjustment, an elegantly designed ergonomic handle and high-quality finishes. Per the datasheet it supports 125 kg and adjusts between 76 and 99 cm; the handle is foam.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP4192-22"},{"clave":"Color","grupo":"Variante","valor":"Cromo"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"125 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"76 - 99 cm"},{"clave":"Material","grupo":"Material","valor":"Aluminio; empuñadura de espuma"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Empuñadura tipo paraguas de espuma, ergonómica y cómoda.","Altura graduable de 76 a 99 cm.","Aluminio ligero con capacidad de 125 kg."],"beneficios_en":["Comfortable ergonomic foam umbrella-type handle.","Height adjustable from 76 to 99 cm.","Light aluminium with 125 kg capacity."],"valor_es":"Un bastón tipo paraguas ligero y graduable, con ficha oficial de Konfort Plus.","valor_en":"A light, adjustable umbrella-type cane, with official Konfort Plus datasheet.","preguntas_frecuentes_es":[{"q":"¿Qué altura tiene?","a":"Entre 76 y 99 cm."},{"q":"¿Qué peso soporta?","a":"125 kg."},{"q":"¿De qué es la empuñadura?","a":"De espuma."},{"q":"¿Dónde descargo la ficha técnica de Bastón Tipo Paraguas Color Cromo Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What height does it have?","a":"Between 76 and 99 cm."},{"q":"What weight does it support?","a":"125 kg."},{"q":"What is the handle made of?","a":"Foam."},{"q":"Where can I download the Umbrella-Type Cane Chrome Color Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["bastón tipo paraguas cromo","bastón de aluminio graduable","bastón con empuñadura de espuma","bastón Konfort Plus","bastón ortopédico Colombia","ficha técnica KP4192-22"],"seo_keywords_en":["umbrella-type cane chrome","adjustable aluminium cane","foam-handle cane","Konfort Plus cane","orthopaedic cane Colombia","KP4192-22 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCLQ2JGV6C6RHSXGVA6LHX2HUOUY?version=4.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'baston-tipo-paraguas-color-cromo-ref-kp4192-22-konfort-plus';
