-- Second landing batch: content transcribed from the cited manufacturer documentation.
-- Preserve existing JSON attributes; no prices, schema, or commercial logic are changed.

UPDATE public.productos SET
  nombre_es = 'Kit de circuito AirSpiral para Airvo 2 900PT561 Fisher & Paykel',
  nombre_en = 'Fisher & Paykel 900PT561 AirSpiral Circuit Kit for Airvo 2',
  descripcion_corta_es = 'Kit de circuito AirSpiral para sistema Airvo 2, presentación de 10.',
  descripcion_corta_en = 'AirSpiral circuit kit for the Airvo 2 system, supplied in packs of 10.',
  descripcion_larga_es = 'El 900PT561 es un kit de circuito AirSpiral Fisher & Paykel para el sistema Airvo 2. La documentación consultada indica presentación de 10. La configuración compatible del sistema se confirma con la documentación vigente del fabricante y en la cotización.',
  descripcion_larga_en = 'The 900PT561 is a Fisher & Paykel AirSpiral circuit kit for the Airvo 2 system. The reviewed documentation states a pack of 10. Compatible system configuration must be confirmed against current manufacturer documentation and in the quotation.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"900PT561"},{"clave":"Tipo","grupo":"Configuración","valor":"Kit de circuito AirSpiral"},{"clave":"Sistema descrito","grupo":"Compatibilidad","valor":"Airvo 2"},{"clave":"Presentación","grupo":"Empaque","valor":"10"}]'::jsonb,
  aplicaciones_es = ARRAY['Configuración del sistema Airvo 2 con kit de circuito AirSpiral'],
  aplicaciones_en = ARRAY['Airvo 2 system configuration with the AirSpiral circuit kit'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"Fisher & Paykel","fabricante":"Fisher & Paykel","ref_proveedor":"900PT561","valor_es":"Kit de circuito AirSpiral para la configuración descrita de Airvo 2.","valor_en":"AirSpiral circuit kit for the described Airvo 2 configuration.","beneficios_es":["Identifica la referencia específica del kit de circuito para Airvo 2.","La presentación publicada permite solicitar la cantidad indicada."],"beneficios_en":["Identifies the specific circuit-kit reference for Airvo 2.","The published pack supports requesting the stated quantity."],"preguntas_frecuentes_es":[{"q":"¿Para qué sistema se describe el 900PT561?","a":"La documentación consultada lo describe como kit de circuito AirSpiral para Airvo 2."},{"q":"¿Cuál es su presentación?","a":"La presentación indicada es de 10."},{"q":"¿Debe confirmarse la configuración?","a":"Sí. Debe confirmarse con documentación vigente del fabricante y en la cotización."}],"preguntas_frecuentes_en":[{"q":"Which system is the 900PT561 described for?","a":"The reviewed documentation describes it as an AirSpiral circuit kit for Airvo 2."},{"q":"What is its pack size?","a":"The stated pack size is 10."},{"q":"Should the configuration be confirmed?","a":"Yes. It must be confirmed against current manufacturer documentation and in the quotation."}],"seo_keywords_es":["kit circuito AirSpiral 900PT561","circuito Airvo 2 Fisher Paykel","AirSpiral Colombia"],"seo_keywords_en":["900PT561 AirSpiral circuit kit","Fisher Paykel Airvo 2 circuit","AirSpiral Colombia"],"fuentes_auditoria":["https://www.fphcare.com/nz/hospital/adult-respiratory/optiflow/airspiral-tube-for-airvo-2/"]}'::jsonb
WHERE slug = 'circuito-airvo-spiral-ref-900pt561-fisher-paykel';

UPDATE public.productos SET
  nombre_es = 'Circuito adulto de doble rama Evaqua 2 con línea de presión RT385 Fisher & Paykel',
  nombre_en = 'Fisher & Paykel RT385 Adult Dual-Limb Evaqua 2 Circuit with Pressure Line',
  descripcion_corta_es = 'Circuito adulto de doble rama Evaqua 2 con línea de presión, presentación de 10.',
  descripcion_corta_en = 'Adult dual-limb Evaqua 2 circuit with pressure line, supplied in packs of 10.',
  descripcion_larga_es = 'El RT385 es un circuito Fisher & Paykel para adulto, de doble rama Evaqua 2 y con línea de presión. La documentación consultada indica presentación de 10. La compatibilidad con la configuración clínica se confirma con documentación vigente del fabricante y en la cotización.',
  descripcion_larga_en = 'The RT385 is a Fisher & Paykel adult dual-limb Evaqua 2 circuit with a pressure line. The reviewed documentation states a pack of 10. Compatibility with the clinical configuration must be confirmed against current manufacturer documentation and in the quotation.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"RT385"},{"clave":"Tipo","grupo":"Configuración","valor":"Circuito adulto de doble rama"},{"clave":"Tecnología","grupo":"Circuito","valor":"Evaqua 2"},{"clave":"Línea","grupo":"Circuito","valor":"Línea de presión"},{"clave":"Presentación","grupo":"Empaque","valor":"10"}]'::jsonb,
  aplicaciones_es = ARRAY['Configuraciones de circuito adulto de doble rama con línea de presión'],
  aplicaciones_en = ARRAY['Adult dual-limb circuit configurations with a pressure line'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"Fisher & Paykel","fabricante":"Fisher & Paykel","ref_proveedor":"RT385","valor_es":"Circuito adulto Evaqua 2 de doble rama con línea de presión.","valor_en":"Adult dual-limb Evaqua 2 circuit with a pressure line.","beneficios_es":["La línea de presión es parte de la configuración descrita.","La tecnología Evaqua 2 identifica la familia del circuito."],"beneficios_en":["The pressure line is part of the described configuration.","Evaqua 2 identifies the circuit family."],"preguntas_frecuentes_es":[{"q":"¿Qué tipo de circuito es el RT385?","a":"Es un circuito adulto de doble rama Evaqua 2 con línea de presión."},{"q":"¿Cuál es su presentación?","a":"La presentación indicada es de 10."},{"q":"¿Se debe confirmar compatibilidad?","a":"Sí. La configuración compatible se confirma con documentación vigente del fabricante y en la cotización."}],"preguntas_frecuentes_en":[{"q":"What type of circuit is the RT385?","a":"It is an adult dual-limb Evaqua 2 circuit with a pressure line."},{"q":"What is its pack size?","a":"The stated pack size is 10."},{"q":"Should compatibility be confirmed?","a":"Yes. Compatible configuration must be confirmed against current manufacturer documentation and in the quotation."}],"seo_keywords_es":["circuito RT385 Evaqua 2","circuito adulto doble rama Fisher Paykel","línea de presión RT385"],"seo_keywords_en":["RT385 Evaqua 2 circuit","Fisher Paykel adult dual limb circuit","RT385 pressure line"],"fuentes_auditoria":["https://www.fphcare.com/en-gb/products/evaqua-breathing-circuits/?lang=en-fph"]}'::jsonb
WHERE slug = 'circuito-desachable-para-adulto-evaqua-con-linea-de-presion-ref-rt385-fisher-paykel';

UPDATE public.productos SET
  nombre_es = 'Circuito infantil de doble calefacción Evaqua 2 con MR290 para SLE5000 RT268 Fisher & Paykel',
  nombre_en = 'Fisher & Paykel RT268 Infant Dual-Heated Evaqua 2 Circuit with MR290 for SLE5000',
  descripcion_corta_es = 'Circuito infantil Evaqua 2 de doble calefacción con MR290 para SLE5000, presentación de 10.',
  descripcion_corta_en = 'Infant dual-heated Evaqua 2 circuit with MR290 for SLE5000, supplied in packs of 10.',
  descripcion_larga_es = 'El RT268 es un circuito infantil Fisher & Paykel de doble calefacción con tecnología Evaqua 2 y cámara MR290, descrito para SLE5000. La documentación consultada indica presentación de 10. La compatibilidad final del equipo y la configuración se confirman con documentación vigente del fabricante y en la cotización.',
  descripcion_larga_en = 'The RT268 is a Fisher & Paykel infant dual-heated circuit with Evaqua 2 technology and an MR290 chamber, described for SLE5000. The reviewed documentation states a pack of 10. Final equipment compatibility and configuration must be confirmed against current manufacturer documentation and in the quotation.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"RT268"},{"clave":"Tipo","grupo":"Configuración","valor":"Circuito infantil de doble calefacción"},{"clave":"Tecnología","grupo":"Circuito","valor":"Evaqua 2"},{"clave":"Cámara descrita","grupo":"Configuración","valor":"MR290"},{"clave":"Equipo descrito","grupo":"Compatibilidad","valor":"SLE5000"},{"clave":"Presentación","grupo":"Empaque","valor":"10"}]'::jsonb,
  aplicaciones_es = ARRAY['Configuración descrita de circuito infantil para SLE5000'],
  aplicaciones_en = ARRAY['Described infant circuit configuration for SLE5000'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"Fisher & Paykel","fabricante":"Fisher & Paykel","ref_proveedor":"RT268","valor_es":"Circuito infantil de doble calefacción Evaqua 2 con MR290, descrito para SLE5000.","valor_en":"Infant dual-heated Evaqua 2 circuit with MR290, described for SLE5000.","beneficios_es":["Identifica una configuración de circuito infantil de doble calefacción.","La referencia integra Evaqua 2 y la cámara MR290 en la configuración publicada."],"beneficios_en":["Identifies an infant dual-heated circuit configuration.","The reference combines Evaqua 2 and the MR290 chamber in the published configuration."],"preguntas_frecuentes_es":[{"q":"¿Para qué equipo se describe el RT268?","a":"La documentación consultada lo describe para SLE5000."},{"q":"¿Qué cámara se indica?","a":"La configuración publicada indica MR290."},{"q":"¿Cuál es su presentación?","a":"La presentación indicada es de 10."}],"preguntas_frecuentes_en":[{"q":"Which device is the RT268 described for?","a":"The reviewed documentation describes it for SLE5000."},{"q":"Which chamber is indicated?","a":"The published configuration indicates MR290."},{"q":"What is its pack size?","a":"The stated pack size is 10."}],"seo_keywords_es":["circuito RT268 Evaqua 2","circuito SLE5000 MR290","circuito infantil Fisher Paykel"],"seo_keywords_en":["RT268 Evaqua 2 circuit","SLE5000 MR290 circuit","Fisher Paykel infant circuit"],"fuentes_auditoria":["https://www.fphcare.com/en-ca/products/rt-series-breathing-circuits/?lang=en-fph","https://www.fphcare.com/en-fp/hospital/infant-respiratory/infants/invasive-ventilation/invasive-circuits/"]}'::jsonb
WHERE slug = 'circuito-desechable-bicalentado-cascada-ref-rt268-fisher-paykel';

UPDATE public.productos SET
  nombre_es = 'Circuito infantil de doble calefacción Evaqua 2 con MR290 para SLE6000 RT269 Fisher & Paykel',
  nombre_en = 'Fisher & Paykel RT269 Infant Dual-Heated Evaqua 2 Circuit with MR290 for SLE6000',
  descripcion_corta_es = 'Circuito infantil Evaqua 2 de doble calefacción con MR290 para SLE6000, presentación de 10.',
  descripcion_corta_en = 'Infant dual-heated Evaqua 2 circuit with MR290 for SLE6000, supplied in packs of 10.',
  descripcion_larga_es = 'El RT269 es un circuito infantil Fisher & Paykel de doble calefacción con tecnología Evaqua 2 y cámara MR290, descrito para SLE6000. La documentación consultada indica presentación de 10. La compatibilidad final del equipo y la configuración se confirman con documentación vigente del fabricante y en la cotización.',
  descripcion_larga_en = 'The RT269 is a Fisher & Paykel infant dual-heated circuit with Evaqua 2 technology and an MR290 chamber, described for SLE6000. The reviewed documentation states a pack of 10. Final equipment compatibility and configuration must be confirmed against current manufacturer documentation and in the quotation.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"RT269"},{"clave":"Tipo","grupo":"Configuración","valor":"Circuito infantil de doble calefacción"},{"clave":"Tecnología","grupo":"Circuito","valor":"Evaqua 2"},{"clave":"Cámara descrita","grupo":"Configuración","valor":"MR290"},{"clave":"Equipo descrito","grupo":"Compatibilidad","valor":"SLE6000"},{"clave":"Presentación","grupo":"Empaque","valor":"10"}]'::jsonb,
  aplicaciones_es = ARRAY['Configuración descrita de circuito infantil para SLE6000'],
  aplicaciones_en = ARRAY['Described infant circuit configuration for SLE6000'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"Fisher & Paykel","fabricante":"Fisher & Paykel","ref_proveedor":"RT269","valor_es":"Circuito infantil de doble calefacción Evaqua 2 con MR290, descrito para SLE6000.","valor_en":"Infant dual-heated Evaqua 2 circuit with MR290, described for SLE6000.","beneficios_es":["Identifica una configuración de circuito infantil de doble calefacción.","La referencia integra Evaqua 2 y la cámara MR290 en la configuración publicada."],"beneficios_en":["Identifies an infant dual-heated circuit configuration.","The reference combines Evaqua 2 and the MR290 chamber in the published configuration."],"preguntas_frecuentes_es":[{"q":"¿Para qué equipo se describe el RT269?","a":"La documentación consultada lo describe para SLE6000."},{"q":"¿Qué cámara se indica?","a":"La configuración publicada indica MR290."},{"q":"¿Cuál es su presentación?","a":"La presentación indicada es de 10."}],"preguntas_frecuentes_en":[{"q":"Which device is the RT269 described for?","a":"The reviewed documentation describes it for SLE6000."},{"q":"Which chamber is indicated?","a":"The published configuration indicates MR290."},{"q":"What is its pack size?","a":"The stated pack size is 10."}],"seo_keywords_es":["circuito RT269 Evaqua 2","circuito SLE6000 MR290","circuito infantil Fisher Paykel"],"seo_keywords_en":["RT269 Evaqua 2 circuit","SLE6000 MR290 circuit","Fisher Paykel infant circuit"],"fuentes_auditoria":["https://www.fphcare.com/en-ca/products/rt-series-breathing-circuits/?lang=en-fph","https://www.fphcare.com/en-fp/hospital/infant-respiratory/infants/invasive-ventilation/invasive-circuits/"]}'::jsonb
WHERE slug = 'circuito-desechable-bicalentado-cascada-ref-rt269-fisher-paykel';

UPDATE public.productos SET
  nombre_es = 'Circuito neonatal de doble calefacción Evaqua 2 con MR290 RT265 Fisher & Paykel',
  nombre_en = 'Fisher & Paykel RT265 Neonatal Dual-Heated Evaqua 2 Circuit with MR290',
  descripcion_corta_es = 'Circuito neonatal Evaqua 2 de doble calefacción con MR290 para flujos superiores a 4 L/min, presentación de 10.',
  descripcion_corta_en = 'Neonatal dual-heated Evaqua 2 circuit with MR290 for flows above 4 L/min, supplied in packs of 10.',
  descripcion_larga_es = 'El RT265 es un circuito neonatal Fisher & Paykel de doble calefacción con tecnología Evaqua 2 y cámara MR290, descrito para flujos superiores a 4 L/min. La documentación consultada indica presentación de 10. La compatibilidad y configuración final se confirman con documentación vigente del fabricante y en la cotización.',
  descripcion_larga_en = 'The RT265 is a Fisher & Paykel neonatal dual-heated circuit with Evaqua 2 technology and an MR290 chamber, described for flows above 4 L/min. The reviewed documentation states a pack of 10. Final compatibility and configuration must be confirmed against current manufacturer documentation and in the quotation.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"RT265"},{"clave":"Tipo","grupo":"Configuración","valor":"Circuito neonatal de doble calefacción"},{"clave":"Tecnología","grupo":"Circuito","valor":"Evaqua 2"},{"clave":"Cámara descrita","grupo":"Configuración","valor":"MR290"},{"clave":"Flujo descrito","grupo":"Uso","valor":"Superior a 4 L/min"},{"clave":"Presentación","grupo":"Empaque","valor":"10"}]'::jsonb,
  aplicaciones_es = ARRAY['Configuración neonatal descrita para flujos superiores a 4 L/min'],
  aplicaciones_en = ARRAY['Described neonatal configuration for flows above 4 L/min'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"Fisher & Paykel","fabricante":"Fisher & Paykel","ref_proveedor":"RT265","valor_es":"Circuito neonatal de doble calefacción Evaqua 2 con MR290 para flujos superiores a 4 L/min.","valor_en":"Neonatal dual-heated Evaqua 2 circuit with MR290 for flows above 4 L/min.","beneficios_es":["La configuración publicada integra Evaqua 2 y cámara MR290.","El rango de flujo descrito facilita identificar la referencia para la configuración requerida."],"beneficios_en":["The published configuration combines Evaqua 2 and an MR290 chamber.","The stated flow condition helps identify the reference for the required configuration."],"preguntas_frecuentes_es":[{"q":"¿Para qué flujo se describe el RT265?","a":"La documentación consultada lo describe para flujos superiores a 4 L/min."},{"q":"¿Qué cámara se indica?","a":"La configuración publicada indica MR290."},{"q":"¿Cuál es su presentación?","a":"La presentación indicada es de 10."}],"preguntas_frecuentes_en":[{"q":"Which flow is the RT265 described for?","a":"The reviewed documentation describes it for flows above 4 L/min."},{"q":"Which chamber is indicated?","a":"The published configuration indicates MR290."},{"q":"What is its pack size?","a":"The stated pack size is 10."}],"seo_keywords_es":["circuito RT265 Evaqua 2","circuito neonatal MR290","circuito Fisher Paykel 4 L min"],"seo_keywords_en":["RT265 Evaqua 2 circuit","MR290 neonatal circuit","Fisher Paykel circuit 4 L min"],"fuentes_auditoria":["https://www.fphcare.com/en-ca/products/rt-series-breathing-circuits/?lang=en-fph","https://www.fphcare.com/en-fp/hospital/infant-respiratory/infants/invasive-ventilation/invasive-circuits/"]}'::jsonb
WHERE slug = 'circuito-desechable-neonatal-bical-cascada-evaqua-2-ref-rt265-fisher-paykel';

UPDATE public.productos SET
  nombre_es = 'Circuito inspiratorio adulto calefaccionado con MR290 RT202 Fisher & Paykel',
  nombre_en = 'Fisher & Paykel RT202 Adult Heated Inspiratory Circuit with MR290',
  descripcion_corta_es = 'Circuito inspiratorio adulto calefaccionado con cámara MR290 de llenado automático, presentación de 10.',
  descripcion_corta_en = 'Adult heated inspiratory circuit with an MR290 auto-fill chamber, supplied in packs of 10.',
  descripcion_larga_es = 'El RT202 es un circuito inspiratorio adulto calefaccionado Fisher & Paykel con cámara MR290 de llenado automático. La documentación consultada indica presentación de 10. La compatibilidad de la configuración se confirma con documentación vigente del fabricante y en la cotización.',
  descripcion_larga_en = 'The RT202 is a Fisher & Paykel adult heated inspiratory circuit with an MR290 auto-fill chamber. The reviewed documentation states a pack of 10. Configuration compatibility must be confirmed against current manufacturer documentation and in the quotation.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"RT202"},{"clave":"Tipo","grupo":"Configuración","valor":"Circuito inspiratorio adulto calefaccionado"},{"clave":"Cámara descrita","grupo":"Configuración","valor":"MR290 de llenado automático"},{"clave":"Presentación","grupo":"Empaque","valor":"10"}]'::jsonb,
  aplicaciones_es = ARRAY['Configuraciones adultas con circuito inspiratorio calefaccionado y cámara MR290'],
  aplicaciones_en = ARRAY['Adult configurations with a heated inspiratory circuit and MR290 chamber'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"Fisher & Paykel","fabricante":"Fisher & Paykel","ref_proveedor":"RT202","valor_es":"Circuito inspiratorio adulto calefaccionado con cámara MR290 de llenado automático.","valor_en":"Adult heated inspiratory circuit with an MR290 auto-fill chamber.","beneficios_es":["Identifica una configuración de circuito inspiratorio adulto calefaccionado.","La cámara MR290 de llenado automático forma parte de la configuración publicada."],"beneficios_en":["Identifies an adult heated inspiratory circuit configuration.","The MR290 auto-fill chamber is part of the published configuration."],"preguntas_frecuentes_es":[{"q":"¿Qué tipo de circuito es el RT202?","a":"Es un circuito inspiratorio adulto calefaccionado."},{"q":"¿Qué cámara se indica?","a":"La configuración publicada indica una MR290 de llenado automático."},{"q":"¿Cuál es su presentación?","a":"La presentación indicada es de 10."}],"preguntas_frecuentes_en":[{"q":"What type of circuit is the RT202?","a":"It is an adult heated inspiratory circuit."},{"q":"Which chamber is indicated?","a":"The published configuration indicates an MR290 auto-fill chamber."},{"q":"What is its pack size?","a":"The stated pack size is 10."}],"seo_keywords_es":["circuito RT202 MR290","circuito inspiratorio adulto Fisher Paykel","circuito calefaccionado RT202"],"seo_keywords_en":["RT202 MR290 circuit","Fisher Paykel adult inspiratory circuit","RT202 heated circuit"],"fuentes_auditoria":["https://www.fphcare.com/en-ca/products/rt-series-breathing-circuits/?lang=en-fph"]}'::jsonb
WHERE slug = 'circuito-desechable-para-canula-de-alto-flujo-adulto-ref-rt202-fisher-paykel';

UPDATE public.productos SET
  nombre_es = 'Kit de circuito Optiflow Junior para ventilador con MR850 RT331 Fisher & Paykel',
  nombre_en = 'Fisher & Paykel RT331 Optiflow Junior Ventilator Circuit Kit with MR850',
  descripcion_corta_es = 'Kit de circuito Optiflow Junior para ventilador con MR850, presentación de 10.',
  descripcion_corta_en = 'Optiflow Junior ventilator circuit kit with MR850, supplied in packs of 10.',
  descripcion_larga_es = 'El RT331 es un kit de circuito Optiflow Junior Fisher & Paykel para ventilador, descrito con humidificador MR850. La documentación consultada indica presentación de 10. La compatibilidad final de los componentes se confirma con documentación vigente del fabricante y en la cotización.',
  descripcion_larga_en = 'The RT331 is a Fisher & Paykel Optiflow Junior ventilator circuit kit described with an MR850 humidifier. The reviewed documentation states a pack of 10. Final component compatibility must be confirmed against current manufacturer documentation and in the quotation.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"RT331"},{"clave":"Tipo","grupo":"Configuración","valor":"Kit de circuito Optiflow Junior para ventilador"},{"clave":"Humidificador descrito","grupo":"Configuración","valor":"MR850"},{"clave":"Presentación","grupo":"Empaque","valor":"10"}]'::jsonb,
  aplicaciones_es = ARRAY['Configuración de ventilador con kit de circuito Optiflow Junior y MR850'],
  aplicaciones_en = ARRAY['Ventilator configuration with the Optiflow Junior circuit kit and MR850'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"Fisher & Paykel","fabricante":"Fisher & Paykel","ref_proveedor":"RT331","valor_es":"Kit de circuito Optiflow Junior para ventilador con MR850.","valor_en":"Optiflow Junior ventilator circuit kit with MR850.","beneficios_es":["Identifica el kit de circuito para la configuración descrita de ventilador.","El humidificador MR850 está indicado en la configuración publicada."],"beneficios_en":["Identifies the circuit kit for the described ventilator configuration.","The MR850 humidifier is indicated in the published configuration."],"preguntas_frecuentes_es":[{"q":"¿Qué tipo de kit es el RT331?","a":"Es un kit de circuito Optiflow Junior para ventilador."},{"q":"¿Qué humidificador se indica?","a":"La configuración publicada indica MR850."},{"q":"¿Cuál es su presentación?","a":"La presentación indicada es de 10."}],"preguntas_frecuentes_en":[{"q":"What type of kit is the RT331?","a":"It is an Optiflow Junior ventilator circuit kit."},{"q":"Which humidifier is indicated?","a":"The published configuration indicates MR850."},{"q":"What is its pack size?","a":"The stated pack size is 10."}],"seo_keywords_es":["kit circuito RT331","Optiflow Junior MR850","circuito ventilador Fisher Paykel"],"seo_keywords_en":["RT331 circuit kit","Optiflow Junior MR850","Fisher Paykel ventilator circuit"],"fuentes_auditoria":["https://www.fphcare.com/en-gb/products/optiflow-junior-breathing-circuit/"]}'::jsonb
WHERE slug = 'circuito-optiflow-junior-para-ventilador-ref-rt331-fisher-paykel';

UPDATE public.productos SET
  nombre_es = 'Kit mezclador Optiflow Junior con MR850 y MR290 RT330 Fisher & Paykel',
  nombre_en = 'Fisher & Paykel RT330 Optiflow Junior Blender Kit with MR850 and MR290',
  descripcion_corta_es = 'Kit mezclador Optiflow Junior con MR850, MR290 y circuito de 1,75 m; presentación de 10.',
  descripcion_corta_en = 'Optiflow Junior blender kit with MR850, MR290 and a 1.75 m circuit; supplied in packs of 10.',
  descripcion_larga_es = 'El RT330 es un kit mezclador Optiflow Junior Fisher & Paykel, descrito con humidificador MR850, cámara MR290 y circuito de 1,75 m. La documentación consultada indica presentación de 10. La compatibilidad final de los componentes se confirma con documentación vigente del fabricante y en la cotización.',
  descripcion_larga_en = 'The RT330 is a Fisher & Paykel Optiflow Junior blender kit described with an MR850 humidifier, MR290 chamber and a 1.75 m circuit. The reviewed documentation states a pack of 10. Final component compatibility must be confirmed against current manufacturer documentation and in the quotation.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"RT330"},{"clave":"Tipo","grupo":"Configuración","valor":"Kit mezclador Optiflow Junior"},{"clave":"Humidificador descrito","grupo":"Configuración","valor":"MR850"},{"clave":"Cámara descrita","grupo":"Configuración","valor":"MR290"},{"clave":"Longitud de circuito","grupo":"Configuración","valor":"1,75 m"},{"clave":"Presentación","grupo":"Empaque","valor":"10"}]'::jsonb,
  aplicaciones_es = ARRAY['Configuración Optiflow Junior con kit mezclador, MR850 y MR290'],
  aplicaciones_en = ARRAY['Optiflow Junior configuration with the blender kit, MR850 and MR290'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"Fisher & Paykel","fabricante":"Fisher & Paykel","ref_proveedor":"RT330","valor_es":"Kit mezclador Optiflow Junior con MR850, MR290 y circuito de 1,75 m.","valor_en":"Optiflow Junior blender kit with MR850, MR290 and a 1.75 m circuit.","beneficios_es":["Identifica los componentes publicados para la configuración Optiflow Junior.","La longitud de circuito indicada facilita confirmar la referencia requerida."],"beneficios_en":["Identifies the published components for the Optiflow Junior configuration.","The stated circuit length helps confirm the required reference."],"preguntas_frecuentes_es":[{"q":"¿Qué componentes se describen para el RT330?","a":"Se describen MR850, MR290 y un circuito de 1,75 m."},{"q":"¿Qué tipo de kit es?","a":"Es un kit mezclador Optiflow Junior."},{"q":"¿Cuál es su presentación?","a":"La presentación indicada es de 10."}],"preguntas_frecuentes_en":[{"q":"Which components are described for the RT330?","a":"MR850, MR290 and a 1.75 m circuit are described."},{"q":"What type of kit is it?","a":"It is an Optiflow Junior blender kit."},{"q":"What is its pack size?","a":"The stated pack size is 10."}],"seo_keywords_es":["kit RT330 Optiflow Junior","MR850 MR290 circuito 1.75 m","mezclador Fisher Paykel"],"seo_keywords_en":["RT330 Optiflow Junior kit","MR850 MR290 1.75 m circuit","Fisher Paykel blender"],"fuentes_auditoria":["https://www.fphcare.com/en-gb/products/optiflow-junior-breathing-circuit/"]}'::jsonb
WHERE slug = 'circuito-para-alto-flujo-optiflow-junior-ref-rt330-fisher-paykel';

UPDATE public.productos SET
  nombre_es = 'Sensor de flujo de un solo uso N5302/05 SLE',
  nombre_en = 'SLE N5302/05 Single-Use Flow Sensor',
  descripcion_corta_es = 'Sensor de flujo de un solo uso SLE de dos hilos calientes, 10 mm.',
  descripcion_corta_en = 'SLE single-use dual hot-wire flow sensor, 10 mm.',
  descripcion_larga_es = 'El N5302/05 es un sensor de flujo SLE de un solo uso con dos hilos calientes. La especificación consultada indica diámetro de 10 mm, rango de flujo de 0,2 a 30 L/min y espacio muerto de 1 ml. La selección y compatibilidad con la configuración del ventilador se confirman con documentación vigente del fabricante y en la cotización.',
  descripcion_larga_en = 'The N5302/05 is an SLE single-use flow sensor with dual hot wires. The reviewed specification states a 10 mm diameter, a 0.2 to 30 L/min flow range and 1 ml dead space. Selection and compatibility with the ventilator configuration must be confirmed against current manufacturer documentation and in the quotation.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"N5302/05"},{"clave":"Tipo","grupo":"Uso","valor":"Sensor de flujo de un solo uso"},{"clave":"Tecnología","grupo":"Medición","valor":"Dos hilos calientes"},{"clave":"Diámetro","grupo":"Dimensiones","valor":"10 mm"},{"clave":"Rango de flujo","grupo":"Medición","valor":"0,2–30 L/min"},{"clave":"Espacio muerto","grupo":"Dimensiones","valor":"1 ml"}]'::jsonb,
  aplicaciones_es = ARRAY['Medición de flujo en configuraciones de ventilador compatibles'],
  aplicaciones_en = ARRAY['Flow measurement in compatible ventilator configurations'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"SLE","fabricante":"SLE","ref_proveedor":"N5302/05","valor_es":"Sensor de flujo de un solo uso de dos hilos calientes, con rango de 0,2 a 30 L/min.","valor_en":"Single-use dual hot-wire flow sensor with a 0.2 to 30 L/min range.","beneficios_es":["La configuración de dos hilos calientes identifica la tecnología de medición publicada.","El rango de flujo y espacio muerto publicados ayudan a verificar la referencia requerida."],"beneficios_en":["The dual hot-wire configuration identifies the published measurement technology.","The published flow range and dead space help verify the required reference."],"preguntas_frecuentes_es":[{"q":"¿El N5302/05 es reusable?","a":"No. La especificación consultada lo identifica como sensor de un solo uso."},{"q":"¿Cuál es su rango de flujo?","a":"La especificación indica de 0,2 a 30 L/min."},{"q":"¿Cuál es el espacio muerto indicado?","a":"La especificación indica 1 ml."}],"preguntas_frecuentes_en":[{"q":"Is the N5302/05 reusable?","a":"No. The reviewed specification identifies it as a single-use sensor."},{"q":"What is its flow range?","a":"The specification states 0.2 to 30 L/min."},{"q":"What is its stated dead space?","a":"The specification states 1 ml."}],"seo_keywords_es":["sensor flujo N5302 05 SLE","sensor desechable doble hilo caliente","sensor flujo 0.2 30 L min"],"seo_keywords_en":["SLE N5302 05 flow sensor","single use dual hot wire sensor","0.2 30 L min flow sensor"],"fuentes_auditoria":["https://inspirationhealthcaregroup.com/wp-content/uploads/2023/02/SLE6000-specifications.pdf"]}'::jsonb
WHERE slug = 'sensor-de-flujo-desechable-ref-n5302-05-sle';

UPDATE public.productos SET
  nombre_es = 'Sensor de flujo reusable N5402 SLE',
  nombre_en = 'SLE N5402 Reusable Flow Sensor',
  descripcion_corta_es = 'Sensor de flujo reusable SLE de dos hilos calientes, 10 mm.',
  descripcion_corta_en = 'SLE reusable dual hot-wire flow sensor, 10 mm.',
  descripcion_larga_es = 'El N5402 es un sensor de flujo reusable SLE con dos hilos calientes. La especificación consultada indica diámetro de 10 mm, rango de flujo de 0,2 a 30 L/min y espacio muerto de 1 ml. La selección y compatibilidad con la configuración del ventilador se confirman con documentación vigente del fabricante y en la cotización.',
  descripcion_larga_en = 'The N5402 is an SLE reusable flow sensor with dual hot wires. The reviewed specification states a 10 mm diameter, a 0.2 to 30 L/min flow range and 1 ml dead space. Selection and compatibility with the ventilator configuration must be confirmed against current manufacturer documentation and in the quotation.',
  especificaciones = '[{"clave":"Referencia","grupo":"Identificación","valor":"N5402"},{"clave":"Tipo","grupo":"Uso","valor":"Sensor de flujo reusable"},{"clave":"Tecnología","grupo":"Medición","valor":"Dos hilos calientes"},{"clave":"Diámetro","grupo":"Dimensiones","valor":"10 mm"},{"clave":"Rango de flujo","grupo":"Medición","valor":"0,2–30 L/min"},{"clave":"Espacio muerto","grupo":"Dimensiones","valor":"1 ml"}]'::jsonb,
  aplicaciones_es = ARRAY['Medición de flujo en configuraciones de ventilador compatibles'],
  aplicaciones_en = ARRAY['Flow measurement in compatible ventilator configurations'],
  atributos = COALESCE(atributos, '{}'::jsonb) || '{"marca":"SLE","fabricante":"SLE","ref_proveedor":"N5402","valor_es":"Sensor de flujo reusable de dos hilos calientes, con rango de 0,2 a 30 L/min.","valor_en":"Reusable dual hot-wire flow sensor with a 0.2 to 30 L/min range.","beneficios_es":["La configuración de dos hilos calientes identifica la tecnología de medición publicada.","El rango de flujo y espacio muerto publicados ayudan a verificar la referencia requerida."],"beneficios_en":["The dual hot-wire configuration identifies the published measurement technology.","The published flow range and dead space help verify the required reference."],"preguntas_frecuentes_es":[{"q":"¿El N5402 es de un solo uso?","a":"No. La especificación consultada lo identifica como sensor reusable."},{"q":"¿Cuál es su rango de flujo?","a":"La especificación indica de 0,2 a 30 L/min."},{"q":"¿Cuál es el espacio muerto indicado?","a":"La especificación indica 1 ml."}],"preguntas_frecuentes_en":[{"q":"Is the N5402 single use?","a":"No. The reviewed specification identifies it as a reusable sensor."},{"q":"What is its flow range?","a":"The specification states 0.2 to 30 L/min."},{"q":"What is its stated dead space?","a":"The specification states 1 ml."}],"seo_keywords_es":["sensor flujo N5402 SLE","sensor reusable doble hilo caliente","sensor flujo 0.2 30 L min"],"seo_keywords_en":["SLE N5402 flow sensor","reusable dual hot wire sensor","0.2 30 L min flow sensor"],"fuentes_auditoria":["https://inspirationhealthcaregroup.com/wp-content/uploads/2023/02/SLE6000-specifications.pdf"]}'::jsonb
WHERE slug = 'sensor-de-flujo-reusable-ref-n5402-sle';
