-- Enriquecimiento de landings desde fichas técnicas oficiales del fabricante (konfort-plus-hogar-ortopedia).
-- Contenido redactado solo con datos presentes en la ficha; ver informe docs/informe-fichas-fabricantes-2026-10-02.md.
-- Se aplica con el workflow manual "Deploy Supabase Migrations". Idempotente (UPDATE por slug).

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kb215sr-al-ft.pdf',
  descripcion_larga_es = $d$El Cómodo Sanitario Plegable en Aluminio  KB215SR-AL está diseñado para ofrecer una solución segura y cómoda a usuarios con dificultades para el desplazamiento, facilitando las rutinas de higiene diaria. Fabricado en aluminio ligero con un acabado anodizado natural, este cómodo es resistente a la corrosión y fácil de manejar. Su diseño plegable lo hace ideal para espacios reducidos, permitiendo un almacenamiento y transporte sencillos.

El cómodo sanitario plegable Konfort Plus en aluminio anodizado, sin ruedas, está fabricado en aluminio ligero con acabado anodizado natural y diseño plegable que da estabilidad y seguridad al usuario. Tiene asiento de 43 x 43 cm, respaldo de nailon, apoyabrazos de 24 cm de alto, soporta 100 kg y consta de asiento, respaldo, balde y estructura principal.$d$,
  descripcion_larga_en = $d$The Konfort Plus Folding Commode Chair KB215SR-AL is designed to offer a safe and comfortable solution for users with mobility difficulties, facilitating daily hygiene routines. Made from lightweight aluminum with a natural anodized finish, this commode is corrosion-resistant and easy to handle. Its foldable design makes it ideal for compact spaces, allowing simple storage and transport.

The Konfort Plus foldable commode in anodised aluminium, without wheels, is made of lightweight aluminium with a natural anodised finish and a folding design that provides stability and safety. It has a 43 x 43 cm seat, nylon backrest, 24 cm armrests, supports 100 kg and consists of seat, backrest, bucket and main frame.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KB215SR-AL"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"100 kg"},{"clave":"Asiento","grupo":"Dimensiones","valor":"43 x 43 cm"},{"clave":"Estructura","grupo":"Material","valor":"Aluminio anodizado"},{"clave":"Componentes","grupo":"Partes","valor":"Asiento, respaldo, balde, estructura principal"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Aluminio ligero con acabado anodizado y diseño plegable.","Asiento de 43 x 43 cm, respaldo de nailon y capacidad de 100 kg.","Incluye balde; sin ruedas, con tapones para mayor estabilidad."],"beneficios_en":["Lightweight aluminium with anodised finish and folding design.","43 x 43 cm seat, nylon backrest and 100 kg capacity.","Bucket included; no wheels, with tips for greater stability."],"valor_es":"Un cómodo sanitario plegable de aluminio de 100 kg.","valor_en":"A 100 kg foldable aluminium commode.","preguntas_frecuentes_es":[{"q":"¿Qué peso soporta?","a":"100 kg."},{"q":"¿Se pliega?","a":"Sí, es plegable."},{"q":"¿Tiene ruedas?","a":"No, esta versión usa tapones."},{"q":"¿Dónde descargo la ficha técnica de Cómodo Sanitario En Aluminio Anodizado Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What weight does it support?","a":"100 kg."},{"q":"Does it fold?","a":"Yes, it is foldable."},{"q":"Does it have wheels?","a":"No, this version uses tips."},{"q":"Where can I download the Konfort Plus Folding Commode Chair Aluminum Anodized datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["cómodo sanitario plegable de aluminio","silla sanitaria plegable","cómodo sin ruedas","cómodo Konfort Plus","sillas sanitarias Colombia","ficha técnica KB215SR-AL"],"seo_keywords_en":["foldable aluminium commode","folding commode chair","wheel-less commode","Konfort Plus commode","commode chairs Colombia","KB215SR-AL datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCARGCXLIW5FG3NHP34AICCSA3MM?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'comodo-sanitario-en-aluminio-anodizado-ref-kb215sr-al-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kb225cr-al19-ft.pdf',
  descripcion_larga_es = $d$El Cómodo Sanitario Plegable en Aluminio con ruedas KB225CR-AL19 está especialmente diseñado para brindar apoyo a personas con movilidad reducida, ofreciendo un equilibrio perfecto entre funcionalidad y confort. Con una estructura de aluminio pintado, este cómodo combina ligereza con durabilidad, siendo resistente a la corrosión y fácil de manejar.

El cómodo sanitario plegable con ruedas Konfort Plus en aluminio anodizado tiene ruedas macizas de 4", asiento de 43 x 43 cm, respaldo de nailon y capacidad de 100 kg. Consta de asiento, respaldo, balde y estructura principal, y está clasificado clase I (riesgo bajo) con registro sanitario 2018DM-0018624.$d$,
  descripcion_larga_en = $d$The Konfort Plus Folding Commode Chair on Wheels KB225CR-AL19 is specially designed to support individuals with reduced mobility, offering a perfect balance between functionality and comfort. With a painted aluminum structure, this commode combines lightweight construction with durability, being corrosion-resistant and easy to handle. Its foldable design optimizes space in clinical and home environments. Integrated wheels facilitate movement within the home or institution.

The Konfort Plus foldable commode with wheels in anodised aluminium has 4" solid wheels, a 43 x 43 cm seat, nylon backrest and 100 kg capacity. It consists of seat, backrest, bucket and main frame, and is class I (low risk) with health registration 2018DM-0018624.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KB225CR-AL19"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"100 kg"},{"clave":"Asiento","grupo":"Dimensiones","valor":"43 x 43 cm"},{"clave":"Ruedas","grupo":"Ruedas","valor":"Macizas de 4\""},{"clave":"Registro sanitario","grupo":"Regulatorio","valor":"2018DM-0018624; clase I"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Ruedas macizas de 4\" para desplazarlo fácilmente.","Estructura de aluminio anodizado plegable con capacidad de 100 kg.","Asiento de 43 x 43 cm con balde incluido."],"beneficios_en":["4\" solid wheels to move it easily.","Foldable anodised aluminium frame with 100 kg capacity.","43 x 43 cm seat with bucket included."],"valor_es":"Un cómodo sanitario plegable con ruedas de 4\" y capacidad de 100 kg.","valor_en":"A foldable commode with 4\" wheels and 100 kg capacity.","preguntas_frecuentes_es":[{"q":"¿Qué peso soporta?","a":"100 kg."},{"q":"¿Qué ruedas tiene?","a":"Ruedas macizas de 4\"."},{"q":"¿Qué registro sanitario tiene?","a":"2018DM-0018624, clase I (riesgo bajo)."},{"q":"¿Dónde descargo la ficha técnica de Cómodo Sanitario En Aluminio Anodizado Con Ruedas Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What weight does it support?","a":"100 kg."},{"q":"Which wheels does it have?","a":"4\" solid wheels."},{"q":"What health registration does it have?","a":"2018DM-0018624, class I (low risk)."},{"q":"Where can I download the Konfort Plus Folding Commode Chair on Wheels Aluminum Anodized datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["cómodo sanitario con ruedas aluminio anodizado","silla sanitaria con ruedas","cómodo plegable con ruedas","cómodo Konfort Plus","sillas sanitarias Colombia","ficha técnica KB225CR-AL19"],"seo_keywords_en":["commode with wheels anodised aluminium","wheeled commode chair","folding commode with wheels","Konfort Plus commode","commode chairs Colombia","KB225CR-AL19 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCW4D7374W3ZHIFCV4M5U2DAUTLE?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'comodo-sanitario-en-aluminio-anodizado-con-ruedas-ref-kb225cr-al19-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kb225cr-ap1-ft.pdf',
  descripcion_larga_es = $d$El Cómodo Sanitario Plegable con Ruedas de Acero Pintado  KB225CR-AP1 está diseñado para proporcionar un soporte robusto y seguro a personas con dificultades para el desplazamiento. Su estructura en acero pintado ofrece durabilidad y estabilidad, mientras que su diseño plegable facilita el almacenamiento y el transporte en espacios reducidos. Equipado con ruedas macizas de 4 pulgadas, garantiza una movilidad suave y segura en interiores, sin necesidad de mantenimiento.

El cómodo sanitario plegable con ruedas Konfort Plus en acero pintado tiene ruedas macizas de 4", asiento de 43 x 43 cm, respaldo de nailon y capacidad de 100 kg. Consta de asiento, respaldo, balde y estructura principal, y está clasificado clase I (riesgo bajo) con registro sanitario 2018DM-0018624.$d$,
  descripcion_larga_en = $d$The KB225CR-AP1 commode chair is designed to provide robust and secure support for individuals with limited mobility. Its painted steel structure ensures durability and stability, while the foldable design facilitates storage and transport in confined spaces. Equipped with 4-inch solid wheels, it guarantees smooth and safe indoor mobility without requiring maintenance.

The Konfort Plus foldable commode with wheels in painted steel has 4" solid wheels, a 43 x 43 cm seat, nylon backrest and 100 kg capacity. It consists of seat, backrest, bucket and main frame, and is class I (low risk) with health registration 2018DM-0018624.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KB225CR-AP1"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"100 kg"},{"clave":"Asiento","grupo":"Dimensiones","valor":"43 x 43 cm"},{"clave":"Ruedas","grupo":"Ruedas","valor":"Macizas de 4\""},{"clave":"Registro sanitario","grupo":"Regulatorio","valor":"2018DM-0018624; clase I"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Ruedas macizas de 4\" para desplazarlo fácilmente.","Estructura de acero pintado plegable con capacidad de 100 kg.","Asiento de 43 x 43 cm con balde incluido."],"beneficios_en":["4\" solid wheels to move it easily.","Foldable painted steel frame with 100 kg capacity.","43 x 43 cm seat with bucket included."],"valor_es":"Un cómodo sanitario plegable con ruedas de 4\" y capacidad de 100 kg.","valor_en":"A foldable commode with 4\" wheels and 100 kg capacity.","preguntas_frecuentes_es":[{"q":"¿Qué peso soporta?","a":"100 kg."},{"q":"¿Qué ruedas tiene?","a":"Ruedas macizas de 4\"."},{"q":"¿Qué registro sanitario tiene?","a":"2018DM-0018624, clase I (riesgo bajo)."},{"q":"¿Dónde descargo la ficha técnica de Cómodo Sanitario En Acero Pintado Con Ruedas Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What weight does it support?","a":"100 kg."},{"q":"Which wheels does it have?","a":"4\" solid wheels."},{"q":"What health registration does it have?","a":"2018DM-0018624, class I (low risk)."},{"q":"Where can I download the Painted Steel Commode Chair With Wheels Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["cómodo sanitario con ruedas acero pintado","silla sanitaria con ruedas","cómodo plegable con ruedas","cómodo Konfort Plus","sillas sanitarias Colombia","ficha técnica KB225CR-AP1"],"seo_keywords_en":["commode with wheels painted steel","wheeled commode chair","folding commode with wheels","Konfort Plus commode","commode chairs Colombia","KB225CR-AP1 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCRXQKRP7TI5C25DJSQNTWCMBUSY?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'comodo-sanitario-en-acero-pintado-con-ruedas-ref-kb225cr-ap1-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp2-6543cr-al19-ft.pdf',
  descripcion_larga_es = $d$El Cómodo Sanitario Plegable con Ruedas de Aluminio KP2-6543CR-AL19 está diseñado para brindar un soporte seguro y cómodo a personas con dificultades para el desplazamiento. Fabricado en aluminio pintado, este cómodo sanitario es ligero, resistente y fácil de manejar. Su diseño plegable lo hace ideal para espacios reducidos, permitiendo un almacenamiento y transporte sencillos. Equipado con ruedas de 3,8 pulgadas de plástico, facilita la movilidad en interiores sin esfuerzo.

El cómodo sanitario de aluminio con ruedas de 120 kg Konfort Plus tiene estructura de aluminio pintado, aro plástico, respaldo de tela lavable, balde con tapa y extensión con rueda y freno. Mide entre 97 y 102 cm de alto, tiene asiento de 43 x 43 cm y es clase I (riesgo bajo) con registro 2018DM-0018624.$d$,
  descripcion_larga_en = $d$The Konfort Plus Folding Commode Chair on Wheels KP2-6543CR-AL19 is designed to provide safe and comfortable support for individuals with mobility difficulties. Constructed from painted aluminum, this commode is lightweight, durable, and easy to handle. Its foldable design makes it ideal for compact spaces, allowing simple storage and transport. Equipped with 3.8-inch plastic wheels, it facilitates effortless indoor mobility.

The Konfort Plus 120 kg aluminium commode with wheels has a painted aluminium frame, plastic ring seat, washable fabric backrest, a bucket with lid and an extension with wheel and brake. It stands 97 to 102 cm high, has a 43 x 43 cm seat and is class I (low risk) with registration 2018DM-0018624.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP2-6543CR-AL19"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"120 kg"},{"clave":"Altura","grupo":"Dimensiones","valor":"97 - 102 cm"},{"clave":"Ruedas","grupo":"Ruedas","valor":"3,8\" de plástico"},{"clave":"Registro sanitario","grupo":"Regulatorio","valor":"2018DM-0018624; clase I"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Capacidad de 120 kg sobre estructura de aluminio pintado.","Respaldo de tela lavable, aro plástico y balde con tapa.","Extensión con rueda y freno; altura de 97 a 102 cm."],"beneficios_en":["120 kg capacity on a painted aluminium frame.","Washable fabric backrest, plastic ring and bucket with lid.","Extension with wheel and brake; height from 97 to 102 cm."],"valor_es":"Un cómodo sanitario con ruedas para pacientes de hasta 120 kg.","valor_en":"A commode with wheels for patients up to 120 kg.","preguntas_frecuentes_es":[{"q":"¿Qué peso soporta?","a":"120 kg."},{"q":"¿Tiene tapa el balde?","a":"Sí, balde con tapa."},{"q":"¿Qué altura tiene?","a":"De 97 a 102 cm."},{"q":"¿Dónde descargo la ficha técnica de Cómodo Sanitario En Aluminio Anodizado Con Ruedas de 120 kg Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What weight does it support?","a":"120 kg."},{"q":"Does the bucket have a lid?","a":"Yes, bucket with lid."},{"q":"What height does it have?","a":"From 97 to 102 cm."},{"q":"Where can I download the Konfort Plus Folding Commode Chair on Wheels 120 kg Aluminum Anodized datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["cómodo sanitario con ruedas 120 kg","silla sanitaria con ruedas de aluminio","cómodo con balde y tapa","cómodo Konfort Plus","sillas sanitarias Colombia","ficha técnica KP2-6543CR-AL19"],"seo_keywords_en":["120 kg commode with wheels","aluminium commode chair with wheels","commode with bucket and lid","Konfort Plus commode","commode chairs Colombia","KP2-6543CR-AL19 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCEHCZYTKRRFDQJFZQFHHK4NWE6A?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'comodo-sanitario-en-aluminio-anodizado-con-ruedas-de-120-kg-ref-kp2-6543cr-al19-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp1-3520l-ft.pdf',
  descripcion_larga_es = $d$La Silla para Ducha con Brazos Konfort Plus está diseñada para ofrecer seguridad y comodidad durante el baño. Fabricada en aluminio, esta silla es ligera y fácil de transportar, además de resistente gracias a su estructura. El asiento y respaldo en polietileno de alta densidad son duraderos y fáciles de limpiar, garantizando una larga vida útil y un mantenimiento sencillo.

La silla para ducha con brazos Konfort Plus es de aluminio desarmable mediante pines y tornillos, con asiento y respaldo de polietileno de alta densidad, altura regulable de 41 a 54 cm, apoyabrazos y capacidad de 130 kg. Pesa 3,2 kg y es clase I (riesgo bajo), con registro sanitario 2018DM-0018624.$d$,
  descripcion_larga_en = $d$The Konfort Plus Shower Chair with Arms is designed to provide safety and comfort during bathing. Constructed from aluminum, this chair is lightweight and easy to transport, while its frame ensures structural resistance. The high-density polyethylene seat and backrest are durable and easy to clean, guaranteeing a long service life and simple maintenance.

The Konfort Plus shower chair with arms is aluminium that can be taken apart with pins and screws, with a high-density polyethylene seat and backrest, adjustable height from 41 to 54 cm, armrests and a 130 kg capacity. It weighs 3.2 kg and is class I (low risk), with health registration 2018DM-0018624.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP1-3520L"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"130 kg"},{"clave":"Peso del producto","grupo":"Peso","valor":"3,2 kg"},{"clave":"Estructura / asiento","grupo":"Material","valor":"Aluminio / polietileno de alta densidad"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Aluminio desarmable, de solo 3,2 kg, fácil de guardar.","Asiento y respaldo de polietileno de alta densidad con brazos.","Altura regulable y capacidad de 130 kg."],"beneficios_en":["Take-apart aluminium, only 3.2 kg, easy to store.","High-density polyethylene seat and backrest with arms.","Adjustable height and 130 kg capacity."],"valor_es":"Una silla de ducha ligera con brazos y capacidad de 130 kg.","valor_en":"A light shower chair with arms and 130 kg capacity.","preguntas_frecuentes_es":[{"q":"¿Qué capacidad tiene?","a":"130 kg."},{"q":"¿Se puede desarmar?","a":"Sí, mediante pines y tornillos."},{"q":"¿De qué material es el asiento?","a":"Polietileno de alta densidad."},{"q":"¿Dónde descargo la ficha técnica de Silla Para Ducha Con Brazos Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What capacity does it have?","a":"130 kg."},{"q":"Can it be taken apart?","a":"Yes, with pins and screws."},{"q":"What is the seat made of?","a":"High-density polyethylene."},{"q":"Where can I download the Konfort Plus Shower Chair with Arms datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["silla para ducha con brazos","silla de baño de aluminio","silla de ducha regulable","silla de ducha Konfort Plus","ayudas para el baño Colombia","ficha técnica KP1-3520L"],"seo_keywords_en":["shower chair with arms","aluminium bath chair","adjustable shower chair","Konfort Plus shower chair","bathroom aids Colombia","KP1-3520L datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MC2RQMZQF2ZVDV5ARA5TBEG3I2KI?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'silla-para-ducha-con-brazos-ref-kp1-3520l-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp3-67034-ft.pdf',
  descripcion_larga_es = $d$El Elevador Sanitario con Seguro y Apoyabrazos está diseñado para proporcionar una solución segura y cómoda a personas con movilidad reducida. Fabricado en resina de polipropileno, este elevador sanitario es duradero, ligero y fácil de limpiar, asegurando una larga vida útil y un mantenimiento sencillo. Equipado con apoyabrazos integrados, ofrece el soporte necesario para facilitar el posicionamiento y el levantamiento del usuario, reduciendo el riesgo de caídas.

El eleva sanitario con seguro y apoyabrazos Konfort Plus está fabricado en resina de polipropileno y facilita el posicionamiento del usuario en el sanitario con el soporte adecuado. Se adapta a sanitarios clásicos, no requiere herramientas para instalarse, tiene mecanismo de ajuste y bloqueo manual seguro y apoyabrazos removibles forrados en espuma. Tiene 2 años de garantía.$d$,
  descripcion_larga_en = $d$The Konfort Plus Toilet Lift with Lock and Armrests is designed to provide a safe and comfortable solution for individuals with reduced mobility. Made from polypropylene resin, this toilet lift is durable, lightweight, and easy to clean, ensuring a long service life and simple maintenance. Equipped with integrated armrests, it provides the necessary support to facilitate user positioning and lifting, reducing the risk of falls.

The Konfort Plus toilet riser with lock and armrests is made of polypropylene resin and makes it easier to position the user on the toilet with the right support. It fits standard toilets, needs no tools to install, has a secure manual adjustment and locking mechanism and removable foam-padded armrests. It has a 2-year warranty.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP3-67034"},{"clave":"Material","grupo":"Material","valor":"Resina de polipropileno"},{"clave":"Instalación","grupo":"Instalación","valor":"Sin herramientas; bloqueo manual"},{"clave":"Garantía","grupo":"Garantía","valor":"2 años"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Se instala sin herramientas en sanitarios clásicos.","Apoyabrazos removibles forrados en espuma y bloqueo manual seguro.","Resina de polipropileno y 2 años de garantía."],"beneficios_en":["Installs without tools on standard toilets.","Removable foam-padded armrests and secure manual lock.","Polypropylene resin and 2-year warranty."],"valor_es":"Un eleva sanitario con apoyabrazos de fácil instalación.","valor_en":"An easy-to-install toilet riser with armrests.","preguntas_frecuentes_es":[{"q":"¿Necesita herramientas?","a":"No, es de fácil instalación sin herramientas."},{"q":"¿Con qué sanitarios es compatible?","a":"Está diseñado para adaptarse a sanitarios clásicos."},{"q":"¿Qué garantía tiene?","a":"2 años."},{"q":"¿Dónde descargo la ficha técnica de Eleva Sanitario Con Seguro Y Apoyabrazos Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Does it need tools?","a":"No, it installs easily without tools."},{"q":"Which toilets is it compatible with?","a":"It is designed to fit standard toilets."},{"q":"What warranty does it have?","a":"2 years."},{"q":"Where can I download the Konfort Plus Toilet Lift with Lock and Armrests datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["eleva sanitario con apoyabrazos","elevador de inodoro","ayuda para el sanitario","eleva sanitario Konfort Plus","ayudas para el baño Colombia","ficha técnica KP3-67034"],"seo_keywords_en":["toilet riser with armrests","toilet seat raiser","toileting aid","Konfort Plus toilet riser","bathroom aids Colombia","KP3-67034 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCZXPT3KMPHVF4JKDAIPDD3GNNOY?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'eleva-sanitario-con-seguro-y-apoyabrazos-ref-kp3-67034-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp68080-ft.pdf',
  descripcion_larga_es = $d$Las Barras de Seguridad Konfort Plus están diseñadas para proporcionar apoyo y seguridad en el hogar, especialmente en entornos como el baño y la habitación. Fabricadas en acero cromado resistente, ofrecen una solución fiable para personas con movilidad reducida o que requieren mayor estabilidad. Disponibles en cuatro tamaños diferentes (30,48 cm, 40,64 cm, 45,72 cm y 60,96 cm), estas barras pueden ser instaladas en diversos ángulos y direcciones, brindando soporte donde más se necesita.

La barra de seguridad Konfort Plus de 30,48 cm está fabricada en acero cromado y ofrece soporte y seguridad al usuario en el baño y la habitación. Se comercializa en cuatro tamaños (30,48; 40,64; 45,72 y 60,96 cm) y puede instalarse en distintos ángulos y direcciones.$d$,
  descripcion_larga_en = $d$Konfort Plus safety bars are designed to provide support and security at home, especially in environments such as the bathroom and bedroom. Made of durable chrome-plated steel, they offer a reliable solution for individuals with reduced mobility or those requiring greater stability. Available in four sizes (30.48 cm, 40.64 cm, 45.72 cm and 60.96 cm), these bars can be installed at various angles and directions, providing support exactly where needed.

The Konfort Plus 30.48 cm safety bar is made of chrome-plated steel and gives the user support and safety in the bathroom and bedroom. It is sold in four sizes (30.48, 40.64, 45.72 and 60.96 cm) and can be installed at different angles and directions.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP68080"},{"clave":"Largo","grupo":"Dimensiones","valor":"30,48 cm"},{"clave":"Material","grupo":"Material","valor":"Acero cromado"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Acero cromado resistente de 30,48 cm.","Instalable en distintos ángulos y direcciones.","Cuatro tamaños para baño o habitación."],"beneficios_en":["Sturdy chrome-plated steel, 30.48 cm.","Installable at different angles and directions.","Four sizes for bathroom or bedroom."],"valor_es":"Una barra de seguridad de acero cromado en cuatro tamaños.","valor_en":"A chrome steel safety bar in four sizes.","preguntas_frecuentes_es":[{"q":"¿En qué tamaños viene?","a":"30,48; 40,64; 45,72 y 60,96 cm."},{"q":"¿De qué material es?","a":"Acero cromado."},{"q":"¿Dónde se puede instalar?","a":"En el baño y la habitación, en distintos ángulos y direcciones."},{"q":"¿Dónde descargo la ficha técnica de Barra De Seguridad Tamaño - 30.48 cm Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which sizes does it come in?","a":"30.48, 40.64, 45.72 and 60.96 cm."},{"q":"What material is it?","a":"Chrome-plated steel."},{"q":"Where can it be installed?","a":"In the bathroom and bedroom, at different angles and directions."},{"q":"Where can I download the Safety Bar Size - 30.48 cm Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["barra de seguridad 30,48 cm","barra de apoyo para baño","barra de seguridad de acero cromado","barra Konfort Plus","ayudas para el baño Colombia","ficha técnica KP68080"],"seo_keywords_en":["30.48 cm safety bar","bathroom grab bar","chrome steel safety bar","Konfort Plus grab bar","bathroom aids Colombia","KP68080 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCBIOZBQGISFCLRBBAY5OPTKQBTI?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'barra-de-seguridad-tamano-30-48-cm-ref-kp68080-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp68080-ft.pdf',
  descripcion_larga_es = $d$Las Barras de Seguridad Konfort Plus están diseñadas para proporcionar apoyo y seguridad en el hogar, especialmente en entornos como el baño y la habitación. Fabricadas en acero cromado resistente, ofrecen una solución fiable para personas con movilidad reducida o que requieren mayor estabilidad. Disponibles en cuatro tamaños diferentes (30,48 cm, 40,64 cm, 45,72 cm y 60,96 cm), estas barras pueden ser instaladas en diversos ángulos y direcciones, brindando soporte donde más se necesita.

La barra de seguridad Konfort Plus de 40,64 cm está fabricada en acero cromado y ofrece soporte y seguridad al usuario en el baño y la habitación. Se comercializa en cuatro tamaños (30,48; 40,64; 45,72 y 60,96 cm) y puede instalarse en distintos ángulos y direcciones.$d$,
  descripcion_larga_en = $d$Konfort Plus safety bars are designed to provide support and security at home, especially in environments such as the bathroom and bedroom. Made of durable chrome-plated steel, they offer a reliable solution for individuals with reduced mobility or those requiring greater stability. Available in four sizes (30.48 cm, 40.64 cm, 45.72 cm and 60.96 cm), these bars can be installed at various angles and directions, providing support exactly where needed.

The Konfort Plus 40.64 cm safety bar is made of chrome-plated steel and gives the user support and safety in the bathroom and bedroom. It is sold in four sizes (30.48, 40.64, 45.72 and 60.96 cm) and can be installed at different angles and directions.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP68081"},{"clave":"Largo","grupo":"Dimensiones","valor":"40,64 cm"},{"clave":"Material","grupo":"Material","valor":"Acero cromado"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Acero cromado resistente de 40,64 cm.","Instalable en distintos ángulos y direcciones.","Cuatro tamaños para baño o habitación."],"beneficios_en":["Sturdy chrome-plated steel, 40.64 cm.","Installable at different angles and directions.","Four sizes for bathroom or bedroom."],"valor_es":"Una barra de seguridad de acero cromado en cuatro tamaños.","valor_en":"A chrome steel safety bar in four sizes.","preguntas_frecuentes_es":[{"q":"¿En qué tamaños viene?","a":"30,48; 40,64; 45,72 y 60,96 cm."},{"q":"¿De qué material es?","a":"Acero cromado."},{"q":"¿Dónde se puede instalar?","a":"En el baño y la habitación, en distintos ángulos y direcciones."},{"q":"¿Dónde descargo la ficha técnica de Barra De Seguridad Tamaño - 40.64 cm Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which sizes does it come in?","a":"30.48, 40.64, 45.72 and 60.96 cm."},{"q":"What material is it?","a":"Chrome-plated steel."},{"q":"Where can it be installed?","a":"In the bathroom and bedroom, at different angles and directions."},{"q":"Where can I download the Safety Bar Size - 40.64 cm Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["barra de seguridad 40,64 cm","barra de apoyo para baño","barra de seguridad de acero cromado","barra Konfort Plus","ayudas para el baño Colombia","ficha técnica KP68081"],"seo_keywords_en":["40.64 cm safety bar","bathroom grab bar","chrome steel safety bar","Konfort Plus grab bar","bathroom aids Colombia","KP68081 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCBIOZBQGISFCLRBBAY5OPTKQBTI?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'barra-de-seguridad-tamano-40-64-cm-ref-kp68081-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp68080-ft.pdf',
  descripcion_larga_es = $d$Las Barras de Seguridad Konfort Plus están diseñadas para proporcionar apoyo y seguridad en el hogar, especialmente en entornos como el baño y la habitación. Fabricadas en acero cromado resistente, ofrecen una solución fiable para personas con movilidad reducida o que requieren mayor estabilidad. Disponibles en cuatro tamaños diferentes (30,48 cm, 40,64 cm, 45,72 cm y 60,96 cm), estas barras pueden ser instaladas en diversos ángulos y direcciones, brindando soporte donde más se necesita.

La barra de seguridad Konfort Plus de 45,72 cm está fabricada en acero cromado y ofrece soporte y seguridad al usuario en el baño y la habitación. Se comercializa en cuatro tamaños (30,48; 40,64; 45,72 y 60,96 cm) y puede instalarse en distintos ángulos y direcciones.$d$,
  descripcion_larga_en = $d$Konfort Plus safety bars are designed to provide support and security at home, especially in environments such as the bathroom and bedroom. Made of durable chrome-plated steel, they offer a reliable solution for individuals with reduced mobility or those requiring greater stability. Available in four sizes (30.48 cm, 40.64 cm, 45.72 cm and 60.96 cm), these bars can be installed at various angles and directions, providing support exactly where needed.

The Konfort Plus 45.72 cm safety bar is made of chrome-plated steel and gives the user support and safety in the bathroom and bedroom. It is sold in four sizes (30.48, 40.64, 45.72 and 60.96 cm) and can be installed at different angles and directions.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP68082"},{"clave":"Largo","grupo":"Dimensiones","valor":"45,72 cm"},{"clave":"Material","grupo":"Material","valor":"Acero cromado"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Acero cromado resistente de 45,72 cm.","Instalable en distintos ángulos y direcciones.","Cuatro tamaños para baño o habitación."],"beneficios_en":["Sturdy chrome-plated steel, 45.72 cm.","Installable at different angles and directions.","Four sizes for bathroom or bedroom."],"valor_es":"Una barra de seguridad de acero cromado en cuatro tamaños.","valor_en":"A chrome steel safety bar in four sizes.","preguntas_frecuentes_es":[{"q":"¿En qué tamaños viene?","a":"30,48; 40,64; 45,72 y 60,96 cm."},{"q":"¿De qué material es?","a":"Acero cromado."},{"q":"¿Dónde se puede instalar?","a":"En el baño y la habitación, en distintos ángulos y direcciones."},{"q":"¿Dónde descargo la ficha técnica de Barra De Seguridad Tamaño - 45.72 cm Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which sizes does it come in?","a":"30.48, 40.64, 45.72 and 60.96 cm."},{"q":"What material is it?","a":"Chrome-plated steel."},{"q":"Where can it be installed?","a":"In the bathroom and bedroom, at different angles and directions."},{"q":"Where can I download the Safety Bar Size - 45.72 cm Konfort Plus datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["barra de seguridad 45,72 cm","barra de apoyo para baño","barra de seguridad de acero cromado","barra Konfort Plus","ayudas para el baño Colombia","ficha técnica KP68082"],"seo_keywords_en":["45.72 cm safety bar","bathroom grab bar","chrome steel safety bar","Konfort Plus grab bar","bathroom aids Colombia","KP68082 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCBIOZBQGISFCLRBBAY5OPTKQBTI?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'barra-de-seguridad-tamano-45-72-cm-ref-kp68082-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kp68080-ft.pdf',
  descripcion_larga_es = $d$Las Barras de Seguridad Konfort Plus están diseñadas para proporcionar apoyo y seguridad en el hogar, especialmente en entornos como el baño y la habitación. Fabricadas en acero cromado resistente, ofrecen una solución fiable para personas con movilidad reducida o que requieren mayor estabilidad. Disponibles en cuatro tamaños diferentes (30,48 cm, 40,64 cm, 45,72 cm y 60,96 cm), estas barras pueden ser instaladas en diversos ángulos y direcciones, brindando soporte donde más se necesita.

La barra de seguridad Konfort Plus de 60,96 cm está fabricada en acero cromado y ofrece soporte y seguridad al usuario en el baño y la habitación. Se comercializa en cuatro tamaños (30,48; 40,64; 45,72 y 60,96 cm) y puede instalarse en distintos ángulos y direcciones.$d$,
  descripcion_larga_en = $d$Konfort Plus Security Bars are designed to provide support and safety in the home, especially in environments such as the bathroom and bedroom. Made from durable chromed steel, they offer a reliable solution for individuals with reduced mobility or those requiring greater stability. Available in four sizes (30.48 cm, 40.64 cm, 45.72 cm, and 60.96 cm), these bars can be installed at various angles and directions, providing support where it is most needed.

The Konfort Plus 60.96 cm safety bar is made of chrome-plated steel and gives the user support and safety in the bathroom and bedroom. It is sold in four sizes (30.48, 40.64, 45.72 and 60.96 cm) and can be installed at different angles and directions.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KP68083"},{"clave":"Largo","grupo":"Dimensiones","valor":"60,96 cm"},{"clave":"Material","grupo":"Material","valor":"Acero cromado"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Acero cromado resistente de 60,96 cm.","Instalable en distintos ángulos y direcciones.","Cuatro tamaños para baño o habitación."],"beneficios_en":["Sturdy chrome-plated steel, 60.96 cm.","Installable at different angles and directions.","Four sizes for bathroom or bedroom."],"valor_es":"Una barra de seguridad de acero cromado en cuatro tamaños.","valor_en":"A chrome steel safety bar in four sizes.","preguntas_frecuentes_es":[{"q":"¿En qué tamaños viene?","a":"30,48; 40,64; 45,72 y 60,96 cm."},{"q":"¿De qué material es?","a":"Acero cromado."},{"q":"¿Dónde se puede instalar?","a":"En el baño y la habitación, en distintos ángulos y direcciones."},{"q":"¿Dónde descargo la ficha técnica de Barra De Seguridad Tamaño - 60.96 cm Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which sizes does it come in?","a":"30.48, 40.64, 45.72 and 60.96 cm."},{"q":"What material is it?","a":"Chrome-plated steel."},{"q":"Where can it be installed?","a":"In the bathroom and bedroom, at different angles and directions."},{"q":"Where can I download the Konfort Plus Security Bar Size - 60.96 cm datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["barra de seguridad 60,96 cm","barra de apoyo para baño","barra de seguridad de acero cromado","barra Konfort Plus","ayudas para el baño Colombia","ficha técnica KP68083"],"seo_keywords_en":["60.96 cm safety bar","bathroom grab bar","chrome steel safety bar","Konfort Plus grab bar","bathroom aids Colombia","KP68083 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCBIOZBQGISFCLRBBAY5OPTKQBTI?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'barra-de-seguridad-tamano-60-96-cm-ref-kp68083-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/jbs168-1-ft.pdf',
  descripcion_larga_es = $d$La Grúa Hidráulica Konfort Plus está diseñada para realizar transferencias seguras y cómodas de pacientes con movilidad limitada. Fabricada en acero de alta resistencia y equipada con una palanca hidráulica, esta grúa permite levantar y bajar al paciente con un esfuerzo mínimo, facilitando el trabajo del cuidador. Con una capacidad de peso de hasta 180 kg y una apertura interior ajustable, es ideal para su uso en una variedad de entornos, desde clínicas hasta el hogar.

La grúa hidráulica Konfort Plus permite realizar transferencias seguras y cómodas (elevación, descenso y traslados cortos) a pacientes dependientes con limitaciones de movilidad, con un esfuerzo mínimo para el cuidador. Tiene palanca hidráulica fácil de usar, estructura de acero, ruedas macizas de 4" (dos con freno y dos sin freno), arnés de tela impermeable de 92 x 45 cm y capacidad de 180 kg. Es clase I (riesgo bajo) con registro 2016DM-0015510.$d$,
  descripcion_larga_en = $d$The Konfort Plus Hydraulic Patient Lift is designed to perform safe and comfortable transfers of patients with limited mobility. Fabricated from high-strength steel and equipped with a hydraulic lever, this lift enables raising and lowering the patient with minimal effort, facilitating caregiver work. With a weight capacity of up to 180 kg and an adjustable interior opening, it is ideal for use in various settings, from clinics to home environments.

The Konfort Plus hydraulic lift enables safe, comfortable transfers (lifting, lowering and short moves) for dependent patients with mobility limitations, with minimal effort for the caregiver. It has an easy-to-use hydraulic lever, a steel structure, 4" solid wheels (two braked, two unbraked), a 92 x 45 cm waterproof fabric sling and a 180 kg capacity. It is class I (low risk) with registration 2016DM-0015510.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"JBS168-1"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"180 kg"},{"clave":"Mecanismo","grupo":"Accionamiento","valor":"Hidráulico"},{"clave":"Ruedas","grupo":"Ruedas","valor":"4 macizas de 4\" (2 con freno)"},{"clave":"Registro sanitario","grupo":"Regulatorio","valor":"2016DM-0015510; clase I"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Transferencias seguras con mínimo esfuerzo del cuidador.","Palanca hidráulica fácil de operar y ruedas macizas de 4\" (dos con freno).","Capacidad de 180 kg con arnés de tela impermeable."],"beneficios_en":["Safe transfers with minimal caregiver effort.","Easy-to-operate hydraulic lever and 4\" solid wheels (two braked).","180 kg capacity with waterproof fabric sling."],"valor_es":"Una grúa hidráulica para transferencias seguras de pacientes de hasta 180 kg.","valor_en":"A hydraulic lift for safe transfers of patients up to 180 kg.","preguntas_frecuentes_es":[{"q":"¿Qué capacidad tiene?","a":"180 kg."},{"q":"¿Cómo se acciona?","a":"Con una palanca hidráulica."},{"q":"¿Qué incluye?","a":"Estructura con arnés de tela impermeable de 92 x 45 cm, según la ficha."},{"q":"¿Dónde descargo la ficha técnica de Grúa Hidráulica Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What capacity does it have?","a":"180 kg."},{"q":"How is it operated?","a":"With a hydraulic lever."},{"q":"What does it include?","a":"A structure with a 92 x 45 cm waterproof fabric sling, per the datasheet."},{"q":"Where can I download the Konfort Plus Hydraulic Patient Lift datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["grúa hidráulica para pacientes","grúa de transferencia","grúa para cuidador","grúa Konfort Plus","grúas de pacientes Colombia","ficha técnica JBS168-1"],"seo_keywords_en":["hydraulic patient lift","transfer lift","caregiver lift","Konfort Plus lift","patient lifts Colombia","JBS168-1 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCYGJK5XIUOFD4NLP2QFVMWBTFUM?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'grua-hidraulica-ref-jbs168-1-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kpc-bd02-ft.pdf',
  descripcion_larga_es = $d$La cama eléctrica de 3 funciones está diseñada para ofrecer comodidad al paciente y facilitar las labores de cuidado. Permite ajustar de manera eléctrica la elevación del espaldar, la sección de las piernas y la altura de la cama, adaptándose a diferentes necesidades de descanso y posicionamiento. Su estructura resistente proporciona estabilidad durante el uso.

La cama eléctrica de 3 funciones Konfort Plus permite ajustar eléctricamente la posición (respaldo 0° a 75° y piernas 0° a 25°) con un control de fácil operación. Soporta 200 kg, tiene barandas de un cuerpo con seguro, atril portasueros, colchón de espuma de alta densidad, bandeja auxiliar de alimentación, ruedas de 5" y opera a 100-230 V. Registro sanitario 2025DM-0031142; garantía de 1 año en estructura y 2 años en componentes eléctricos.$d$,
  descripcion_larga_en = $d$The 3-function electric hospital bed is designed to provide patient comfort and facilitate caregiving tasks. It allows electric adjustment of the backrest, leg section, and bed height, adapting to different resting and positioning needs. Its sturdy structure ensures stability during use.

The Konfort Plus 3-function electric bed lets you electrically adjust the position (backrest 0° to 75° and legs 0° to 25°) with an easy-to-use control. It supports 200 kg, has one-piece locking side rails, an IV pole, a high-density foam mattress, an auxiliary meal tray, 5" wheels and operates at 100-230 V. Health registration 2025DM-0031142; 1-year warranty on structure and 2 years on electrical components.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KPC-BD02"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"200 kg"},{"clave":"Respaldo / piernas","grupo":"Ajustes","valor":"0-75° / 0-25°"},{"clave":"Largo total","grupo":"Dimensiones","valor":"218 cm"},{"clave":"Alimentación","grupo":"Eléctrico","valor":"100 - 230 V AC"},{"clave":"Registro sanitario","grupo":"Regulatorio","valor":"2025DM-0031142"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Ajuste eléctrico de respaldo (0-75°) y piernas (0-25°) con control sencillo.","Capacidad de 200 kg, barandas con seguro, atril y bandeja auxiliar.","Garantía de 1 año en estructura y 2 años en componentes eléctricos."],"beneficios_en":["Electric adjustment of backrest (0-75°) and legs (0-25°) with a simple control.","200 kg capacity, locking rails, IV pole and auxiliary tray.","1-year warranty on structure and 2 years on electrical components."],"valor_es":"Una cama eléctrica de tres funciones para uso domiciliario o institucional.","valor_en":"A three-function electric bed for home or institutional use.","preguntas_frecuentes_es":[{"q":"¿Qué ajustes eléctricos tiene?","a":"Respaldo de 0° a 75° y piernas de 0° a 25°."},{"q":"¿Qué capacidad tiene?","a":"200 kg."},{"q":"¿Qué garantía tiene?","a":"1 año en estructura metálica y sistema mecánico, y 2 años en componentes eléctricos."},{"q":"¿Dónde descargo la ficha técnica de Cama Eléctrica 3 funciones?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which electric adjustments does it have?","a":"Backrest 0° to 75° and legs 0° to 25°."},{"q":"What capacity does it have?","a":"200 kg."},{"q":"What warranty does it have?","a":"1 year on metal structure and mechanical system, and 2 years on electrical components."},{"q":"Where can I download the 3-Function Electric Hospital Bed datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["cama eléctrica 3 funciones","cama hospitalaria domiciliaria","cama eléctrica con barandas","cama Konfort Plus","camas hospitalarias Colombia","ficha técnica KPC-BD02"],"seo_keywords_en":["3-function electric bed","home hospital bed","electric bed with rails","Konfort Plus bed","hospital beds Colombia","KPC-BD02 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCYPCWTIE6SJGHZPF66LRNMKY3E4?version=5.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'cama-electrica-3-funciones-ref-kpc-bd02';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kpsempa2g1-27-ft.pdf',
  descripcion_larga_es = $d$La Superficie Especial para el Manejo de la Presión SEMP I  de Konfort Plus es una solución avanzada para la prevención de úlceras por presión en pacientes con riesgo moderado. Fabricada en PVC de grado médico y diseñada con una estructura de burbujas, esta superficie distribuye la presión de manera uniforme, evitando la compresión vascular prolongada y disminuyendo significativamente el riesgo de úlceras.

La superficie especial para el manejo de la presión SEMP I de Konfort Plus es un colchón antiescaras de burbujas fabricado en PVC de grado médico (0,3 mm), de 200 x 90 cm, con bomba regulable y manguera flexible. Evita la compresión vascular prolongada y reduce el riesgo de úlceras por presión; soporta hasta 130 kg, trabaja a 50-110 mmHg, 120 V / 60 Hz con ciclo de 12 minutos y flujo de 5 a 7 L/min. Clase IIA con registro 2024DM-0029903.$d$,
  descripcion_larga_en = $d$The Konfort Plus Pressure Management Special Surface SEMP I is an advanced solution for preventing pressure ulcers in patients at moderate risk. Constructed from medical-grade PVC with a bubble-structured design, this surface distributes pressure evenly, preventing prolonged vascular compression and significantly reducing ulcer risk.

The Konfort Plus SEMP I special pressure-management surface is an alternating-bubble anti-decubitus mattress made of medical-grade PVC (0.3 mm), 200 x 90 cm, with an adjustable pump and flexible hose. It avoids prolonged vascular compression and reduces the risk of pressure ulcers; it supports up to 130 kg, works at 50-110 mmHg, 120 V / 60 Hz with a 12-minute cycle and 5 to 7 L/min flow. Class IIA with registration 2024DM-0029903.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KPSEMPA2G1-27"},{"clave":"Capacidad de peso","grupo":"Capacidad","valor":"Hasta 130 kg"},{"clave":"Tamaño","grupo":"Dimensiones","valor":"200 x 90 cm"},{"clave":"Rango de presión","grupo":"Rendimiento","valor":"50 - 110 mmHg"},{"clave":"Alimentación","grupo":"Eléctrico","valor":"120 V / 60 Hz"},{"clave":"Registro sanitario","grupo":"Regulatorio","valor":"2024DM-0029903; clase IIA"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Colchón de burbujas en PVC de grado médico para reducir el riesgo de úlceras por presión.","Bomba regulable (50-110 mmHg) con ciclo de 12 minutos y manguera flexible.","Soporta hasta 130 kg; 200 x 90 cm."],"beneficios_en":["Medical-grade PVC bubble mattress to reduce the risk of pressure ulcers.","Adjustable pump (50-110 mmHg) with a 12-minute cycle and flexible hose.","Supports up to 130 kg; 200 x 90 cm."],"valor_es":"Un colchón antiescaras de burbujas con bomba regulable.","valor_en":"An alternating-bubble anti-bedsore mattress with adjustable pump.","preguntas_frecuentes_es":[{"q":"¿Qué capacidad de peso tiene?","a":"Hasta 130 kg."},{"q":"¿Qué presión maneja?","a":"Entre 50 y 110 mmHg."},{"q":"¿Qué medidas tiene?","a":"200 x 90 cm."},{"q":"¿Dónde descargo la ficha técnica de Superficie Especial para el Manejo de la Presión SEMP I Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What weight capacity does it have?","a":"Up to 130 kg."},{"q":"What pressure range does it handle?","a":"Between 50 and 110 mmHg."},{"q":"What are its dimensions?","a":"200 x 90 cm."},{"q":"Where can I download the Konfort Plus Pressure Management Special Surface SEMP I datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["colchón antiescaras con bomba","superficie especial para manejo de presión","colchón anti-decúbito de burbujas","colchón antiescaras Konfort Plus","prevención de úlceras por presión Colombia","ficha técnica KPSEMPA2G1-27"],"seo_keywords_en":["anti-bedsore mattress with pump","special pressure-management surface","alternating bubble anti-decubitus mattress","Konfort Plus anti-bedsore mattress","pressure ulcer prevention Colombia","KPSEMPA2G1-27 datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCE7ZAUFSTGFHM5ARN2ILZMPHDB4?version=2.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'superficie-especial-para-el-manejo-de-la-presion-semp-i-ref-kpsempa2g1-27-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kbf-ab23-sm-ft.pdf',
  descripcion_larga_es = $d$La Faja Abdominal Konfort Plus está diseñada para brindar soporte y mejorar la funcionalidad de los músculos abdominales en casos postoperatorios, hernias o postparto. Elaborada con elástico libre de látex, esta faja ofrece un ajuste cómodo y seguro, gracias a su sistema de velcro reforzado. Además, cuenta con tres barras verticales en la parte posterior hechas de polipropileno, que proporcionan estabilidad adicional y apoyo a la zona lumbar.

La faja abdominal Konfort Plus (23 cm, talla S/M) está elaborada en elástico libre de látex, velcro gancho y felpa, con soporte de plaquetas posteriores de polipropileno. Brinda soporte y mejora la funcionalidad de los músculos abdominales en postoperatorios, hernias y posparto, y se ofrece en alturas de 23 y 30 cm y tallas S/M y L/XL.$d$,
  descripcion_larga_en = $d$The Konfort Plus Abdominal Belt is designed to provide support and improve the functionality of abdominal muscles in postoperative cases, hernias, or postpartum recovery. Made with latex-free elastic material, this belt offers a comfortable and secure fit through reinforced velcro. Additionally, it features three vertical polypropylene bars on the posterior side that provide additional stability and lumbar support.

The Konfort Plus abdominal binder (23 cm, size S/M) is made of latex-free elastic, hook-and-loop fastener and plush, with polypropylene rear stay supports. It provides support and improves abdominal muscle function in post-operative cases, hernias and post-partum, and is offered in 23 and 30 cm heights and sizes S/M and L/XL.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KBF-AB23-SM"},{"clave":"Material","grupo":"Material","valor":"Elástico libre de látex, velcro y felpa; 3 barras posteriores de polipropileno"},{"clave":"Altura / talla","grupo":"Dimensiones","valor":"23 cm, S/M"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Elástico libre de látex con cierre de velcro ajustable.","Plaquetas posteriores de polipropileno que aportan soporte.","Indicada en postoperatorios, hernias y posparto."],"beneficios_en":["Latex-free elastic with adjustable hook-and-loop closure.","Polypropylene rear stays that add support.","Indicated for post-operative care, hernias and post-partum."],"valor_es":"Una faja abdominal de soporte para postoperatorio, hernias y posparto.","valor_en":"An abdominal support binder for post-operative care, hernias and post-partum.","preguntas_frecuentes_es":[{"q":"¿Para qué se usa?","a":"Para dar soporte abdominal en postoperatorios, hernias y posparto."},{"q":"¿Qué alturas y tallas existen?","a":"Alturas de 23 y 30 cm; tallas S/M y L/XL."},{"q":"¿Contiene látex?","a":"No, el elástico es libre de látex."},{"q":"¿Dónde descargo la ficha técnica de Faja Abdominal De 23 cm Talla S/M?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What is it used for?","a":"To provide abdominal support in post-operative care, hernias and post-partum."},{"q":"Which heights and sizes exist?","a":"Heights of 23 and 30 cm; sizes S/M and L/XL."},{"q":"Does it contain latex?","a":"No, the elastic is latex-free."},{"q":"Where can I download the Konfort Plus 23 cm Abdominal Belt Size S/M datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["faja abdominal 23 cm, talla S/M","faja abdominal postoperatoria","faja para hernias y posparto","faja Konfort Plus","ortopedia blanda Colombia","ficha técnica KBF-AB23-SM"],"seo_keywords_en":["abdominal binder 23 cm, size S/M","post-operative abdominal binder","binder for hernias and post-partum","Konfort Plus binder","soft orthopaedics Colombia","KBF-AB23-SM datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCSDDORWVIENG65MCXJES54MCRZU?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'faja-abdominal-de-23-cm-talla-s-m-ref-kbf-ab23-sm';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kbf-ab23-sm-ft.pdf',
  descripcion_larga_es = $d$La Faja Abdominal Konfort Plus está diseñada para brindar soporte y mejorar la funcionalidad de los músculos abdominales en casos postoperatorios, hernias o postparto. Elaborada con elástico libre de látex, esta faja ofrece un ajuste cómodo y seguro, gracias a su sistema de velcro reforzado. Además, cuenta con tres barras verticales en la parte posterior hechas de polipropileno, que proporcionan estabilidad adicional y apoyo a la zona lumbar.

La faja abdominal Konfort Plus (23 cm, talla L/XL) está elaborada en elástico libre de látex, velcro gancho y felpa, con soporte de plaquetas posteriores de polipropileno. Brinda soporte y mejora la funcionalidad de los músculos abdominales en postoperatorios, hernias y posparto, y se ofrece en alturas de 23 y 30 cm y tallas S/M y L/XL.$d$,
  descripcion_larga_en = $d$The Konfort Plus Abdominal Belt is designed to provide support and improve the functionality of abdominal muscles in postoperative cases, hernias, or postpartum recovery. Made with latex-free elastic material, this belt offers a comfortable and secure fit through reinforced velcro. Additionally, it features three vertical polypropylene bars on the posterior side that provide additional stability and lumbar support.

The Konfort Plus abdominal binder (23 cm, size L/XL) is made of latex-free elastic, hook-and-loop fastener and plush, with polypropylene rear stay supports. It provides support and improves abdominal muscle function in post-operative cases, hernias and post-partum, and is offered in 23 and 30 cm heights and sizes S/M and L/XL.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KBF-AB23-LXL"},{"clave":"Material","grupo":"Material","valor":"Elástico libre de látex, velcro y felpa; 3 barras posteriores de polipropileno"},{"clave":"Altura / talla","grupo":"Dimensiones","valor":"23 cm, L/XL"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Elástico libre de látex con cierre de velcro ajustable.","Plaquetas posteriores de polipropileno que aportan soporte.","Indicada en postoperatorios, hernias y posparto."],"beneficios_en":["Latex-free elastic with adjustable hook-and-loop closure.","Polypropylene rear stays that add support.","Indicated for post-operative care, hernias and post-partum."],"valor_es":"Una faja abdominal de soporte para postoperatorio, hernias y posparto.","valor_en":"An abdominal support binder for post-operative care, hernias and post-partum.","preguntas_frecuentes_es":[{"q":"¿Para qué se usa?","a":"Para dar soporte abdominal en postoperatorios, hernias y posparto."},{"q":"¿Qué alturas y tallas existen?","a":"Alturas de 23 y 30 cm; tallas S/M y L/XL."},{"q":"¿Contiene látex?","a":"No, el elástico es libre de látex."},{"q":"¿Dónde descargo la ficha técnica de Faja Abdominal De 23 cm Talla L/XL?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What is it used for?","a":"To provide abdominal support in post-operative care, hernias and post-partum."},{"q":"Which heights and sizes exist?","a":"Heights of 23 and 30 cm; sizes S/M and L/XL."},{"q":"Does it contain latex?","a":"No, the elastic is latex-free."},{"q":"Where can I download the Konfort Plus 23 cm Abdominal Belt Size L/XL datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["faja abdominal 23 cm, talla L/XL","faja abdominal postoperatoria","faja para hernias y posparto","faja Konfort Plus","ortopedia blanda Colombia","ficha técnica KBF-AB23-LXL"],"seo_keywords_en":["abdominal binder 23 cm, size L/XL","post-operative abdominal binder","binder for hernias and post-partum","Konfort Plus binder","soft orthopaedics Colombia","KBF-AB23-LXL datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCSDDORWVIENG65MCXJES54MCRZU?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'faja-abdominal-de-23-cm-talla-l-xl-ref-kbf-ab23-lxl';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kbf-ab23-sm-ft.pdf',
  descripcion_larga_es = $d$La Faja Abdominal Konfort Plus está diseñada para brindar soporte y mejorar la funcionalidad de los músculos abdominales en casos postoperatorios, hernias o postparto. Elaborada con elástico libre de látex, esta faja ofrece un ajuste cómodo y seguro, gracias a su sistema de velcro reforzado. Además, cuenta con tres barras verticales en la parte posterior hechas de polipropileno, que proporcionan estabilidad adicional y apoyo a la zona lumbar.

La faja abdominal Konfort Plus (30 cm, talla S/M) está elaborada en elástico libre de látex, velcro gancho y felpa, con soporte de plaquetas posteriores de polipropileno. Brinda soporte y mejora la funcionalidad de los músculos abdominales en postoperatorios, hernias y posparto, y se ofrece en alturas de 23 y 30 cm y tallas S/M y L/XL.$d$,
  descripcion_larga_en = $d$The Konfort Plus Abdominal Belt is designed to provide support and improve the functionality of abdominal muscles in postoperative cases, hernias, or postpartum recovery. Made with latex-free elastic material, this belt offers a comfortable and secure fit through reinforced velcro. Additionally, it features three vertical polypropylene bars on the posterior side that provide additional stability and lumbar support.

The Konfort Plus abdominal binder (30 cm, size S/M) is made of latex-free elastic, hook-and-loop fastener and plush, with polypropylene rear stay supports. It provides support and improves abdominal muscle function in post-operative cases, hernias and post-partum, and is offered in 23 and 30 cm heights and sizes S/M and L/XL.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KBF-AB30-SM"},{"clave":"Material","grupo":"Material","valor":"Elástico libre de látex, velcro y felpa; 3 barras posteriores de polipropileno"},{"clave":"Altura / talla","grupo":"Dimensiones","valor":"30 cm, S/M"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Elástico libre de látex con cierre de velcro ajustable.","Plaquetas posteriores de polipropileno que aportan soporte.","Indicada en postoperatorios, hernias y posparto."],"beneficios_en":["Latex-free elastic with adjustable hook-and-loop closure.","Polypropylene rear stays that add support.","Indicated for post-operative care, hernias and post-partum."],"valor_es":"Una faja abdominal de soporte para postoperatorio, hernias y posparto.","valor_en":"An abdominal support binder for post-operative care, hernias and post-partum.","preguntas_frecuentes_es":[{"q":"¿Para qué se usa?","a":"Para dar soporte abdominal en postoperatorios, hernias y posparto."},{"q":"¿Qué alturas y tallas existen?","a":"Alturas de 23 y 30 cm; tallas S/M y L/XL."},{"q":"¿Contiene látex?","a":"No, el elástico es libre de látex."},{"q":"¿Dónde descargo la ficha técnica de Faja Abdominal De 30 cm Talla S/M?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What is it used for?","a":"To provide abdominal support in post-operative care, hernias and post-partum."},{"q":"Which heights and sizes exist?","a":"Heights of 23 and 30 cm; sizes S/M and L/XL."},{"q":"Does it contain latex?","a":"No, the elastic is latex-free."},{"q":"Where can I download the Konfort Plus 30 cm Abdominal Belt Size S/M datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["faja abdominal 30 cm, talla S/M","faja abdominal postoperatoria","faja para hernias y posparto","faja Konfort Plus","ortopedia blanda Colombia","ficha técnica KBF-AB30-SM"],"seo_keywords_en":["abdominal binder 30 cm, size S/M","post-operative abdominal binder","binder for hernias and post-partum","Konfort Plus binder","soft orthopaedics Colombia","KBF-AB30-SM datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCSDDORWVIENG65MCXJES54MCRZU?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'faja-abdominal-de-30-cm-talla-s-m-ref-kbf-ab30-sm';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kbf-ab23-sm-ft.pdf',
  descripcion_larga_es = $d$La Faja Abdominal Konfort Plus está diseñada para brindar soporte y mejorar la funcionalidad de los músculos abdominales en casos postoperatorios, hernias o postparto. Elaborada con elástico libre de látex, esta faja ofrece un ajuste cómodo y seguro, gracias a su sistema de velcro reforzado. Además, cuenta con tres barras verticales en la parte posterior hechas de polipropileno, que proporcionan estabilidad adicional y apoyo a la zona lumbar.

La faja abdominal Konfort Plus (30 cm, talla L/XL) está elaborada en elástico libre de látex, velcro gancho y felpa, con soporte de plaquetas posteriores de polipropileno. Brinda soporte y mejora la funcionalidad de los músculos abdominales en postoperatorios, hernias y posparto, y se ofrece en alturas de 23 y 30 cm y tallas S/M y L/XL.$d$,
  descripcion_larga_en = $d$30 cm abdominal support belt made of latex-free elastic and reinforced Velcro system. Includes three vertical polypropylene bars at the back for lumbar stability. Designed for support and compression in postoperative care, hernias, and postpartum recovery.

The Konfort Plus abdominal binder (30 cm, size L/XL) is made of latex-free elastic, hook-and-loop fastener and plush, with polypropylene rear stay supports. It provides support and improves abdominal muscle function in post-operative cases, hernias and post-partum, and is offered in 23 and 30 cm heights and sizes S/M and L/XL.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KBF-AB30-LXL"},{"clave":"Material","grupo":"Material","valor":"Elástico libre de látex, velcro y felpa; 3 barras posteriores de polipropileno"},{"clave":"Altura / talla","grupo":"Dimensiones","valor":"30 cm, L/XL"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Elástico libre de látex con cierre de velcro ajustable.","Plaquetas posteriores de polipropileno que aportan soporte.","Indicada en postoperatorios, hernias y posparto."],"beneficios_en":["Latex-free elastic with adjustable hook-and-loop closure.","Polypropylene rear stays that add support.","Indicated for post-operative care, hernias and post-partum."],"valor_es":"Una faja abdominal de soporte para postoperatorio, hernias y posparto.","valor_en":"An abdominal support binder for post-operative care, hernias and post-partum.","preguntas_frecuentes_es":[{"q":"¿Para qué se usa?","a":"Para dar soporte abdominal en postoperatorios, hernias y posparto."},{"q":"¿Qué alturas y tallas existen?","a":"Alturas de 23 y 30 cm; tallas S/M y L/XL."},{"q":"¿Contiene látex?","a":"No, el elástico es libre de látex."},{"q":"¿Dónde descargo la ficha técnica de Faja Abdominal De 30 cm Talla L/XL?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What is it used for?","a":"To provide abdominal support in post-operative care, hernias and post-partum."},{"q":"Which heights and sizes exist?","a":"Heights of 23 and 30 cm; sizes S/M and L/XL."},{"q":"Does it contain latex?","a":"No, the elastic is latex-free."},{"q":"Where can I download the Abdominal Support Belt, 30 cm, Size L/XL datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["faja abdominal 30 cm, talla L/XL","faja abdominal postoperatoria","faja para hernias y posparto","faja Konfort Plus","ortopedia blanda Colombia","ficha técnica KBF-AB30-LXL"],"seo_keywords_en":["abdominal binder 30 cm, size L/XL","post-operative abdominal binder","binder for hernias and post-partum","Konfort Plus binder","soft orthopaedics Colombia","KBF-AB30-LXL datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCSDDORWVIENG65MCXJES54MCRZU?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'faja-abdominal-de-30-cm-talla-l-xl-ref-kbf-ab30-lxl';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kbf-camp-sm-ft.pdf',
  descripcion_larga_es = $d$La Faja Lumbosacra Tipo Camp de Konfort Plus está diseñada para brindar soporte y alivio en tratamientos de espóndilo artrosis, esguinces y desgarres musculares en la región lumbar. Fabricada en materiales hipoalergénicos y transpirables, esta faja incluye barras de aluminio posteriores que se adaptan a la estructura de la espalda, proporcionando una compresión eficaz que limita parcialmente los movimientos de la columna lumbar.

La faja lumbosacra tipo Camp Konfort Plus (talla S/M) está elaborada en bondeados de poliéster hipoalergénico y respirable, resortes laterales resistentes y bandas elásticas libres de látex, con velcro y varillas de aluminio posteriores contorneadas a la espalda. Está diseñada para espondiloartrosis, esguinces y desgarres musculares lumbares, escoliosis menores de 25° y postoperatorios de columna lumbosacra, comprimiendo y limitando parcialmente el movimiento lumbar.$d$,
  descripcion_larga_en = $d$The Konfort Plus Lumbosacral Camp Type Belt is designed to provide support and relief in the treatment of spondyloarthritis, sprains, and muscle tears in the lumbar region. Made from hypoallergenic and breathable materials, this belt features posterior aluminum bars that adapt to the back structure, providing effective compression that partially limits lumbar spine movements.

The Konfort Plus Camp-type lumbosacral binder (size S/M) is made of hypoallergenic, breathable bonded polyester, strong side springs and latex-free elastic bands, with hook-and-loop fastener and rear aluminium stays contoured to the back. It is designed for spondyloarthrosis, lumbar sprains and muscle tears, scoliosis under 25° and lumbosacral spine post-operative care, compressing and partially limiting lumbar movement.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KBF-CAMP-SM"},{"clave":"Material","grupo":"Material","valor":"Poliéster hipoalergénico; varillas de aluminio posteriores"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Poliéster hipoalergénico y respirable con varillas de aluminio contorneadas.","Indicada en espondiloartrosis, esguinces, desgarres lumbares y escoliosis menores de 25°.","Compresión y limitación parcial del movimiento lumbar tras cirugía de columna."],"beneficios_en":["Hypoallergenic, breathable polyester with contoured aluminium stays.","Indicated for spondyloarthrosis, sprains, lumbar tears and scoliosis under 25°.","Compression and partial limitation of lumbar movement after spine surgery."],"valor_es":"Una faja lumbosacra con varillas de aluminio para tratamientos lumbares.","valor_en":"A lumbosacral binder with aluminium stays for lumbar treatments.","preguntas_frecuentes_es":[{"q":"¿Para qué patologías está indicada?","a":"Espondiloartrosis, esguince y desgarre muscular lumbar, escoliosis menores de 25° y postoperatorios de columna lumbosacra."},{"q":"¿De qué está hecha?","a":"Poliéster hipoalergénico y respirable, resortes laterales y bandas elásticas libres de látex."},{"q":"¿Qué tallas existen?","a":"S/M y L/XL."},{"q":"¿Dónde descargo la ficha técnica de Faja Lumbo Sacra Tipo Camp Talla S/M?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which conditions is it indicated for?","a":"Spondyloarthrosis, lumbar sprain and muscle tear, scoliosis under 25° and lumbosacral spine post-operative care."},{"q":"What is it made of?","a":"Hypoallergenic, breathable polyester, side springs and latex-free elastic bands."},{"q":"Which sizes exist?","a":"S/M and L/XL."},{"q":"Where can I download the Konfort Plus Lumbosacral Camp Type Belt Size S/M datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["faja lumbosacra tipo Camp talla S/M","faja lumbar con varillas","faja para lumbalgia","faja Konfort Plus","ortopedia blanda Colombia","ficha técnica KBF-CAMP-SM"],"seo_keywords_en":["Camp-type lumbosacral binder size S/M","lumbar binder with stays","binder for low back pain","Konfort Plus binder","soft orthopaedics Colombia","KBF-CAMP-SM datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCR2SQBHTJFNBBPD4IFFZC43WII4?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'faja-lumbo-sacra-tipo-camp-talla-s-m-ref-kbf-camp-sm';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-gmd/kbf-camp-sm-ft.pdf',
  descripcion_larga_es = $d$La Faja Lumbosacra Tipo Camp de Konfort Plus está diseñada para brindar soporte y alivio en tratamientos de espóndilo artrosis, esguinces y desgarres musculares en la región lumbar. Fabricada en materiales hipoalergénicos y transpirables, esta faja incluye barras de aluminio posteriores que se adaptan a la estructura de la espalda, proporcionando una compresión eficaz que limita parcialmente los movimientos de la columna lumbar.

La faja lumbosacra tipo Camp Konfort Plus (talla L/XL) está elaborada en bondeados de poliéster hipoalergénico y respirable, resortes laterales resistentes y bandas elásticas libres de látex, con velcro y varillas de aluminio posteriores contorneadas a la espalda. Está diseñada para espondiloartrosis, esguinces y desgarres musculares lumbares, escoliosis menores de 25° y postoperatorios de columna lumbosacra, comprimiendo y limitando parcialmente el movimiento lumbar.$d$,
  descripcion_larga_en = $d$The Konfort Plus Lumbosacral Camp Type Belt is designed to provide support and relief in the treatment of spondyloarthritis, sprains, and muscle tears in the lumbar region. Made from hypoallergenic and breathable materials, this belt features posterior aluminum bars that adapt to the back structure, providing effective compression that partially limits lumbar spine movements.

The Konfort Plus Camp-type lumbosacral binder (size L/XL) is made of hypoallergenic, breathable bonded polyester, strong side springs and latex-free elastic bands, with hook-and-loop fastener and rear aluminium stays contoured to the back. It is designed for spondyloarthrosis, lumbar sprains and muscle tears, scoliosis under 25° and lumbosacral spine post-operative care, compressing and partially limiting lumbar movement.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KBF-CAMP-LXL"},{"clave":"Material","grupo":"Material","valor":"Poliéster hipoalergénico; varillas de aluminio posteriores"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Poliéster hipoalergénico y respirable con varillas de aluminio contorneadas.","Indicada en espondiloartrosis, esguinces, desgarres lumbares y escoliosis menores de 25°.","Compresión y limitación parcial del movimiento lumbar tras cirugía de columna."],"beneficios_en":["Hypoallergenic, breathable polyester with contoured aluminium stays.","Indicated for spondyloarthrosis, sprains, lumbar tears and scoliosis under 25°.","Compression and partial limitation of lumbar movement after spine surgery."],"valor_es":"Una faja lumbosacra con varillas de aluminio para tratamientos lumbares.","valor_en":"A lumbosacral binder with aluminium stays for lumbar treatments.","preguntas_frecuentes_es":[{"q":"¿Para qué patologías está indicada?","a":"Espondiloartrosis, esguince y desgarre muscular lumbar, escoliosis menores de 25° y postoperatorios de columna lumbosacra."},{"q":"¿De qué está hecha?","a":"Poliéster hipoalergénico y respirable, resortes laterales y bandas elásticas libres de látex."},{"q":"¿Qué tallas existen?","a":"S/M y L/XL."},{"q":"¿Dónde descargo la ficha técnica de Faja Lumbo Sacra Tipo Camp Talla L/XL?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which conditions is it indicated for?","a":"Spondyloarthrosis, lumbar sprain and muscle tear, scoliosis under 25° and lumbosacral spine post-operative care."},{"q":"What is it made of?","a":"Hypoallergenic, breathable polyester, side springs and latex-free elastic bands."},{"q":"Which sizes exist?","a":"S/M and L/XL."},{"q":"Where can I download the Konfort Plus Lumbosacral Camp Type Belt Size L/XL datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["faja lumbosacra tipo Camp talla L/XL","faja lumbar con varillas","faja para lumbalgia","faja Konfort Plus","ortopedia blanda Colombia","ficha técnica KBF-CAMP-LXL"],"seo_keywords_en":["Camp-type lumbosacral binder size L/XL","lumbar binder with stays","binder for low back pain","Konfort Plus binder","soft orthopaedics Colombia","KBF-CAMP-LXL datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCR2SQBHTJFNBBPD4IFFZC43WII4?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'faja-lumbo-sacra-tipo-camp-talla-l-xl-ref-kbf-camp-lxl';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kb-ra-ft.pdf',
  descripcion_larga_es = $d$La Rodillera Universal Konfort Plus es una solución ideal para quienes necesitan soporte y alivio en la articulación de la rodilla. Fabricada en neopreno de alta calidad, esta rodillera proporciona calor terapéutico que ayuda a aliviar el dolor y acelerar la recuperación de lesiones como subluxaciones de la rótula y esguinces leves.

La rodillera ajustable talla universal Konfort Plus está elaborada en neopreno (caucho multidireccional recubierto en nailon-poliéster) con cierre de velcro, y aporta calor a la articulación. Tiene orificio patelar que ayuda a mantener la rótula alineada. Está indicada en la recuperación de subluxaciones de rótula, esguinces leves de rodilla o como soporte deportivo.$d$,
  descripcion_larga_en = $d$The Konfort Plus Universal Knee Brace is an ideal solution for those requiring support and relief in the knee joint. Made of high-quality neoprene, this knee brace provides therapeutic heat that helps relieve pain and accelerate recovery from injuries such as patellar subluxations and mild sprains.

The Konfort Plus adjustable universal-size knee support is made of neoprene (multidirectional rubber covered with nylon-polyester) with hook-and-loop closure, and provides warmth to the joint. It has a patellar opening that helps keep the kneecap aligned. It is indicated for recovery from patellar subluxations, mild knee sprains or as sports support.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KB-RA"},{"clave":"Material","grupo":"Material","valor":"Neopreno recubierto en nailon-poliéster y velcro"},{"clave":"Talla","grupo":"Talla","valor":"Universal ajustable"},{"clave":"Color","grupo":"Color","valor":"Negro"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Neopreno que da calor a la articulación y velcro ajustable.","Orificio patelar que ayuda a mantener la rótula alineada.","Para subluxaciones de rótula, esguinces leves o soporte deportivo."],"beneficios_en":["Neoprene that warms the joint and adjustable hook-and-loop closure.","Patellar opening that helps keep the kneecap aligned.","For patellar subluxations, mild sprains or sports support."],"valor_es":"Una rodillera de neopreno con orificio patelar y ajuste universal.","valor_en":"A neoprene knee brace with patellar opening and universal fit.","preguntas_frecuentes_es":[{"q":"¿Qué talla es?","a":"Talla universal ajustable con velcro."},{"q":"¿Para qué se usa?","a":"Recuperación de subluxaciones de rótula, esguinces leves de rodilla o soporte deportivo."},{"q":"¿De qué material es?","a":"Neopreno con velcro."},{"q":"¿Dónde descargo la ficha técnica de Rodillera Universal Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"What size is it?","a":"Universal size adjustable with hook-and-loop."},{"q":"What is it used for?","a":"Recovery from patellar subluxations, mild knee sprains or sports support."},{"q":"What material is it?","a":"Neoprene with hook-and-loop."},{"q":"Where can I download the Konfort Plus Universal Knee Brace datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["rodillera ajustable talla universal","rodillera de neopreno","soporte de rodilla con orificio patelar","rodillera Konfort Plus","ortopedia blanda Colombia","ficha técnica KB-RA"],"seo_keywords_en":["adjustable universal knee support","neoprene knee brace","knee support with patellar opening","Konfort Plus knee brace","soft orthopaedics Colombia","KB-RA datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCC5EPGEAM3RCQ7HZYV3TIWNDI7Q?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'rodillera-universal-ref-kb-ra-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kbc-aa-ft.pdf',
  descripcion_larga_es = $d$El Cabestrillo Adulto de Konfort Plus está diseñado para proporcionar un soporte confiable en casos de traumas, inestabilidad, fracturas, esguinces y lesiones de hombro y codo. Fabricado en resistente tela de dril y reforzado con reatas y hebillas, este cabestrillo garantiza una inmovilización cómoda y segura, con un diseño que incluye un inmovilizador circular en la espalda para mayor estabilidad.

El cabestrillo adulto azul profundo Konfort Plus está elaborado en tela de algodón con reatas y bondeado de poliéster, y brinda soporte en traumas e inestabilidad con un inmovilizador circular a la espalda. Está indicado en fracturas, esguinces y lesiones de hombro y codo; se fija por medio de reatas y hebillas.$d$,
  descripcion_larga_en = $d$The Konfort Plus Adult Sling is designed to provide reliable support for trauma, instability, fractures, sprains, and shoulder and elbow injuries. Made from durable drill fabric and reinforced with straps and buckles, this sling ensures comfortable and secure immobilization, featuring a circular back immobilizer for enhanced stability.

The Konfort Plus adult deep blue sling is made of cotton fabric with polyester straps and bonding, and gives support in trauma and instability with a circular immobiliser around the back. It is indicated for fractures, sprains and shoulder and elbow injuries; it is fastened with straps and buckles.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KBC-AA"},{"clave":"Material","grupo":"Material","valor":"Algodón (dril) con reatas y bondeado de poliéster"},{"clave":"Sujeción","grupo":"Sujeción","valor":"Reatas y hebillas"},{"clave":"Registro sanitario","grupo":"Regulatorio","valor":"2018DM-0018516"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Soporte en traumas e inestabilidad con inmovilizador circular a la espalda.","Indicado en fracturas, esguinces y lesiones de hombro y codo.","Algodón con reatas de poliéster, ajustable con hebillas."],"beneficios_en":["Support in trauma and instability with circular back immobiliser.","Indicated for fractures, sprains and shoulder and elbow injuries.","Cotton with polyester straps, adjustable with buckles."],"valor_es":"Un cabestrillo de algodón para inmovilizar hombro y codo.","valor_en":"A cotton sling to immobilise the shoulder and elbow.","preguntas_frecuentes_es":[{"q":"¿Para qué lesiones sirve?","a":"Fracturas, esguinces y lesiones de hombro y codo."},{"q":"¿Cómo se ajusta?","a":"Por medio de reatas y hebillas."},{"q":"¿Hay versión pediátrica?","a":"Sí, existe la versión pediátrica en azul y rosado y la de adulto en azul profundo."},{"q":"¿Dónde descargo la ficha técnica de Cabestrillo Adulto Color Azul Profundo Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which injuries is it for?","a":"Fractures, sprains and shoulder and elbow injuries."},{"q":"How is it adjusted?","a":"With straps and buckles."},{"q":"Is there a paediatric version?","a":"Yes, the paediatric version comes in blue and pink and the adult in deep blue."},{"q":"Where can I download the Konfort Plus Adult Sling Deep Blue datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["cabestrillo adulto azul profundo","cabestrillo para hombro y codo","cabestrillo de algodón","cabestrillo Konfort Plus","ortopedia blanda Colombia","ficha técnica KBC-AA"],"seo_keywords_en":["adult deep blue sling","shoulder and elbow sling","cotton arm sling","Konfort Plus sling","soft orthopaedics Colombia","KBC-AA datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MC2TIO6ZNC4NC25CNNR6FE22SU34?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'cabestrillo-adulto-color-azul-profundo-ref-kbc-aa-konfort-plus';

UPDATE public.productos SET
  ficha_pdf = '/assets/productos/fichas/gmd-konfort-plus/kbc-pa-ft.pdf',
  descripcion_larga_es = $d$El Cabestrillo Pediátrico de Konfort Plus está diseñado para proporcionar un soporte seguro y cómodo en casos de traumas, esguinces, fracturas o lesiones en hombro y codo en pacientes pediátricos. Fabricado en resistente tela de dril, fácil de lavar, y reforzado con reatas y hebillas, este cabestrillo ofrece una inmovilización confiable para facilitar la recuperación. Incluye un inmovilizador circular en la espalda para mayor estabilidad y seguridad.

El cabestrillo pediátrico azul Konfort Plus está elaborado en tela de algodón con reatas y bondeado de poliéster, y brinda soporte en traumas e inestabilidad con un inmovilizador circular a la espalda. Está indicado en fracturas, esguinces y lesiones de hombro y codo; se fija por medio de reatas y hebillas.$d$,
  descripcion_larga_en = $d$The Konfort Plus Pediatric Sling is designed to provide safe and comfortable support for pediatric patients experiencing trauma, sprains, fractures, or shoulder and elbow injuries. Made from durable, washable drill fabric and reinforced with straps and buckles, this sling offers reliable immobilization to facilitate recovery. It includes a circular back immobilizer for enhanced stability and safety.

The Konfort Plus paediatric blue sling is made of cotton fabric with polyester straps and bonding, and gives support in trauma and instability with a circular immobiliser around the back. It is indicated for fractures, sprains and shoulder and elbow injuries; it is fastened with straps and buckles.$d$,
  especificaciones = $j$[{"clave":"Marca / fabricante","grupo":"Identificación","valor":"Konfort Plus (GMD)"},{"clave":"Referencia","grupo":"Identificación","valor":"KBC-PA"},{"clave":"Material","grupo":"Material","valor":"Algodón (dril) con reatas y bondeado de poliéster"},{"clave":"Sujeción","grupo":"Sujeción","valor":"Reatas y hebillas"},{"clave":"Registro sanitario","grupo":"Regulatorio","valor":"2018DM-0018516"}]$j$::jsonb,
  atributos = COALESCE(atributos, '{}'::jsonb) || $j${"beneficios_es":["Soporte en traumas e inestabilidad con inmovilizador circular a la espalda.","Indicado en fracturas, esguinces y lesiones de hombro y codo.","Algodón con reatas de poliéster, ajustable con hebillas."],"beneficios_en":["Support in trauma and instability with circular back immobiliser.","Indicated for fractures, sprains and shoulder and elbow injuries.","Cotton with polyester straps, adjustable with buckles."],"valor_es":"Un cabestrillo de algodón para inmovilizar hombro y codo.","valor_en":"A cotton sling to immobilise the shoulder and elbow.","preguntas_frecuentes_es":[{"q":"¿Para qué lesiones sirve?","a":"Fracturas, esguinces y lesiones de hombro y codo."},{"q":"¿Cómo se ajusta?","a":"Por medio de reatas y hebillas."},{"q":"¿Hay versión pediátrica?","a":"Sí, existe la versión pediátrica en azul y rosado y la de adulto en azul profundo."},{"q":"¿Dónde descargo la ficha técnica de Cabestrillo Pediátrico Color Azul Konfort Plus?","a":"En esta página, con el botón «Descargar ficha técnica»: es el PDF oficial de GMD (marca Konfort Plus) (en español)."}],"preguntas_frecuentes_en":[{"q":"Which injuries is it for?","a":"Fractures, sprains and shoulder and elbow injuries."},{"q":"How is it adjusted?","a":"With straps and buckles."},{"q":"Is there a paediatric version?","a":"Yes, the paediatric version comes in blue and pink and the adult in deep blue."},{"q":"Where can I download the Konfort Plus Pediatric Sling Blue datasheet?","a":"On this page, with the “Download datasheet” button: it is the official GMD (marca Konfort Plus) PDF (in Spanish)."}],"seo_keywords_es":["cabestrillo pediátrico azul","cabestrillo para hombro y codo","cabestrillo de algodón","cabestrillo Konfort Plus","ortopedia blanda Colombia","ficha técnica KBC-PA"],"seo_keywords_en":["paediatric blue sling","shoulder and elbow sling","cotton arm sling","Konfort Plus sling","soft orthopaedics Colombia","KBC-PA datasheet"],"ficha_fabricante":{"fabricante":"GMD (marca Konfort Plus)","idioma":"es","url_origen":"https://www.gmd.com.co/sfsites/c/cms/delivery/media/MCBAXQDXGSSRDJVNOXVJ75DD6HGE?version=1.1&channelId=0apVT00000000Xu&oid=00D3t000001N5bX","descargada":"2026-10-02"}}$j$::jsonb
WHERE slug = 'cabestrillo-pediatrico-color-azul-ref-kbc-pa-konfort-plus';
